an <- c(
  "Abutilon avicennae", "Abutilon theophrasti Medik.",
  "Acer campestre", "Acer campestre L.", 
  "Acer tataricum", "Acer tataricum L.",
  "Adonis aestivalis", "Adonis aestivalis L.",
  "Agrimonia odorata", "",
  "Agrostemma githago f. latisecta f. nov.", "Agrostemma githago L.",
  "Ailanthus glandulosa Desf.", "Ailanthus altissima (Mill.) Swingle", 
  "Aira caryophyllea", "Aira caryophyllea L.", 
  "Allium senescens", "Allium senescens L.",
  "Allium sibiricum", "Allium schoenoprasum L.",
  "Allium ursinum", "Allium ursinum L.",
  "Allium victorialis", "Allium victorialis L.",
  "Alyssum argenteum", "Odontarrhena argentea (All.) Ledeb.",
  "Amarantus albus", "Amaranthus albus L.",
  "Amarantus angustifolius Lam.", "Amaranthus graecizans L.",
  "Amarantus angustifolius var. graecizans (L.) Thell.", "Amaranthus graecizans L.",
  "Amarantus cruentus var.paniculatus","Amaranthus cruentus L.",
  "Amarantus hypochondriacus var. chlorostachys", "Amaranthus hypochondriacus L.",
  "Andropogon halepensis f . muticus Hackel", "Sorghum halepense (L.) Pers.",
  "Androsace septentrionalis", "Androsace septentrionalis L.",  
  "Anemone pratensis", "Pulsatilla pratensis subsp. pratensis ", 
  "Antennaria margaritacea", "Antennaria margaritacea R.Br., 1817",
  "Anthemis tinctoria", "Cota tinctoria subsp. tinctoria", 
  "Anthericum ramosum", "Anthericum ramosum L.",
  "Anthoxanthum aristatum", "Anthoxanthum aristatum Boiss.",
  "Anthriscus nitida", "Anthriscus nitidus (Wahlenb.) Hazsl.",
  "Antirrhinum orontium", "Misopates orontium subsp. orontium (Linnaeus) Rafinesque",
  "Arabis hirsuta", "Arabis hirsuta (L.) Scop.",
  "Archangelica officinalis", "Angelica archangelica subsp. archangelica", 
  "Arnica montana", "Arnica montana L.",
  "Aristolochia clematitis", "Aristolochia clematitis L.",
  "Armeria vulgaris", "Armeria maritima subsp. elongata (Hoffm.) Bonnier",
  "Arrhenatherum elatius f. biaristatum", "Arrhenatherum elatius (L.) P.Beauv. ex J.Presl & C.Presl",
  "Artemisia annua", "Artemisia annua L.", 
  "Artemisia campestris", "Artemisia campestris L.", 
  "Artemisia pontica", "Artemisia pontica L.",
  "Asperugo procumbens", "Asperugo procumbens L.",
  "Asperula aparine", "Galium aparine L.", 
  "Asperula odorata", "Galium odoratum (L.) Scop.", 
  "Aspidium dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Aspidium Dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Aspidium filix mas var. deorsolobatum", "",
  "Aspidium lonchitis (L.) Sw.", "Polystichum lonchitis (L.) Roth", 
  "Aspidium montanum (Vogler) Aschs.", "Oreopteris limbosperma (All.) Holub", 
  "Aspidium phegopteris", "Phegopteris connectilis (Michx.) Watt", 
  "Aspidium Phegopteris", "Phegopteris connectilis (Michx.) Watt", 
  "Aspidium robertianum", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Aspidium Robertianum", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Aspidium spinulosum", "Dryopteris carthusiana (Vill.) H.P.Fuchs", 
  "Aspidium tanacetifolium", "Dryopteris dilatata subsp. dilatata", 
  "Aspidium thelypteris", "Thelypteris palustris subsp. palustris", 
  "Aspidium Thelypteris", "Thelypteris palustris subsp. palustris", 
  "Aspidium thelypteris (L.) Sw.", "Thelypteris palustris subsp. palustris", 
  "Asplenium fllix femina", "Athyrium filix-femina (L.) Roth", 
  "Asplenium germanicum Weis.", "Asplenium ruta-muraria subsp. ruta-muraria", 
  "Asplenium ruta-muraria", "Asplenium ruta-muraria L.", 
  "Asplenium Ruta muraria", "Asplenium ruta-muraria L.", 
  "Asplenium septentrionale", "Asplenium septentrionale (L.) Hoffm.", 
  "Asplenium trichomanes L.", "Asplenium trichomanes L.", 
  "Asplenium viride", "Asplenium viride Huds.", 
  "Asplenium viride Huds.", "Asplenium viride Huds.", 
  "Asplenium viride ssp. adulterinum", "Asplenium adulterinum Milde", 
  "Aster novi-belgii", "Symphyotrichum novi-belgii (L.) G.L.Nesom", 
  "Aster salignus", "Aster salignus L.", 
  "Astragalus arenarius", "Astragalus arenarius L.", 
  "Astragalus cicer", "Astragalus cicer L.",
  "Astrantia major", "Astrantia major L.",
  "Atrichum tenellum", "Atrichum tenellum Bruch & W.P.Schimper, 1844", 
  "Atriplex hortense", "Atriplex hortensis L.",
  "Atriplex hortense f. ruberrimum", "Atriplex hortensis L.",
  "Atriplex nitens", "Atriplex sagittata Borkh.",
  "Avena sativa f . aristata Krause", "Avena sativa L.",
  "Barbaraea stricta", "Barbarea stricta Andrz. ex Besser",
  "Berberis vulgaris", "Berberis vulgaris L.",
  "Berteroa incana", "Berteroa incana (L.) DC.",
  "Beta maritima L.", "Beta maritima L.", 
  "Betula pubescens x verrucosa", "", 
  "Bidens connatus", "Bidens connata Muhl. ex Willd.", 
  "Bidens melanocarpus", "Bidens frondosa L.", 
  "Blechnum spicant", "Struthiopteris spicant (L.) Weiss", 
  "Blechnum spicant (L.) Wth.", "Struthiopteris spicant (L.) Weiss", 
  "Borrago officinalis", "Borago officinalis L.", 
  "Botrychium lunaria", "Botrychium lunaria (L.) Sw.", 
  "Botrychium lunaria f. cristatum", "Botrychium lunaria (L.) Sw.",
  "Botrychium lunaria f. incisum", "Botrychium lunaria (L.) Sw.",
  "Botrychium lunaria var. subincisum Rüp.", "Botrychium lunaria (L.) Sw.",
  "Botrychium matricariae", "Sceptridium multifidum (S.G.Gmel.) Nishida ex Tagawa", 
  "Botrychium matricariaefolium", "Botrychium matricariifolium (Döll) A.Braun ex Koch", 
  "Botrychium matricarifolium", "Botrychium matricariifolium (Döll) A.Braun ex Koch", 
  "Botrychium rutaefolium A. Br.", "Sceptridium multifidum (S.G.Gmel.) Nishida ex Tagawa", 
  "Botrychium simplex Hitchcock", "Botrychium simplex E.Hitchc.", 
  "Botrychium ternatum Sw.", "Sceptridium ternatum (Thunb.) Lyon", 
  "Brassica juncea", "Brassica juncea (L.) Czern.",
  "Bromus asper", "Bromus ramosus Huds.", 
  "Bromus erectus", "Bromus erectus Huds.",
  "Bromus inermis", "Bromus inermis Leyss.",
  "Bromus racemosus", "Bromus racemosus L.",
  "Bromus sterilis", "Bromus sterilis L.",
  "Buphthalmum speciosum", "Telekia speciosa (Schreb.) Baumg.", 
  "Bupleurum tenuissimum", "Bupleurum tenuissimum L.", 
  "Butomus umbellatus", "Butomus umbellatus L.", 
  "Calendula officinalis", "Calendula officinalis L.", 
  "Calla palustris", "Calla palustris L.",
  "Camelina sativa", "Camelina sativa (L.) Crantz", 
  "Campanula patula", "Campanula patula L.", 
  "Campanula Rapunculus", "Campanula rapunculus L.", 
  "Campanula rotundifolia", "Campanula rotundifolia L.", 
  "Campanula trachelium var. calycibus complanatis", "Campanula trachelium L.", 
  "Cardamine amara", "Cardamine amara L.", 
  "Cardamine chelidonia L.", "Cardamine chelidonia L.", 
  "Carduus crispus", "Carduus crispus L.", 
  "Carex acuta x stricta", "", 
  "Carex brizoides", "Carex brizoides L.", 
  "Carex buekii", "Carex buekii Wimm.", 
  "Carex buxbaumi", "Carex buxbaumii Wahlenb.",
  "Carex buxbaumii", "Carex buxbaumii Wahlenb.", 
  "Carex caespitosa L. nach Fries.", "Carex cespitosa L.", 
  "Carex cyperoides", "Carex bohemica Schreb.",
  "Carex davalliana", "Carex davalliana Sm.", 
  "Carex davalliana Smith", "Carex davalliana Sm.", 
  "Carex disticha", "Carex disticha Huds.",
  "Carex evoluta Hartmann", "Carex ×evoluta Hartm.", 
  "Carex goodenoughi f. tornata", "Carex nigra subsp. nigra",
  "Carex goodenoughii x stricta", "",
  "Carex ligerica", "Carex colchica J.Gay",
  "Carex longifolia Host.", "Carex umbrosa subsp. umbrosa", 
  "Carex paradoxa", "Carex appropinquata Schumach.", 
  "Carex paradoxa var. gracilis Aschers, et Gr.", "Carex appropinquata Schumach.", 
  "Carex pendula", "Carex pendula Huds.",
  "Carex pilosa", "Carex pilosa Scop.", 
  "Carex pseudocyperus", "Carex pseudocyperus L.", 
  "Carex pulicaris", "Carex pulicaris L.", 
  "Carex riparia", "Carex riparia Curtis", 
  "Carex teretiuscula", "Carex teretiuscula Willd. ex Kunth, 1837",
  "Carex tomentosa", "Carex tomentosa L.",
  "Carlina acaulis", "Carlina acaulis L.", 
  "Carlina acaulis f. caulescens", "Carlina acaulis subsp. caulescens (Lam.) Schübl. & G.Martens", 
  "Centaurea phrygia", "Centaurea phrygia L.", 
  "Ceratophyllum demersum", "Ceratophyllum demersum L.",
  "Cerastium anomalum", "", 
  "Cerinthe minor", "Cerinthe minor L.", 
  "Chenopodium ficifolium", "Chenopodium ficifolium Sm.",
  "Chenopodium hircinum", "Chenopodium hircinum Schrad.",
  "Chenopodium opulifolium", "Chenopodium opulifolium Schrad.",
  "Chenopodium vulvaria", "Chenopodium vulvaria L.",
  "Chrysosplenium oppositifolium", "Chrysosplenium oppositifolium L.",
  "Cichorium intybus", "Cichorium intybus L.", 
  "Cicuta virosa", "Cicuta virosa L.", 
  "Circaea alpina", "Circaea alpina L.",
  "Circaea intermedia", "Circaea ×intermedia Ehrh.", 
  "Cirsium acaule", "Cirsium acaule (L.) All., 1780", 
  "Cirsium acaule-oleraceum", "Cirsium acaule × oleraceum", 
  "Cirsium arvense", "Cirsium arvense (L.) Scop.", 
  "Cirsium canum", "Cirsium canum (L.) All.", 
  "Cirsium canum-acaule", "", 
  "Cirsium heterophyllum", "Cirsium heterophyllum (L.) Hill", 
  "Cirsium lanceolatum-oleraceum", "", 
  "Cirsium rivulare", "Cirsium rivulare (Jacq.) All.", 
  "Coeloglossum viride", "Dactylorhiza viridis (L.) R.M.Bateman, Pridgeon & M.W.Chase",
  "Colchicum autumnale", "Colchicum autumnale L.", 
  "Conium maculatum", "Conium maculatum L.", 
  "Convallaria majalis", "Convallaria majalis L.", 
  "Convolvulus dahuricus", "Calystegia pulchra Brumm. & Heywood",
  "Cosmos bipinnatus", "Cosmos bipinnatus Cav.", 
  "Cotoneaster integerrimus", "Cotoneaster integerrimus Medik.",
  "Crepis biennis", "Crepis biennis L.", 
  "Crocus vernus", "Crocus vernus (L.) Hill",
  "Crocus vernus Wulf.", "Crocus vernus (L.) Hill",
  "Cucumis melo L.", "Cucumis melo L.",
  "Cucubalus baccifer", "Silene baccifera (L.) Roth",
  "Cucurbita maxima Duch.", "Cucurbita maxima Duchesne", 
  "Cystopteris fragilis (L.) Beruh.", "Cystopteris fragilis (L.) Bernh.", 
  "Cystopteris sudetica", "Cystopteris sudetica A.Braun & Milde",
  "Cytisus elongatus", "",
  "Cytisus nigricans", "Cytisus nigricans L.",
  "Dahlia variabilis", "Dahlia variabilis Hort.", 
  "Daphne mezereum", "Daphne mezereum L.",
  "Datura stramonium", "Datura stramonium L.", 
  "Delphinium ajacis", "Delphinium ajacis L.",
  "Dentaria bulbifera", "Cardamine bulbifera (L.) Crantz",
  "Dentaria enneaphyllos", "Cardamine enneaphyllos (L.) Crantz",
  "Dianthus barbatus", "Dianthus barbatus L.",
  "Dianthus carthusianorum", "Dianthus carthusianorum L.", 
  "Dianthus superbus", "Dianthus superbus L.",
  "Digitalis purpurea", "Digitalis purpurea L.", 
  "Diplotaxis muralis", "Diplotaxis muralis (L.) DC.",
  "Dipsacus silvester", "Dipsacus fullonum L.", 
  "Drosera rotundifolia", "Drosera rotundifolia L.", 
  "Echinops sphaerocephalus", "Echinops sphaerocephalus L.", 
  "Elatine alsinastrum L.", "Elatine alsinastrum L.", 
  "Elatine hexandra", "Elatine hexandra (Lapierre) DC.",
  "Elatine hydropiper", "Elatine hydropiper L.",
  "Epilobium adnatum", "Epilobium tetragonum L.",
  "Epilobium hirsutum x montanum", "Epilobium hirsutum × montanum ",
  "Epilobium lamyi", "Epilobium lamyi F.W.Schultz", 
  "Epilobium obscurum", "Epilobium obscurum Schreb.", 
  "Epilobium palustre f. glandulosum", "Epilobium palustre L.",
  "Epilobium parviflorum", "Epilobium parviflorum Schreb.", 
  "Epilobium parviflorum x roseum", "Epilobium parviflorum x roseum", 
  "Equisetum Telmateia Ehrh", "Equisetum telmateia Ehrh.", 
  "Equisetum arvense", "Equisetum arvense L.", 
  "Equisetum arvense L. var. boreale (Rup.) f. normalis", "Equisetum arvense L.", 
  "Equisetum arvense L. var. campestre (C.F. Schultz)", "Equisetum arvense L.", 
  "Equisetum arvense L. var. nemorosum A. Br.", "Equisetum arvense L.", 
  "Equisetum arvense f. campestre", "Equisetum arvense L.", 
  "Equisetum arvense f. irriguum", "Equisetum arvense L.", 
  "Equisetum arvense var. serotinum G. F. W. Mey.", "Equisetum arvense L.", 
  "Equisetum arvense x limosum", "", 
  "Equisetum hiemale", "Equisetum hyemale L.", 
  "Equisetum limosum", "Equisetum fluviatile L.", 
  "Equisetum limosum L. (erw.) var. attenuatum Milde", "Equisetum fluviatile L.", 
  "Equisetum limosum L. var. uliginosum (Mhbg.)", "Equisetum fluviatile L.", 
  "Equisetum limosum L. var. verticillatum Döll f. ramosissima Baenitz.", "Equisetum fluviatile L.", 
  "Equisetum limosum a. linnaeanum Döll.", "Equisetum fluviatile L.", 
  "Equisetum limosum v. uliginosum", "Equisetum fluviatile L.", 
  "Equisetum limosum var. uliginosum", "Equisetum fluviatile L.", 
  "Equisetum limosum var. uliginosum Mühlbg.", "Equisetum fluviatile L.", 
  "Equisetum litorale", "Equisetum ×litorale Kühlew. ex Rupr.", 
  "Equisetum litorale Kühl.", "Equisetum ×litorale Kühlew. ex Rupr.", 
  "Equisetum maximum", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum Lmk. var. serotinum A. Br.", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum f. serotinum", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum v. breve Milde", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum v. gracile", "Equisetum telmateia Ehrh.", 
  "Equisetum palustre", "Equisetum palustre L.", 
  "Equisetum palustre L. var. arcuatum Milde", "Equisetum palustre L.", 
  "Equisetum palustre f. arcuatum", "Equisetum palustre L.", 
  "Equisetum palustre f. polystachium", "Equisetum palustre L.", 
  "Equisetum pratense", "Equisetum pratense Ehrh.", 
  "Equisetum ramosissimum", "Equisetum ramosissimum Desf.", 
  "Equisetum silvaticum", "Equisetum sylvaticum L.", 
  "Equisetum telmateja Ehrh.", "Equisetum telmateia Ehrh.", 
  "Equisetum variegatum", "Equisetum variegatum Schleich.", 
  "Erica tetralix", "Erica tetralix L.", 
  "Eriophorum gracile Koch.", "Eriophorum gracile W.D.J.Koch", 
  "Eriophorum vaginatum", "Eriophorum vaginatum L.",
  "Eruca sativa", "Eruca sativa Hill",
  "Eupatorium cannabinum", "Eupatorium cannabinum L.", 
  "Euphorbia dulcis", "Euphorbia dulcis L.", 
  "Euphorbia lathyris", "Euphorbia lathyris L.",
  "Euphorbia platyphylla", "Euphorbia platyphyllos L.",
  "Falcaria vulgaris", "Falcaria vulgaris Bernh.", 
  "Festuca elatior var.pseudololiacea", "Lolium arundinaceum subsp. arundinaceum",
  "Festuca myurus", "Festuca myuros L.",
  "Ficus carica", "Ficus carica L.",
  "Flieracium tauschii Zahn", "", 
  "Fragaria collina x vesca", "",
  "Gagea arvensis", "Gagea arvensis Kar. & Kir. ex Ledeb.", 
  "Gagea minima", "Gagea minima (L.) Ker Gawl.",
  "Gagea pratensis", "Gagea pratensis (Pers.) Dumort.", 
  "Galega officinalis", "Galega officinalis L.",
  "Galinsoga parviflora", "Galinsoga parviflora Cav.", 
  "Galinsoga quadriradiata", "Galinsoga quadriradiata Ruiz & Pav.", 
  "Galium boreale", "Galium boreale L.", 
  "Galium tricorne", "Galium tricorne With., 1796", 
  "Geaster fornicatus Fries.", "Geastrum fornicatum (Huds.) Hook.", 
  "Genista pilosa", "Genista pilosa L.",
  "Gentiana verna", "Gentiana verna L.", 
  "Geranium molle", "Geranium molle L.",
  "Geranium phaeum", "Geranium phaeum L.",
  "Geranium pyrenaicum", "Geranium pyrenaicum Burm.f.",
  "Geranium sibiricum", "Geranium sibiricum L.",
  "Geum rivale", "Geum rivale L.", 
  "Gladiolus imbricatus", "Gladiolus imbricatus L.",
  "Glaucium flavum", "Glaucium flavum Crantz",
  "Glyceria nemoralis", "Glyceria nemoralis (R.Uechtr.) R.Uechtr. & Koern.",
  "Glyceria plicata Fries", "Glyceria notata Chevall.", 
  "Glycine hispida (Mönch) Maxim.", "Glycine max subsp. max", 
  "Gratiola officinalis", "Gratiola officinalis L.", 
  "Guizotia abyssinica", "Guizotia abyssinica (L.fil.) Cass.", 
  "Gymnadenia conopea var. ornithis Beck", "Gymnadenia conopsea (L.) R.Br.",
  "Gypsophila elegans", "Gypsophila elegans M.Bieb.",
  "Helianthus tuberosus", "Helianthus tuberosus L.", 
  "Helichrysum arenarium", "Helichrysum arenarium (L.) Moench", 
  "Heracleum sphondylium", "Heracleum sphondylium L.", 
  "Hieracium cernuiforme N. P.", "Hieracium cernuiforme N.P., 1885", 
  "Hieracium cymosum", "Hieracium cymosum Willd., 1803", 
  "Hieracium tauschii", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium tauschii ssp. acrosciadium N. P.", "Pilosella densiflora (Tausch) Soják",
  "Hieracium tauschii Zahn", "Pilosella densiflora (Tausch) Soják", 
  "Hierochloa odorata", "Anthoxanthum nitens (Weber) Y.Schouten & Veldkamp", 
  "Holosteum umbellatum f. heuffeli", "Holosteum umbellatum L.",
  "Hordeum europaeum", "Hordelymus europaeus (L.) Jess. ex Harz", 
  "Hydrocotyle vulgaris", "Hydrocotyle vulgaris L.", 
  "Hypericum hirsutum", "Hypericum hirsutum L.",
  "Hypochoeris glabra", "Hypochoeris glabra L.", 
  "Hypochoeris maculata", "Trommsdorffia maculata subsp. maculata", 
  "Hyssopus officinalis", "Hyssopus officinalis L.", 
  "Illecebrum verticillatum", "Illecebrum verticillatum L.",
  "Impatiens parviflora", "Impatiens parviflora DC.",
  "Imperatoria ostruthium", "Imperatoria ostruthium L.", 
  "Inula salicina", "Inula salicina Pall.", 
  "Inula vulgaris", "Inula vulgaris Williams", 
  "Iris sibirica", "Iris sibirica L.",
  "Isoetes lacustris", "Isoetes lacustris L.", 
  "Isopyrum thalictroides", "Isopyrum thalictroides L.", 
  "Juncus alpinus Vill.", "Juncus alpinoarticulatus subsp. alpinoarticulatus Chaix", 
  "Juncus filiformis", "Juncus filiformis L.",
  "Juncus filiformis f. pusillus Fries", "Juncus filiformis L.",
  "Juncus supinus", "Juncus supinus Bicheno, 1819", 
  "Juncus tenageja", "Juncus tenageia Ehrh. ex L.fil.", 
  "Juncus tenuis", "Juncus tenuis Willd.",
  "Koeleria hispida (Savi) D. C.", "Rostraria hispida (Savi) Dogan", 
  "Lamium galeobdolon", "Lamium galeobdolon (L.) L.", 
  "Lathyrus niger", "Lathyrus niger (L.) Bernh.",
  "Lathyrus silvester", "Lathyrus sylvestris L.",
  "Lathyrus sylvestris", "Lathyrus sylvestris L.", 
  "Lavatera trimestris", "Malva trimestris (L.) Salisb.",
  "Lens esculenta", "Vicia lens (L.) Coss. & Germ.",
  "Leontodon taraxacum", "Taraxacum officinale Weber ex Wiggins", 
  "Lepidium densiflorum", "Lepidium densiflorum Schrad.",
  "Lepidium draba", "Lepidium draba L.",
  "Lepidium ruderale", "Lepidium ruderale L.",
  "Lepidium virginicum", "Lepidium virginicum L.",
  "Ligustrum vulgare", "Ligustrum vulgare L.", 
  "Lilium martagon", "Lilium martagon L.",
  "Limosella aquatica", "Limosella aquatica L.", 
  "Lindernia pyxidaria", "Lindernia pyxidaria Pursh", 
  "Lobelia erinus", "Lobelia erinus L.", 
  "Lolium perenne f. compositum", "Lolium perenne L.",
  "Lolium remotum", "Lolium remotum Schrank", 
  "Lolium temulentum f. arvense", "Lolium temulentum L.",
  "Lonicera morrowii", "Lonicera morrowii Gray", 
  "Lonicera periclymenum", "Lonicera periclymenum L.", 
  "Lonicera xylosteum", "Lonicera xylosteum L.", 
  "Lotus siliquosus", "Lathyrus inconspicuus var. inconspicuus", 
  "Lunaria annua", "Lunaria annua L.",
  "Lunaria rediviva", "Lunaria rediviva L.",
  "Lupinus angustifolius", "Lupinus angustifolius L.",
  "Lychnis chalcedonica", "Silene chalcedonica (L.) E.H.L.Krause",
  "Lycopodium alpinum", "Diphasiastrum alpinum (L.) Holub", 
  "Lycopodium annotinum", "Lycopodium annotinum L.", 
  "Lycopodium annotinum f. integrifolium", "Lycopodium annotinum L.", 
  "Lycopodium chamaecyparissus", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium clavatum", "Lycopodium clavatum L.", 
  "Lycopodium clavatum L. var. tristachyum Nutt. (als Alt)", "Lycopodium clavatum L.", 
  "Lycopodium complanatum", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum L. ssp. anceps (Wallr.)", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum L. ssp. chamaecyparissus ABr.", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium complanatum L. var. L. Chamaecyparissus A, Braun.", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium complanatum anceps Wallr.", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum f. brachystachys", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium inundatum", "Lycopodiella inundata (L.) Holub", 
  "Lycopodium selago", "Huperzia selago (L.) Bernh. ex Schrank & Mart", 
  "Lysimachia thyrsiflora", "Lysimachia thyrsiflora L.", 
  "Macleya cordata", "Macleaya cordata (Willd.) R.Br.",
  "Malva moschata", "Malva moschata L.",
  "Malva parviflora", "Malva parviflora L.",
  "Malva verticillata", "Malva verticillata L.",
  "Malva verticillata var. crispa", "Malva verticillata L.",
  "Matricaria chamomilla", "Matricaria chamomilla L.", 
  "Medicago falcata x sativa", "",
  "Melampyrum cristatum", "Melampyrum cristatum L.", 
  "Melandryum album x rubrum", "",
  "Melica ciliata", "Melica ciliata L.",
  "Melica uniflora", "Melica uniflora Retz.", 
  "Melilotus altissimus", "Melilotus altissimus Thuill.",
  "Melilotus indicus", "Melilotus indicus (L.) All.",
  "Melittis melissophyllum", "Melittis melissophyllum L.", 
  "Menyanthes trifoliata", "Menyanthes trifoliata L.", 
  "Mercurialis annua", "Mercurialis annua L.",
  "Mirabilis Jalapa L.", "Mirabilis jalapa L.", 
  "Muscari comosum", "Leopoldia comosa (L.) Parl.",
  "Muscari racemosum", "Muscari racemosum Mill.",
  "Myosotis caespitosa", "Myosotis caespitosa DC., 1846", 
  "Myosotis palustris", "Myosotis scorpioides L.", 
  "Myosotis silvatica f. lactea", "Myosotis sylvatica Ehrh. ex Hoffm.", 
  "Myosotis sparsiflora", "Myosotis sparsiflora Pohl",
  "Myriophyllum spicatum", "Myriophyllum spicatum L.", 
  "Myriophyllum verticillatum", "Myriophyllum verticillatum L.", 
  "Myrrhis odorata", "Myrrhis odorata (L.) Scop.", 
  "Neottia nidus avis", "Neottia nidus-avis (L.) Rich.", 
  "Nicandra physaloides", "Physochlaina physaloides (L.) G.Don", 
  "Nicotiana rustica", "Nicotiana rustica L.", 
  "Nonnea rosea (M. B.) Lk.", "Nonea rosea (M.Bieb.) Link", 
  "Nymphaea candida", "Nymphaea candida J.Presl & C.Presl",
  "Oenothera muricata", "Oenothera biennis L.", 
  "Onopordon acanthium", "Onopordum acanthium L.", 
  "Onopordum acanthium", "Onopordum acanthium L.",  
  "Ophioglossum vulgatum", "Ophioglossum vulgatum L.",
  "Ophioglossum vulgatum L.", "Ophioglossum vulgatum L.",
  "Orchis incarnata", "Dactylorhiza incarnata (L.) Soó",
  "Orchis mascula", "Orchis mascula (L.) L.",
  "Ornithogalum nutans", "Ornithogalum nutans L.",
  "Ornithogalum umbellatum", "Ornithogalum umbellatum L.",
  "Orobanche caryophyllea", "Orobanche caryophyllacea Sm.", 
  "Orobanche pallidiflora", "Orobanche reticulata subsp. pallidiflora (Wimm. & Grab.) Hayek", 
  "Osmunda regalis", "Osmunda regalis L.", 
  "Osmunda regalis L.", "Osmunda regalis L.", 
  "Panicum lineare", "Cynodon dactylon (L.) Pers.",
  "Papaver dubium", "Papaver dubium L.",
  "Papaver hybridum L.", "Roemeria hispida Stace", 
  "Pastinaca sativa", "Pastinaca sativa L.", 
  "Pedicularis palustris", "Pedicularis palustris L.", 
  "Petasites officinalis", "Petasites hybridus subsp. hybridus ", 
  "Peucedanum cervaria", "Cervaria rivini Gaertn.", 
  "Peucedanum palustre", "Thysselinum palustre (L.) Hoffm.", 
  "Phacelia tanacetifolia", "Phacelia tanacetifolia Benth.", 
  "Phegopteris dryopteris (L.) Fee", "Gymnocarpium dryopteris (L.) Newman",
  "Phegopteris polypodioides Fée.", "Phegopteris connectilis (Michx.) Watt",
  "Phegopteris robertiana", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phegopteris robertiana (Hoffm.) A. Br.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phegopteris robertianum A. Br.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Physocarpus opulifolius", "Physocarpus opulifolius (L.) Maxim.",
  "Phyteuma orbiculare", "Phyteuma orbiculare L.", 
  "Phytolacca decandra", "Phytolacca americana L.",
  "Pilularia globulifera", "Pilularia globulifera L.",
  "Plantago arenaria", "Plantago arenaria Waldst. & Kit.", 
  "Poa bulbosa", "Poa bulbosa L.", 
  "Poa chaixii var. remota", "Poa remota Forselles", 
  "Poa nemoralis var. montana", "Poa nemoralis L.",
  "Polemonium coeruleum", "Polemonium caeruleum L.", 
  "Polygala amara", "Polygala amara L.", 
  "Polygonatum officinale", "Polygonatum officinale All.",
  "Polygonum cuspidatum", "Reynoutria japonica Houtt.",
  "Polygonum mite", "Persicaria mitis (Schrank) Assenov",
  "Polypodium Robertianum Hoffm.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Polypodium dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Polypodium phegopteris", "Phegopteris connectilis (Michx.) Watt",
  "Polypodium vulgare", "Polypodium vulgare L.", 
  "Polypodium vulgare L.", "Polypodium vulgare L.",
  "Potamogeton densus L.", "Groenlandia densa (L.) Fourr.", 
  "Potamogeton obtusifolius", "Potamogeton obtusifolius Mert. & W.D.J.Koch",
  "Potamogeton pectinatus", "Stuckenia pectinata (L.) Börner",
  "Potamogeton praelongus", "Potamogeton praelongus Wulfen",
  "Potentilla alba", "Potentilla alba L.", 
  "Potentilla arenaria", "Potentilla incana Borkh.", 
  "Potentilla canescens", "Potentilla inclinata Vill.",
  "Potentilla fragariastrum", "Potentilla sterilis (L.) Garcke",
  "Potentilla norvegica", "Potentilla norvegica L.",
  "Potentilla opaca", "Potentilla heptaphylla subsp. heptaphylla ",
  "Potentilla palustris", "Comarum palustre L.",
  "Potentilla recta", "Potentilla recta L.",
  "Potentilla supina", "Potentilla supina L.",
  "Potentilla verna", "Potentilla verna L.",
  "Potentilla wiemanniana", "Potentilla wiemanniana Spreng. ex Günther & Schummel",
  "Primula officinalis", "Primula officinalis Wulfen, 1778", 
  "Pteris aquilina", "Pteridium aquilinum (L.) Kuhn",
  "Pulicaria vulgaris", "Pulicaria vulgaris Gaertn.", 
  "Ranunculus cassubicus", "Ranunculus cassubicus L.",
  "Ranunculus flaccidus", "Ranunculus trichophyllus subsp. trichophyllus Chaix ex Villars", 
  "Ranunculus polyanthemus", "Ranunculus polyanthemos L.", 
  "Ranunculus sceleratus", "Ranunculus sceleratus L.",
  "Reseda lutea", "Reseda lutea L.",
  "Ribes alpinum", "Ribes alpinum L.",
  "Ribes grossularia", "Ribes uva-crispa var. sativum DC.",
  "Ribes nigrum", "Ribes nigrum L.",
  "Roripa amphibia", "Rorippa amphibia (L.) Besser",
  "Roripa austriaca", "Rorippa austriaca (Crantz) Besser", 
  "Roripa austriaca X silvestre", "",
  "Rosa agrestis", "Rosa agrestis Savi", 
  "Rosa coriifolia", "Rosa caesia Sm.",
  "Rosa gallica", "Rosa gallica L.", 
  "Rosa gallica x dumetorum", "", 
  "Rosa glauca", "Rosa glauca Pourr.",
  "Rosa hirtifolia (H. Br.) Schalow", "Rosa corymbifera Borkh.",
  "Rosa pomifera", "",
  "Rosa silesiaca", "Rosa agrestis Savi", 
  "Rosa silesiaca Nimptsch", "Rosa agrestis Savi", 
  "Rosa subcanina", "Rosa subcanina (Christ) Dalla Torre & Sarnth.",
  "Rudbekia laciniata", "Rudbeckia laciniata L.", 
  "Rumex acetosella f. ramosissima", "Rumex acetosella L.",
  "Rumex aquaticus", "Rumex aquaticus L.",
  "Rumex aquaticus x obtusifolius", "",
  "Rumex maritimus", "Rumex maritimus L.",
  "Rumex maximus", "Rumex hydrolapathum (Scop.) Huds.",
  "Salix aurita", "Salix aurita L.", 
  "Salix aurita-cinerea", "", 
  "Salix aurita-livida", "", 
  "Salix aurita-purpurea", "Salix aurita × purpurea", 
  "Salix cinerea-viminalis", "Salix ×holosericea Willd.", 
  "Salix dasyclados", "Salix ×dasyclados Wimm.", 
  "Salix hastata-silesiaca", "", 
  "Salix nigricans-repens", "", 
  "Salix pentandra", "Salix pentandra L.",
  "Salix silesiaca-Lapponum", "", 
  "Salix silesiaca-caprea", "", 
  "Salix viminalis-aurita f. glabrata", "", 
  "Salsola kali", "Kali turgidum (Dumort.) Gutermann",
  "Salvia pratensis", "Salvia pratensis L.", 
  "Salvinia natans", "Salvinia natans (L.) All.",
  "Sambucus ebulus", "Sambucus ebulus L.",
  "Sambucus racemosa", "Sambucus racemosa L.", 
  "Sanguisorba minor", "Poterium sanguisorba subsp. sanguisorba L.",
  "Sanicula europaea", "Sanicula europaea L.", 
  "Saponaria officinalis", "Saponaria officinalis L.",
  "Scabiosa canescens", "Scabiosa canescens Waldst. & Kit.", 
  "Scirpus holoschoenus", "Scirpoides holoschoenus (L.) Soják",
  "Scirpus maritimus", "Bolboschoenus maritimus (L.) Palla", 
  "Scirpus ovatus", "Eleocharis ovata (Roth) Roem. & Schult.",
  "Scirpus pauciflorus", "Eleocharis quinqueflora (Hartmann) O.Schwarz", 
  "Scirpus radicans", "Scirpus radicans Schkuhr",
  "Sedum album", "Sedum album L.",
  "Sedum reflexum", "Petrosedum rupestre subsp. rupestre", 
  "Sedum spurium", "Sedum spurium Sibth. ex Nyman, 1879",
  "Selaginella apoda", "Selaginella apoda (L.) Spring",
  "Selaginella selaginoides", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.",
  "Selaginella spiculosa", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.", 
  "Selaginella spinulosa", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.",            
  "Selaginella spinulosa A. Br.", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.", 
  "Sempervivum soboliferum", "Sempervivum globiferum subsp. globiferum",
  "Seseli coloratum", "Seseli annuum subsp. annuum", 
  "Setaria italica", "Setaria italica (L.) P.Beauv.",
  "Silene coeli rosa (L.) A. Br.", "Eudianthe coeli-rosa (L.) Endl.", 
  "Silene dichotoma", "Silene dichotoma Ehrh.",
  "Silene otites", "Silene otites (L.) Wibel", 
  "Sisymbrium orientale", "Sisymbrium orientale L.",
  "Sisymbrium sinapistrum", "Sisymbrium altissimum L.",
  "Sisyrinchium angustufolium", "Sisyrinchium angustifolium Mill.",
  "Solanum rostratum", "Solanum angustifolium Houst. ex Mill.",
  "Solanum villosum", "Solanum villosum Mill.",
  "Solidago canadensis", "Solidago canadensis L.",
  "Solidago serotina", "Solidago serotina Retz., 1781",
  "Sparganium diversifolium", "Sparganium diversifolium Asch.",
  "Sparganium minimum", "Sparganium minimum Hill, 1756",
  "Sparganium natans", "Sparganium natans L.",
  "Sparganium ramosum", "Sparganium erectum L.",
  "Stachys annua", "Stachys annua (L.) L.",
  "Stachys recta", "Stachys recta L.", 
  "Stachys rectus", "Stachys recta L.", 
  "Stellaria friesiana", "Stellaria longifolia (Regel) Muhl. ex Willd.",
  "Stellaria media f. neglecta", "Stellaria neglecta (Lej.) Weihe", 
  "Stratiotes aloides", "Stratiotes aloides L.", 
  "Struthiopteris germanica", "Matteuccia struthiopteris subsp. struthiopteris",
  "Sturmia Loeselii", "Liparis loeselii (L.) Rich.",
  "Suaeda maritima Dum.", "Suaeda maritima (L.) Dumort.",
  "Succisa pratensis f. incisa", "Succisa pratensis Moench",
  "Sweertia perennis var. flore sulphureo", "Swertia perennis L.", 
  "Symphytum asperum X officinale", "Symphytum ×uplandicum Nyman", 
  "Symphytum officinale f. bohemicum", "Symphytum bohemicum F.W.Schmidt",
  "Symphytum tuberosum", "Symphytum tuberosum L.", 
  "Taxus baccata", "Cephalotaxus harringtonii var. harringtonii",
  "Teesdalea nudicaulis", "Teesdalia nudicaulis (L.) W.T.Aiton",
  "Teucrium scordium", "Teucrium scordium L.",
  "Thalictrum aquilegifolium", "Thalictrum aquilegiifolium L.",
  "Thalictrum flavum", "Thalictrum flavum L.", 
  "Thalictrum simplex", "Thalictrum simplex L.", 
  "Thesium alpinum", "Thesium alpinum L.",
  "Thesium ebracteatum", "Thesium ebracteatum Hayne",
  "Thesium intermedium", "Thesium linophyllon L.", 
  "Thesium pratense", "Thesium pyrenaicum Pourr.",
  "Thladiantha dubia", "Thladiantha dubia Bunge",
  "Thlaspi alpestre", "Thlaspi alpestre Luce",
  "Thlaspi arvense", "Thlaspi arvense L.",
  "Thymus alpestris Tausch", "Thymus alpestris (Celak.) Tausch ex A.Kern.",
  "Thymus parviflorus Opiz", "Thymus pulegioides subsp. montanus (Trevir.) Ronniger", 
  "Thymus pulegioides L. var. Chamaedrys (Fries) Ronn.", "Thymus pulegioides L.", 
  "Thymus pulegioides L. var. gracilicaulis Ronn.", "Thymus pulegioides L.",
  "Thymus pulegioides L. var. ovatus (Mill.) Ronn.", "Thymus pulegioides L.",
  "Thymus pulegioides X serpyllum", "",
  "Thymus serpyllum L. em. Fries var. rigidus (Wimmer et Gr.) Ronn.", "Thymus serpyllum var. rigidus Wimmer & Grab.",
  "Thymus sudeticus Opiz", "Thymus pulcherrimus Schur",
  "Trientalis europaea", "Lysimachia europaea (L.) U.Manns & Anderb.",
  "Trientalis europaeus", "Lysimachia europaea (L.) U.Manns & Anderb.",
  "Trifolium alpestre", "Trifolium alpestre L.",
  "Trifolium echinatum Bieb. ssp. constantinopolitanum (Ser.) Gibelli et Belli", "", 
  "Trifolium glomeratum L. var. minus Rouy", "", 
  "Trifolium hybridum", "Trifolium hybridum L.",
  "Trifolium lappaceum L.", "Trifolium lappaceum L.", 
  "Triglochin palustris", "Triglochin palustris L.", 
  "Triticum durum", "Triticum turgidum L.",
  "Trollius europaeus", "Trollius europaeus L.",
  "Tulipa silvestris", "Tulipa sylvestris L.",
  "Turritis glabra", "Turritis glabra L.",
  "Typha latifolia", "Typha latifolia L.",
  "Ulmaria filipendula", "Filipendula vulgaris Moench",
  "Ulmus montana", "Ulmus glabra Huds.",
  "Utricularia intermedia", "Utricularia intermedia Hayne",
  "Utricularia minor", "Utricularia minor L.",
  "Vaccaria parviflora", "Gypsophila vaccaria (L.) Sm.",
  "Vaccinium oxycoccus", "Vaccinium oxycoccos L.",
  "Vaccinium uliginosum", " Vaccinium uliginosum L.",
  "Valeriana dioeca", "Valeriana dioica L.",
  "Valeriana exaltata", "Valeriana officinalis L.",
  "Valeriana polygama", "Valeriana elongata Jacq.",
  "Valeriana sambucifolia", "Valeriana sambucifolia J.C.Mikan ex Pohl",
  "Veratrum album", "Veratrum album L.",
  "Verbascum blattaria", "Verbascum blattaria L.", 
  "Verbascum phlomoides", "Verbascum phlomoides L.",
  "Verbascum thapsiforme x thapsus", "",
  "Veronica anagallis", "Veronica anagallis L.",
  "Veronica longifolia", "Veronica longifolia L.",
  "Veronica teucrium", "Veronica teucrium L.",
  "Vicia cracca var. alpestris Čel.", "",
  "Vicia dumetorum", "Vicia dumetorum L.",
  "Vicia Ervilia (L.) Willd.", "Vicia ervilia (L.) Willd.", 
  "Vicia grandiflora", "Vicia grandiflora Scop.",
  "Vicia lathyroides", "Vicia lathyroides L.",
  "Vicia lutea L. f. caerulea Arcang.", "", 
  "Vicia pannonica", "Vicia pannonica Crantz",
  "Vicia pannonica f. purpurascens", "Vicia pannonica Crantz",
  "Vicia silvatica", "Vicia sylvatica L.",
  "Vicia tenuifolia", "Vicia tenuifolia Roth",
  "Vinca minor", "Vinca minor L.", 
  "Vincetoxicum officinale", "Vincetoxicum hirundinaria Medik.",
  "Viola elatior Fries", "Viola elatior Fr.", 
  "Viola elatior f . humilis Uechtritz", "",
  "Viola elatior x pumila", "",
  "Viola epipsila", "Viola epipsila Ledeb.", 
  "Viola hirta", "Viola hirta L.", 
  "Viola montana x riviniana", "", 
  "Viola mirabilis", "Viola mirabilis L.", 
  "Viola palustris", "Viola palustris L.", 
  "Viola persicifolia", "Viola persicifolia Schreb.",
  "Viola persicifolia x  canina", "",
  "Viola rupestris var. glaberrima", "Viola rupestris subsp. glaberrima (Murb.) Vl.V.Nikitin",
  "Viscum album", "Viscum album L.",
  "Viscum album var. laxum", "Viscum laxum Boiss. & Reut.",
  "Xanthium spinosum", "Xanthium spinosum L.",
  "Xanthium strumarium", "Xanthium strumarium L.",
  "Zannichellia palustris", "Zannichellia palustris L.",
  "Zea mays", "Zea mays L."
)

an <- matrix(unlist(an), nrow=length(an)/2, byrow=TRUE) |>
  as.data.frame()
names(an) <- c("species", "accepted_name")

# an <- an |>  
#   unique() |>
#   dplyr::arrange(species)
#   
# message(
#   paste0("\"", an[, 1], "\", \"", an[,2], "\", \n")
# )

m <- jahres |>
  subset(select = "species") |>
  dplyr::left_join(an, by = "species") |>
  unique() |>
#  subset(is.na(accepted_name) | accepted_name == "") |>
  subset(is.na(accepted_name)) |>
  dplyr::arrange(species) 
# |>
#  as.matrix()

print(m)

