an <- c(
  "Abutilon avicennae", "Abutilon theophrasti Medik.",
  "Abutilon Avicennae", "Abutilon theophrasti Medik.",
  "Acer campestre", "Acer campestre L.", 
  "Acer negundo", "Acer negundo L.",
  "Acer platanoides", "Acer platanoides L.",
  "Acer pseudoplatanus", "Acer pseudoplatanus L.",
  "Acer tataricum", "Acer tataricum L.",
  "Achillea miilefolium v. contrada", "Achillea millefolium subsp. millefolium",
  "Achillea Ptarmica", "Achillea ptarmica L.",
  "Aconitum Lycoctonum", "Aconitum lycoctonum L.",
  "Acorus Calamus", "Acorus calamus L.",
  "Acorus calamus", "Acorus calamus L.",
  "Adonis aestivalis", "Adonis aestivalis L.",
  "Agrimonia eupatoria", "Agrimonia eupatoria L.",
  "Agrimonia odorata", "Agrimonia repens L.",
  "Agropyrum repens v. aristatum", "Elymus repens subsp. repens",
  "Agrostemma githago f. latisecta f. nov.", "Agrostemma githago L.",
  "Agrostis verticillata All.", "Polypogon viridis (Gouan) Breistr.",
  "Ailanthus glandulosa Desf.", "Ailanthus altissima (Mill.) Swingle", 
  "Aira caryophyllea", "Aira caryophyllea L.", 
  "Aira praecox", "Aira praecox L.",
  "Ajuga Chamaepitys", "Ajuga chamaepitys (L.) Schreb.",
  "Ajuga genevensis X reptans", "Ajuga genevensis x reptans",
  "Alectorolophus angustifolius (Gmel.) Heyn.", "Rhinanthus glacialis subsp. glacialis",
  "Alectorolophus hirsutus", "Rhinanthus alectorolophus subsp. alectorolophus (Scop.) Pollich, 1777",
  "Alisma arcuatum", "Alisma gramineum Lej.",
  "Alkanna primuliflora", "Alkanna primuliflora Griseb.",
  "Allium angulosum", "Allium angulosum L.",
  "Allium cepa", "Allium cepa L.",
  "Allium Schoenoprasum", "Allium schoenoprasum L.",
  "Allium scorodoprasum", "Allium scorodoprasum L.",
  "Allium Scorodoprasum", "Allium scorodoprasum L.",
  "Allium senescens", "Allium senescens L.",
  "Allium sibiricum", "Allium schoenoprasum L.",
  "Allium ursinum", "Allium ursinum L.",
  "Allium victorialis", "Allium victorialis L.",
  "Allium Victorialis", "Allium victorialis L.",
  "Alnus incana", "Alnus incana (L.) Moench",
  "Alnus rugosa", "Alnus incana subsp. rugosa (Du Roi) R.T.Clausen",
  "Alopecurus agrestis", "Alopecurus myosuroides Huds.",
  "Althaea officinalis", "Althaea officinalis L.",
  "Althaea rosea", "Alcea rosea L.",
  "Alyssum argenteum", "Odontarrhena argentea (All.) Ledeb.",
  "Amarantus albus", "Amaranthus albus L.",
  "Amarantus angustifolius Lam.", "Amaranthus graecizans L.",
  "Amarantus angustifolius var. graecizans (L.) Thell.", "Amaranthus graecizans L.",
  "Amarantus blitoides S. Wats.", "Amaranthus blitoides S.Watson",
  "Amarantus californicus (Moq.) Wats.", "Amaranthus californicus (Moq.) S.Watson",
  "Amarantus cruentus var.paniculatus","Amaranthus cruentus L.",
  "Amarantus deflexus", "Amaranthus deflexus L.",
  "Amarantus deflexus L.", "Amaranthus deflexus L.",
  "Amarantus hybridus L. ssp. cruentus Thell. var. paniculatus Thell.", "Amaranthus cruentus L.",
  "Amarantus hybridus L. ssp. hypochondriacus (L.) Thell. var. chlorostachys Thell.", "Amaranthus cruentus L.",
  "Amarantus hybridus ssp. cruentus Thell. var. paniculatus Thell.", "Amaranthus cruentus L.",
  "Amarantus hybridus ssp. cruentus var.panniculatus", "Amaranthus cruentus L.",
  "Amarantus hybridus ssp. hypochondriacus var. chlorostachys", "Amaranthus cruentus L.",
  "Amarantus hypochondriacus var. chlorostachys", "Amaranthus hypochondriacus L.",
  "Amarantus panniculatus", "Amaranthus cruentus L.",
  "Amarantus vulgatissimus Spegazzini", "Amaranthus vulgatissimus Speg.",
  "Ambrosia psilostachya DC.", "Ambrosia psilostachya DC.",
  "Ambrosia trifida L.", "Ambrosia trifida L.",
  "Ambrosia trifida var. integrifolia (Mühlenb.) Torrey et Gray", "Ambrosia trifida L.",
  "Amelanchier canadensis", "Amelanchier canadensis (L.) Medik.",
  "Ammobium alatum R. Br.", "Ammobium alatum R.Br.",
  "Anacyclus clavatus", "Anacyclus clavatus (Desf.) Pers.",
  "Ampelopsis quinquefolia", "Parthenocissus quinquefolia (L.) Planch.",
  "Amsinchia Mensiesii (Lehm.) Nels. et Machr.", "Amsinckia menziesii (Lehm.) A.Nelson & J.F.Macbr.",
  "Anacyclus clavatus (Desf.) Pers.", "Anacyclus clavatus (Desf.) Pers.",
  "Anacydus valentinus ssp. dissimilis", "Anacyclus ×valentinus L.",
  "Anagallis arvensis f. alba Ludi", "Lysimachia arvensis subsp. arvensis",
  "Anagallis coerulea", "Lysimachia foemina (Mill.) U.Manns & Anderb.",
  "Anchusa azurea Mill.", "Anchusa azurea Mill.",
  "Andromeda polifolia", "Andromeda polifolia L.",
  "Andropogon Halepensis", "Sorghum halepense (L.) Pers.",
  "Andropogon Halepensis (L.) Brot.", "Sorghum halepense (L.) Pers.",
  "Andropogon halepensis f . muticus Hackel", "Sorghum halepense (L.) Pers.",
  "Androsace septentrionalis", "Androsace septentrionalis L.",  
  "Andryale sinuata L.", "Andryala integrifolia L.",
  "Anemone alpina", "Pulsatilla alpina subsp. alpina (L.) Delarbre",
  "Anemone Hepatica", "Hepatica nobilis Schreb.",
  "Anemone nemorosa", "Anemone nemorosa L.",
  "Anemone nemorosa L.", "Anemone nemorosa L.",
  "Anemone nemorosa X ranunculoides", "Anemone nemorosa × ranunculoides",
  "Anemone patens", "Pulsatilla patens subsp. patens (L.) Mill.",
  "Anemone pratensis", "Pulsatilla pratensis subsp. pratensis ", 
  "Anemone ranunculoides f. subintegra", "Anemone ranunculoides L.",
  "Anemone silvestris", "Anemone sylvestris L.",
  "Aneura pinguis", "Aneura pinguis (L.) Dumort.",
  "Anoda triangularis D. C.", "Anoda cristata (L.) Schltdl.",
  "Antennaria margaritacea", "Antennaria margaritacea R.Br., 1817",
  "Anthemis altissima", "Cota altissima (L.) Gay",
  "Anthemis altissima L.", "Cota altissima (L.) Gay",
  "Anthemis ruthenica", "Anthemis ruthenica M.Bieb.",
  "Anthemis tinctoria", "Cota tinctoria subsp. tinctoria", 
  "Anthericum ramosum", "Anthericum ramosum L.",
  "Anthirrhinum majus", "Antirrhinum majus L.",
  "Anthoceros", "",
  "Anthoxanthum aristatum", "Anthoxanthum aristatum Boiss.",
  "Anthoxanthum odoratum f. picta nov. f.", "Anthoxanthum odoratum L.",
  "Anthriscus nitida", "Anthriscus nitida (Wahlenb.) Hazsl.",
  "Anthriscus nitidus", "Anthriscus nitida (Wahlenb.) Hazsl.",
  "Anthriscus vulgaris", "Anthriscus caucalis M.Bieb.",
  "Anthyllis Vulneraria", "Anthyllis vulneraria L.",
  "Antirrhinum majus", "Antirrhinum majus L.",
  "Antirrhinum Orontium", "Misopates orontium subsp. orontium (Linnaeus) Rafinesque",
  "Antirrhinum orontium", "Misopates orontium subsp. orontium (Linnaeus) Rafinesque",
  "Apium graveolens", "Apium graveolens L.",
  "Aquilegia vulgaris", "Aquilegia vulgaris L.",
  "Arabis arenosa", "Arabidopsis arenosa (L.) Lawalrée",
  "Arabis Gerardi", "Arabis planisiliqua (Pers.) Rchb.",
  "Arabis Halleri", "Arabidopsis halleri (L.) O'Kane & Al-Shehbaz",
  "Arabis hirsuta", "Arabis hirsuta (L.) Scop.",
  "Arachis hypogaea L.", "Arachis hypogaea L.",
  "Archangelica officinalis", "Angelica archangelica subsp. archangelica", 
  "Arctium majus X tomentosum", "Arctium majus X tomentosum",
  "Arctium nemorosum", "Arctium nemorosum Lej.",
  "Arctostaphylus Uva ursi", "Arctostaphylos uva-ursi (L.) Spreng.",
  "Arctostaphylus uva ursi", "Arctostaphylos uva-ursi (L.) Spreng.",
  "Arenaria serpyllifolia var. leptoclados", "Arenaria leptoclados subsp. leptoclados",
  "Arenaria serpyllifolia var. viscida", "Arenaria serpyllifolia var. glutinosa W.D.J.Koch",
  "Aristolochia Clematitis", "Aristolochia clematitis L.",
  "Aristolochia clematitis", "Aristolochia clematitis L.",
  "Armeria vulgaris", "Armeria maritima subsp. elongata (Hoffm.) Bonnier",
  "Arnica montana", "Arnica montana L.",
  "Arnoseris minima", "Arnoseris minima (L.) Schweigg. & Körte",
  "Arrhenatherum elatius", "Arrhenatherum elatius (L.) P.Beauv. ex J.Presl & C.Presl",
  "Arrhenatherum elatius f. biaristatum", "Arrhenatherum elatius (L.) P.Beauv. ex J.Presl & C.Presl",
  "Arrhenatherum elatius f. brachyclada Reinecke", "Arrhenatherum elatius subsp. elatius",
  "Artemisia Abrotanum", "Artemisia abrotanum L.",
  "Artemisia Absinthium", "Artemisia absinthium L.",
  "Artemisia absinthium", "Artemisia absinthium L.",
  "Artemisia annua", "Artemisia annua L.",
  "Artemisia austriaca Jacq.", "Artemisia austriaca Jacq.",
  "Artemisia campestris", "Artemisia campestris L.", 
  "Artemisia dracunculus", "Artemisia dracunculus L.",
  "Artemisia pontica", "Artemisia pontica L.",
  "Artemisia scoparia", "Artemisia scoparia Waldst. & Kit.",
  "Arum maculatum", "Arum maculatum L.",
  "Aruncus silvester", "Aruncus sylvester Kostel.",
  "Asparagus acutifolius", "Asparagus acutifolius L.",
  "Asparagus tenuifolius Lam.", "Asparagus tenuifolius Lam.",
  "Asperugo procumbens", "Asperugo procumbens L.",
  "Asperula aparine", "Galium aparine L.", 
  "Asperula Aparine", "Galium aparine L.", 
  "Asperula arvensis", "Asperula arvensis L.",
  "Asperula cynanchica", "Cynanchica pyrenaica subsp. cynanchica (L.) P.Caputo & Del Guacchio",
  "Asperula odorata", "Galium odoratum (L.) Scop.", 
  "Asperula orientalis", "Asperula orientalis Boiss. & Hohen.",
  "Aspidium Brauni", "Polystichum braunii (Spenn.) Fée",
  "Aspidium Brauni X lobatum", "Aspidium Brauni X lobatum",
  "Aspidium Braunii x Lonchitis", "Aspidium Braunii x Lonchitis",
  "Aspidium Filix mas v. affine Fisch. Mey.", "Dryopteris affinis (Lowe) Fraser-Jenk.",
  "Aspidium cristatum", "Dryopteris cristata (L.) A.Gray",
  "Aspidium cristatum (L.) Sw.", "Dryopteris cristata (L.) A.Gray",
  "Aspidium cristatum X spinulosum", "Aspidium cristatum x spinulosum",
  "Aspidium dilatatum", "Dryopteris dilatata (Hoffm.) A.Gray",
  "Aspidium dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Aspidium Dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Aspidium filix mas var. deorsolobatum", "",
  "Aspidium lobatum", "Polystichum aculeatum (L.) Roth",
  "Aspidium lonchitis (L.) Sw.", "Polystichum lonchitis (L.) Roth", 
  "Aspidium montanum", "Cystopteris montana (Lam.) Bernh.",
  "Aspidium montanum (Vogler) Aschs.", "Oreopteris limbosperma (All.) Holub", 
  "Aspidium phegopteris", "Phegopteris connectilis (Michx.) Watt", 
  "Aspidium Phegopteris", "Phegopteris connectilis (Michx.) Watt", 
  "Aspidium robertianum", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Aspidium Robertianum", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Aspidium spinulosum", "Dryopteris carthusiana (Vill.) H.P.Fuchs", 
  "Aspidium tanacetifolium", "Dryopteris dilatata subsp. dilatata", 
  "Aspidium thelypteris", "Thelypteris palustris subsp. palustris", 
  "Aspidium Thelypteris", "Thelypteris palustris subsp. palustris", 
  "Aspidium thelypteris (L.) Sw.", "Thelypteris palustris subsp. palustris", 
  "Asplenium Adiantum nigrum v. obtusum", "Asplenium adiantum-nigrum subsp. adiantum-nigrum",
  "Asplenium fllix femina", "Athyrium filix-femina (L.) Roth", 
  "Asplenium germanicum Weis.", "Asplenium ruta-muraria subsp. ruta-muraria", 
  "Asplenium ruta-muraria", "Asplenium ruta-muraria L.", 
  "Asplenium Ruta muraria", "Asplenium ruta-muraria L.", 
  "Asplenium septentrionale", "Asplenium septentrionale (L.) Hoffm.", 
  "Asplenium Trichomanes", "Asplenium trichomanes L.", 
  "Asplenium trichomanes L.", "Asplenium trichomanes L.", 
  "Asplenium Trichomanes L.", "Asplenium trichomanes L.", 
  "Asplenium viride", "Asplenium viride Huds.", 
  "Asplenium viride Huds.", "Asplenium viride Huds.", 
  "Asplenium viride ssp. adulterinum", "Asplenium adulterinum Milde", 
  "Aster novi-belgii", "Symphyotrichum novi-belgii (L.) G.L.Nesom", 
  "Aster salignus", "Aster salignus L.", 
  "Astragalus arenarius", "Astragalus arenarius L.", 
  "Astragalus cicer", "Astragalus cicer L.",
  "Astrantia major", "Astrantia major L.",
  "Atrichum tenellum", "Atrichum tenellum Bruch & W.P.Schimper, 1844", 
  "Atriplex hortense", "Atriplex hortensis L.",
  "Atriplex hortense f. ruberrimum", "Atriplex hortensis L.",
  "Atriplex nitens", "Atriplex sagittata Borkh.",
  "Avena sativa f . aristata Krause", "Avena sativa L.",
  "Barbaraea stricta", "Barbarea stricta Andrz. ex Besser",
  "Berberis vulgaris", "Berberis vulgaris L.",
  "Berteroa incana", "Berteroa incana (L.) DC.",
  "Berula", "Berula erecta (Huds.)",
  "Beta maritima L.", "Beta maritima L.", 
  "Betula pubescens x verrucosa", "", 
  "Bidens connatus", "Bidens connata Muhl. ex Willd.", 
  "Bidens melanocarpus", "Bidens frondosa L.", 
  "Blechnum spicant", "Struthiopteris spicant (L.) Weiss", 
  "Blechnum spicant (L.) Wth.", "Struthiopteris spicant (L.) Weiss", 
  "Borrago officinalis", "Borago officinalis L.", 
  "Botrychium lunaria", "Botrychium lunaria (L.) Sw.", 
  "Botrychium lunaria f. cristatum", "Botrychium lunaria (L.) Sw.",
  "Botrychium lunaria f. incisum", "Botrychium lunaria (L.) Sw.",
  "Botrychium lunaria var. subincisum Rüp.", "Botrychium lunaria (L.) Sw.",
  "Botrychium matricariae", "Sceptridium multifidum (S.G.Gmel.) Nishida ex Tagawa", 
  "Botrychium matricariaefolium", "Botrychium matricariifolium (Döll) A.Braun ex Koch", 
  "Botrychium matricarifolium", "Botrychium matricariifolium (Döll) A.Braun ex Koch", 
  "Botrychium rutaefolium A. Br.", "Sceptridium multifidum (S.G.Gmel.) Nishida ex Tagawa", 
  "Botrychium simplex Hitchcock", "Botrychium simplex E.Hitchc.", 
  "Botrychium ternatum Sw.", "Sceptridium ternatum (Thunb.) Lyon", 
  "Brassica juncea", "Brassica juncea (L.) Czern.",
  "Bromus asper", "Bromus ramosus Huds.", 
  "Bromus erectus", "Bromus erectus Huds.",
  "Bromus inermis", "Bromus inermis Leyss.",
  "Bromus racemosus", "Bromus racemosus L.",
  "Bromus sterilis", "Bromus sterilis L.",
  "Buphthalmum speciosum", "Telekia speciosa (Schreb.) Baumg.", 
  "Bupleurum tenuissimum", "Bupleurum tenuissimum L.", 
  "Butomus umbellatus", "Butomus umbellatus L.", 
  "Calendula officinalis", "Calendula officinalis L.", 
  "Calla palustris", "Calla palustris L.",
  "Calystegia silvatica (Kit.) Griseb.", "Calystegia silvatica (Kit.) Griseb.",
  "Camelina sativa", "Camelina sativa (L.) Crantz", 
  "Campanula patula", "Campanula patula L.", 
  "Campanula Rapunculus", "Campanula rapunculus L.", 
  "Campanula rotundifolia", "Campanula rotundifolia L.", 
  "Campanula trachelium var. calycibus complanatis", "Campanula trachelium L.", 
  "Cardamine amara", "Cardamine amara L.", 
  "Cardamine chelidonia L.", "Cardamine chelidonia L.", 
  "Carduus crispus", "Carduus crispus L.", 
  "Carex acuta x stricta", "", 
  "Carex brizoides", "Carex brizoides L.", 
  "Carex buekii", "Carex buekii Wimm.", 
  "Carex buxbaumi", "Carex buxbaumii Wahlenb.",
  "Carex buxbaumii", "Carex buxbaumii Wahlenb.", 
  "Carex caespitosa L. nach Fries.", "Carex cespitosa L.", 
  "Carex cyperoides", "Carex bohemica Schreb.",
  "Carex davalliana", "Carex davalliana Sm.", 
  "Carex davalliana Smith", "Carex davalliana Sm.", 
  "Carex disticha", "Carex disticha Huds.",
  "Carex evoluta Hartmann", "Carex ×evoluta Hartm.", 
  "Carex goodenoughi f. tornata", "Carex nigra subsp. nigra",
  "Carex goodenoughii x stricta", "",
  "Carex ligerica", "Carex colchica J.Gay",
  "Carex longifolia Host.", "Carex umbrosa subsp. umbrosa", 
  "Carex paradoxa", "Carex appropinquata Schumach.", 
  "Carex paradoxa var. gracilis Aschers, et Gr.", "Carex appropinquata Schumach.", 
  "Carex pendula", "Carex pendula Huds.",
  "Carex pilosa", "Carex pilosa Scop.", 
  "Carex pseudocyperus", "Carex pseudocyperus L.", 
  "Carex pulicaris", "Carex pulicaris L.", 
  "Carex pseudocyperus f. minor", "Carex pseudocyperus L.",
  "Carex rigida Gooden.", "Carex dacica Heuff.",
  "Carex riparia", "Carex riparia Curtis", 
  "Carex rudis", "Carex acuta L.",
  "Carex stricta Gooden.", "Carex elata subsp. elata",
  "Carex strigosa Hudson", "Carex strigosa Huds.",
  "Carex teretiuscula", "Carex teretiuscula Willd. ex Kunth, 1837",
  "Carex tomentosa", "Carex tomentosa L.",
  "Carex tricostata Fries.", "Carex acuta L.",
  "Carex turfosa", "Carex ×turfosa Fr.",
  "Carex turfosa Fries.", "Carex ×turfosa Fr.",
  "Carex vesicaria", "Carex vesicaria L.",
  "Carex vulgaris", "Carex nigra (L.) Reichard",
  "Carex vulgaris Fries.", "Carex nigra (L.) Reichard",
  "Carlina acaulis", "Carlina acaulis L.", 
  "Carlina acaulis f. caulescens", "Carlina acaulis subsp. caulescens (Lam.) Schübl. & G.Martens", 
  "Castanea sativa", "Castanea sativa Mill.",
  "Caucalis daucoides", "Orlaya daucoides (L.) Greuter",
  "Centaurea Cyanus", "Centaurea cyanus L.",
  "Centaurea diluta", "Centaurea diluta Aiton",
  "Centaurea diluta Ait.", "Centaurea diluta Aiton",
  "Centaurea jacea ssp. angustifolia (Schrank) Gugler", "Centaurea jacea subsp. angustifolia (DC.) 1874",
  "Centaurea phrygia", "Centaurea phrygia L.", 
  "Centaurea Scabiosa", "Centaurea scabiosa L.",
  "Centaurea solstitialis", "Centaurea solstitialis L.",
  "Cephalanthera grandiflora", "Cephalanthera longifolia (L.) Fritsch",
  "Cephalanthera rubra", "Cephalanthera rubra (L.) Rich.",
  "Cephalanthera xiphophyllum", "Cephalanthera longifolia (L.) Fritsch",
  "Ceratophyllum demersum", "Ceratophyllum demersum L.",
  "Cerastium anomalum", "", 
  "Cerastium triviale", "Cerastium glomeratum Thuill.",
  "Ceratonia siliqua L.", "Ceratonia siliqua L.",
  "Ceratophyllum submersum", "Ceratophyllum submersum L.",
  "Cerinthe major", "Cerinthe major L.",
  "Cerinthe minor", "Cerinthe minor L.", 
  "Chaerophyllum aromaticum", "Chaerophyllum aromaticum L.",
  "Chara syncarpa", "Nitella syncarpa (Thuill.) Chevall.",
  "Chenopodium album", "Chenopodium album L.",
  "Chenopodium album X suecicum", "Chenopodium album X suecicum",
  "Chenopodium Berlandieri Moq. ssp. Zschackei Murr.", "Chenopodium berlandieri Moq.",
  "Chenopodium Botrys", "Dysphania botrys (L.) Mosyakin & Clemants",
  "Chenopodium Botrys L.", "Dysphania botrys (L.) Mosyakin & Clemants",
  "Chenopodium ficifolium", "Chenopodium ficifolium Sm.",
  "Chenopodium foliosum", "Blitum virgatum subsp. virgatum",
  "Chenopodium hircinum", "Chenopodium hircinum Schrad.",
  "Chenopodium hircinum Schräder", "Chenopodium hircinum Schrad.",
  "Chenopodium hybridum f. diversifolium Ludwig", "Chenopodiastrum hybridum (L.) S.Fuentes, Uotila & Borsch",
  "Chenopodium leptophyllum", "Chenopodium leptophyllum (Moq.) Nutt. ex S.Watson",
  "Chenopodium opulifolium", "Chenopodium opulifolium Schrad.",
  "Chenopodium pseudopulifolium J. B. Scholz", "Chenopodium suecicum Murr",
  "Chenopodium rubrum", "Oxybasis rubra (L.) S.Fuentes, Uotila & Borsch",
  "Chenopodium striatum (Kras.) Murr.", "Chenopodium betaceum Andrz.",
  "Chenopodium suecicum", "Chenopodium suecicum Murr",
  "Chenopodium urbicum", "Oxybasis urbica (L.) S.Fuentes, Uotila & Borsch",
  "Chenopodium vulvaria", "Chenopodium vulvaria L.",
  "Chenopodium vulvaria f. microphyllum", "Chenopodium vulvaria L.",
  "Chimophila umbellata", "Chimaphila umbellata (L.) W.P.C.Barton",
  "Chloris virgata Sw.", "Chloris virgata Sw.",
  "Chondrilla juncea", "Chondrilla juncea L.",
  "Chondrilla juncea f. latifolia", "Chondrilla juncea L.",
  "Chorispora tenella (Pall.) DC.", "Chorispora tenella (Pall.) DC.",
  "Chrysanthemum coronarium", "Glebionis coronaria (L.) Tzvelev",
  "Chrysanthemum corymbosum", "Tanacetum corymbosum subsp. corymbosum",
  "Chrysanthemum leucanthemum", "Leucanthemum vulgare subsp. vulgare",
  "Chrysanthemum maximum Ram.", "Leucanthemum maximum (Ramond) DC.",
  "Chrysanthemum Parthenium f. brachyglossum Wallr.", "Tanacetum parthenium (L.) Sch.Bip.",
  "Chrysanthemum segetum", "Glebionis segetum (L.) Fourr.",
  "Chrysosplenium oppositifolium", "Chrysosplenium oppositifolium L.",
  "Cichorium intybus", "Cichorium intybus L.", 
  "Cicuta", "Cicuta sp.",
  "Cicuta virosa", "Cicuta virosa L.", 
  "Cicuta virosa f. angustifolia", "Cicuta virosa L.",
  "Cineraria crispa", "Tephroseris crispa (Jacq.) Rchb.",
  "Circaea alpina", "Circaea alpina L.",
  "Circaea intermedia", "Circaea ×intermedia Ehrh.", 
  "Cirsium acaule", "Cirsium acaule (L.) All., 1780", 
  "Cirsium acaule-oleraceum", "Cirsium acaule × oleraceum", 
  "Cirsium arvense", "Cirsium arvense (L.) Scop.", 
  "Cirsium arvense f. setosum", "Cirsium arvense (L.) Scop.",
  "Cirsium canum", "Cirsium canum (L.) All.", 
  "Cirsium canum-acaule", "", 
  "Cirsium heterophyllum", "Cirsium heterophyllum (L.) Hill", 
  "Cirsium lanceolatum-oleraceum", "", 
  "Cirsium oleraceum-arvense", "",
  "Cirsium oleraceum-palustre", "",
  "Cirsium oleraceum-rivulare", "",
  "Cirsium palustre-rivulare", "",
  "Cirsium rivulare", "Cirsium rivulare (Jacq.) All.", 
  "Cirsium rivulare—palustre", "",
  "Cladium Mariscus", "Cladium mariscus (L.) Pohl",
  "Clarkea elegans Dougl.", "Clarkia unguiculata Lindl.",
  "Clarkea pulchella", "Clarkia pulchella Pursh",
  "Clematis recta", "Clematis recta L.",
  "Clematis vitalba", "Clematis vitalba L.",
  "Clematis Vitalba", "Clematis vitalba L.",
  "Cnicus benedictus", "Centaurea benedicta (L.) L.",
  "Cnidium venosum", "Kadenia dubia (Schkuhr) Lavrova & V.N.Tikhom.",
  "Cochlearia officinalis L.", "Cochlearia officinalis L.",
  "Coeloglossum viride", "Dactylorhiza viridis (L.) R.M.Bateman, Pridgeon & M.W.Chase",
  "Colchicum autumnale", "Colchicum autumnale L.", 
  "Collomia coccinea Lehm.", "Collomia biflora (Ruiz & Pav.) Brand",
  "Collomia grandiflora", "Collomia grandiflora Lindl.",
  "Colutea arborescens", "Colutea arborescens L.",
  "Commelina coelestis L.", "Commelina tuberosa L.",
  "Conium maculatum", "Conium maculatum L.", 
  "Conringia orientalis", "Conringia orientalis (L.) Dumort.",
  "Convallaria majalis", "Convallaria majalis L.", 
  "Convolvulus arvensis", "Convolvulus arvensis L.",  
  "Convolvulus arvensis L.", "Convolvulus arvensis L.",
  "Convolvulus dahuricus", "Calystegia pulchra Brumm. & Heywood",
  "Conyza squarrosa", "Pentanema squarrosum (L.) D.Gut.Larr., Santos-Vicente, Anderb., E.Rico & M.M.Mart.Ort.",
  "Coriandrum sativum", "Coriandrum sativum L.",
  "Corispermum hyssopifolium", "Corispermum hyssopifolium L.",
  "Cornus stolonifera", "Cornus sericea L.",
  "Coronilla scorpioides L.", "Coronilla scorpioides (L.) W.D.J.Koch",
  "Corrigiola litoralis", "Corrigiola litoralis L.",
  "Corydalis cava", "Corydalis cava (L.) Schweigg. & Körte",
  "Corydalis intermedia", "Corydalis intermedia (L.) Mérat",
  "Corydalis solida", "Corydalis solida (L.) Clairv.",
  "Corylus Avellana f. atropurpurea Petz, et Kirchn.", "Corylus avellana f. atropurpurea Kirchn.",
  "Cosmos bipinnatus", "Cosmos bipinnatus Cav.", 
  "Cosmos bipinnatus f. albiflorus hort.", "Cosmos bipinnatus Cav.",
  "Crataegus monogyna X oxyacantha", "Crataegus monogyna X oxyacantha",
  "Crataegus monogyna", "Crataegus monogyna Jacq.",
  "Crataegus monogyna f. fissa Bosc.", "Crataegus monogyna Jacq.",
  "Cotoneaster integerrimus", "Cotoneaster integerrimus Medik.",
  "Crepis biennis", "Crepis biennis L.", 
  "Crepis paludosa f. brachyotus", "Crepis paludosa (L.) Moench",
  "Crepis paludosus", "Crepis paludosa (L.) Moench",
  "Crepis praemorsa", "Crepis praemorsa (L.) Tausch",
  "Crepis succisifolia", "Crepis mollis subsp. succisifolia (All.) Dostál",
  "Crepis tectorum", "Crepis tectorum L.",
  "Crépis setosa", "Crepis setosa Haller fil.",
  "Crocus vernus", "Crocus vernus (L.) Hill",
  "Crocus vernus Wulf.", "Crocus vernus (L.) Hill",
  "Cucumis melo L.", "Cucumis melo L.",
  "Cucubalus baccifer", "Silene baccifera (L.) Roth",
  "Cucurbita maxima Duch.", "Cucurbita maxima Duchesne", 
  "Cucurbita Pepo", "Cucurbita pepo L.",
  "Cuscuta epilinum", "Cuscuta epilinum Weihe",
  "Cuscuta Epithymum", "Cuscuta pedicellata Ledeb.",
  "Cyclamen europaeum", "Cyclamen purpurascens Mill.",
  "Cynodon Dactylon", "Cynodon dactylon (L.) Pers.",
  "Cynodon Dactylon L.", "Cynodon dactylon (L.) Pers.",
  "Cynodon Dactylon Pers.", "Cynodon dactylon (L.) Pers.",
  "Cynodon dactylon", "Cynodon dactylon (L.) Pers.",
  "Cynoglossum officinale", "Cynoglossum officinale L.",
  "Cynoglossum officinalis", "Cynoglossum officinale L.",
  "Cynosurus echinatus", "Cynosurus echinatus L.", 
  "Cyperus Houghtonii Torrey", "Cyperus houghtonii Torr.", 
  "Cyperus alternifolius L.", "Cyperus alternifolius L.", 
  "Cyperus flavescens", "Cyperus flavescens L.",
  "Cypripedilum Calceolus", "Cypripedium calceolus L.",
  "Cystopteris fragilis", "Cystopteris fragilis (L.) Bernh.",
  "Cystopteris fragilis (L.) Beruh.", "Cystopteris fragilis (L.) Bernh.", 
  "Cystopteris sudetica", "Cystopteris sudetica A.Braun & Milde",
  "Cytisus capitatus", "Chamaecytisus hirsutus subsp. hirsutus",
  "Cytisus elongatus W. u. K.", "Chamaecytisus elongatus (Waldst. & Kit.) Link",
  "Cytisus elongatus", "Chamaecytisus elongatus (Waldst. & Kit.) Link",
  "Cytisus nigricans", "Cytisus nigricans L.",
  "Dactylis Aschersoniana Graebn.", "Dactylis glomerata subsp. lobata (Drejer) H.Lindb.",
  "Dactyloctenium aegyptium (L.) Pal.", "Dactyloctenium aegyptium (L.) Willd.",
  "Dahlia variabilis", "Dahlia variabilis Hort.", 
  "Daphne mezereum", "Daphne mezereum L.",
  "Daphne Mezereum", "Daphne mezereum L.",
  "Datura stramonium", "Datura stramonium L.",
  "Datura Stramonium", "Datura stramonium L.",
  "Datura Stramonium f.Tatula", "Datura stramonium var. tatula (L.) Torr.", 
  "Datura stramonium f. Tatula", "Datura stramonium var. tatula (L.) Torr.",
  "Daucus aureus", "Daucus aureus Desf.", 
  "Daucus aureus Desf.", "Daucus aureus Desf.",
  "Daucus carota", "Daucus carota L.", 
  "Delphinium Ajacis", "Delphinium ajacis L.", 
  "Delphinium ajacis", "Delphinium ajacis L.",
  "Dentaria bulbifera", "Cardamine bulbifera (L.) Crantz",
  "Dentaria enneaphyllos", "Cardamine enneaphyllos (L.) Crantz",
  "Dianthus barbatus", "Dianthus barbatus L.",
  "Dianthus carthusianorum", "Dianthus carthusianorum L.", 
  "Dianthus Carthusianorum", "Dianthus carthusianorum L.", 
  "Dianthus superbus", "Dianthus superbus L.",
  "Diervilla japonka DC.", "Weigela japonica Thunb.", 
  "Digitalis ambigua", "Digitalis grandiflora Mill.",
  "Digitalis purpurea", "Digitalis purpurea L.", 
  "Diplotaxis erucoides (L.) D. C.", "Diplotaxis erucoides (L.) DC.",
  "Diplotaxis muralis", "Diplotaxis muralis (L.) DC.",
  "Diplotaxis tenuifolia", "Diplotaxis tenuifolia (L.) DC.", 
  "Dipsacus laciniatus", "Dipsacus laciniatus L.",
  "Dipsacus sativus", "Dipsacus sativus (L.) Honck.",
  "Dipsacus silvester", "Dipsacus fullonum L.", 
  "Dipsacus Silvester", "Dipsacus fullonum L.",
  "Dorycnium suffruticosum Vill.", "Lotus dorycnium L.",
  "Dracocephalum Moldavica", "Dracocephalum moldavica L.",
  "Dracocephalum thymiflorum", "Dracocephalum thymiflorum L.",
  "Drosera intermedia", "Drosera intermedia Hayne",
  "Drosera longifolia", "Drosera longifolia Sm.",
  "Drosera rotundifolia", "Drosera rotundifolia L.", 
  "Echinops sphaerocephalus", "Echinops sphaerocephalus L.", 
  "Elaeagnus argentea Pursh", "Elaeagnus commutata Bernh. ex Rydb.",
  "Elatine alsinastrum L.", "Elatine alsinastrum L.", 
  "Elatine hexandra", "Elatine hexandra (Lapierre) DC.",
  "Elatine hydropiper", "Elatine hydropiper L.",
  "Elatine triandra", "Elatine triandra Schkuhr",
  "Elodea canadensis", "Elodea canadensis Michx.",
  "Epilobium adnatum", "Epilobium tetragonum L.",
  "Epilobium Dodonaei", "Chamaenerion dodonaei (Vill.) Schur ex Fuss.",
  "Epilobium hirsutum x montanum", "Epilobium hirsutum × montanum",
  "Epilobium lamyi", "Epilobium lamyi F.W.Schultz", 
  "Epilobium obscurum", "Epilobium obscurum Schreb.", 
  "Epilobium palustre f. glandulosum", "Epilobium palustre L.",
  "Epilobium palustre f. glandulosum Hauskn.", "Epilobium palustre L.",
  "Epilobium parviflorum", "Epilobium parviflorum Schreb.", 
  "Epilobium parviflorum x roseum", "Epilobium parviflorum x roseum", 
  "Epipactis latifolia", "Epipactis helleborine subsp. helleborine",
  "Epipactis latifolia x rubiginosa", "",
  "Epipactis palustris", "Epipactis palustris (L.) Crantz",
  "Epipactis rubiginosa", "Epipactis atrorubens (Hoffm.) Besser",
  "Epipactis violacea", "Epipactis purpurata Sm.",
  "Epipogon aphyllus", "Epipogium aphyllum Sw.",
  "Equisetum Telmateia Ehrh", "Equisetum telmateia Ehrh.", 
  "Equisetum arvense", "Equisetum arvense L.", 
  "Equisetum arvense L. var. boreale (Rup.) f. normalis", "Equisetum arvense L.", 
  "Equisetum arvense L. var. campestre (C.F. Schultz)", "Equisetum arvense L.", 
  "Equisetum arvense L. var. nemorosum A. Br.", "Equisetum arvense L.", 
  "Equisetum arvense f. campestre", "Equisetum arvense L.", 
  "Equisetum arvense f. irriguum", "Equisetum arvense L.", 
  "Equisetum arvense var. serotinum G. F. W. Mey.", "Equisetum arvense L.", 
  "Equisetum arvense x limosum", "", 
  "Equisetum hiemale", "Equisetum hyemale L.", 
  "Equisetum limosum", "Equisetum fluviatile L.", 
  "Equisetum limosum L. (erw.) var. attenuatum Milde", "Equisetum fluviatile L.", 
  "Equisetum limosum L. var. uliginosum (Mhbg.)", "Equisetum fluviatile L.", 
  "Equisetum limosum L. var. verticillatum Döll f. ramosissima Baenitz.", "Equisetum fluviatile L.", 
  "Equisetum limosum a. linnaeanum Döll.", "Equisetum fluviatile L.", 
  "Equisetum limosum v. uliginosum", "Equisetum fluviatile L.", 
  "Equisetum limosum var. uliginosum", "Equisetum fluviatile L.", 
  "Equisetum limosum var. uliginosum Mühlbg.", "Equisetum fluviatile L.", 
  "Equisetum litorale", "Equisetum ×litorale Kühlew. ex Rupr.", 
  "Equisetum litorale Kühl.", "Equisetum ×litorale Kühlew. ex Rupr.", 
  "Equisetum maximum", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum Lmk. var. serotinum A. Br.", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum f. serotinum", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum v. breve Milde", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum v. gracile", "Equisetum telmateia Ehrh.", 
  "Equisetum palustre", "Equisetum palustre L.", 
  "Equisetum palustre L. var. arcuatum Milde", "Equisetum palustre L.", 
  "Equisetum palustre f. arcuatum", "Equisetum palustre L.", 
  "Equisetum palustre f. polystachium", "Equisetum palustre L.", 
  "Equisetum pratense", "Equisetum pratense Ehrh.", 
  "Equisetum pratense Ehrh.", "Equisetum pratense Ehrh.", 
  "Equisetum ramosissimum", "Equisetum ramosissimum Desf.", 
  "Equisetum silvaticum", "Equisetum sylvaticum L.", 
  "Equisetum telmateja Ehrh.", "Equisetum telmateia Ehrh.", 
  "Equisetum Telmateia Ehrh.", "Equisetum telmateia Ehrh.", 
  "Equisetum Telmateja Ehrh.", "Equisetum telmateia Ehrh.", 
  "Equisetum variegatum", "Equisetum variegatum Schleich.", 
  "Eragrostis cilianensis (All.) Vignolo-Lutati", "Eragrostis cilianensis (All.) Vignolo ex Janch.",
  "Eragrostis mexicana (Lag.) Lk.", "Eragrostis mexicana (Hornem.) Link",
  "Eragrostis minor", "Eragrostis minor Host",
  "Erica tetralix", "Erica tetralix L.", 
  "Erica Tetralix", "Erica tetralix L.", 
  "Erigeron Bonariensis L.", "Erigeron bonariensis L.",
  "Erigeron ramosus", "Erigeron strigosus Muhl. ex Willd.",
  "Erigeron ramosus (Walter) B. S. P.", "Erigeron strigosus Muhl. ex Willd.",
  "Eriophorum angustifolium", "Eriophorum angustifolium Honck.",
  "Eriophorum gracile", "Eriophorum gracile W.D.J.Koch", 
  "Eriophorum gracile Koch.", "Eriophorum gracile W.D.J.Koch", 
  "Eriophorum latifolium", "Eriophorum latifolium Hoppe",
  "Eriophorum polystachyum", "Eriophorum angustifolium subsp. angustifolium",
  "Eriophorum vaginatum", "Eriophorum vaginatum L.",
  "Erodium malacoides", "Erodium malacoides (L.) L'Hér.",
  "Erodium Stephanianum Willd.", "Erodium stephanianum Willd.",
  "Eruca sativa", "Eruca sativa Hill",
  "Erucastrum Pollichii", "Erucastrum gallicum (Willd.) O.E.Schulz",
  "Eryngium planum", "Eryngium planum L.",
  "Erysimum cheiranthoides", "Erysimum cheiranthoides L.",
  "Erysimum hieracifolium", "Erysimum hieraciifolium L.",
  "Erysimum odoratum Ehrh.", "Erysimum odoratum Ehrh.",
  "Erysimum repandum", "Erysimum repandum L.",
  "Erythraea pulchella", "Centaurium pulchellum subsp. pulchellum",
  "Eupatorium cannabinum", "Eupatorium cannabinum L.", 
  "Euphorbia dulcis", "Euphorbia dulcis L.", 
  "Euphorbia lathyris", "Euphorbia lathyris L.",
  "Euphorbia platyphylla", "Euphorbia platyphyllos L.",
  "Euphorbia Esula", "Euphorbia esula L.",
  "Euphorbia Lathyris", "Euphorbia lathyris L.",
  "Euphorbia humifusa", "Euphorbia humifusa Willd.",
  "Euphorbia virgata", "Euphorbia virgata Waldst. & Kit.",
  "Euphrasia curta", "Euphrasia micrantha Rchb.",
  "Euphrasia rostkoviana", "Euphrasia officinalis subsp. pratensis (Fr.) Schübl. & G.Martens",
  "Evonymus europaeus", "Euonymus europaeus L.",
  "Evonymus latifolius", "Euonymus latifolius (L.) Mill.",
  "Falcaria vulgaris", "Falcaria vulgaris Bernh.", 
  "Fegatella conica", "Conocephalum conicum (L.) Dumort.",
  "Festuca arundinacea", "Lolium arundinaceum (Schreb.) Darbysh.",
  "Festuca arundinacea var. fasciculata Hackel", "Lolium arundinaceum (Schreb.) Darbysh.",
  "Festuca elatior f . pseudololiacea", "Lolium arundinaceum subsp. arundinaceum",
  "Festuca heterophylla", "Festuca heterophylla Lam.",
  "Festuca elatior var.pseudololiacea", "Lolium arundinaceum subsp. arundinaceum",
  "Festuca myurus", "Festuca myuros L.",
  "Festuca rubra f. barbata", "Festuca rubra L.",
  "Festuca sciuroides", "Festuca bromoides L.",
  "Filago apiculata", "Filago lutescens Jord.",
  "Filago germanica", "Filago germanica L.",
  "Ficus carica", "Ficus carica L.",
  "Foeniculum vulgare", "Foeniculum vulgare Mill.",
  "Fossombronia", "Fossombronia sp.",
  "Fragaria collina x vesca", "",
  "Fragaria moschata", "Fragaria moschata Duchesne",
  "Fumaria capreolata", "Fumaria capreolata L.",
  "Gagea arvensis", "Gagea arvensis Kar. & Kir. ex Ledeb.", 
  "Gagea minima", "Gagea minima (L.) Ker Gawl.",
  "Gagea pratensis", "Gagea pratensis (Pers.) Dumort.", 
  "Gagea spathacea Salisb.", "Gagea spathacea (Hayne) Salisb.",
  "Galanthus nivalis", "Galanthus nivalis L.",
  "Galega officinalis", "Galega officinalis L.",
  "Galeopsis angustifolia", "Galeopsis angustifolia Ehrh. ex Hoffm.",
  "Galinsoga parviflora", "Galinsoga parviflora Cav.", 
  "Galinsoga quadriradiata", "Galinsoga quadriradiata Ruiz & Pav.", 
  "Galium boreale", "Galium boreale L.", 
  "Galium Cruciata", "Cruciata laevipes Opiz",
  "Galium palustre", "Galium palustre L.",
  "Galium saccharatum All.", "Galium verrucosum Huds.",
  "Galium silvestre", "Galium pumilum Murray",
  "Galium spurium var. echinospermum (Wallr.) Hayek", "Galium spurium subsp. spurium",
  "Galium spurium var. leiospermum", "Galium spurium subsp. spurium",
  "Galium spurium var. leiospermum (Wallr.) Hayek", "Galium spurium subsp. spurium",
  "Galium tricorne", "Galium tricorne With., 1796", 
  "Galium vernum", "Cruciata glabra subsp. glabra",
  "Galium verum", "Galium verum L.",
  "Gastridium ventricosum", "Gastridium ventricosum (Gouan) Schinz & Thell.",
  "Gastridium ventricosum (Gouan) Schinz et Thellung.", "Gastridium ventricosum (Gouan) Schinz & Thell.",
  "Gaudinia fragilis", "Gaudinia fragilis (L.) P.Beauv.",
  "Geaster fornicatus Fries.", "Geastrum fornicatum (Huds.) Hook.",
  "Genista germanica", "Genista germanica L.",
  "Genista pilosa", "Genista pilosa L.",
  "Gentiana campestris", "Gentianella campestris subsp. campestris",
  "Gentiana ciliata", "Gentianopsis ciliata subsp. ciliata",
  "Gentiana cruciata", "Gentiana cruciata L.", 
  "Gentiana Cruciata", "Gentiana cruciata L.", 
  "Gentiana germanica", "Gentianella germanica subsp. germanica",
  "Gentiana germanica f. carpathica", "Gentianella germanica subsp. germanica",
  "Gentiana pneumonanthe", "Gentiana pneumonanthe L.",
  "Gentiana Pneumonanthe", "Gentiana pneumonanthe L.",
  "Gentiana praecox", "Gentianella praecox subsp. praecox", 
  "Gentiana verna", "Gentiana verna L.", 
  "Geranium columbinum", "Geranium columbinum L.",
  "Geranium dissectum", "Geranium dissectum L.",
  "Geranium molle", "Geranium molle L.",
  "Geranium phaeum", "Geranium phaeum L.",
  "Geranium pyrenaicum", "Geranium pyrenaicum Burm.f.",
  "Geranium pyrenaicum f. albiflorum", "Geranium pyrenaicum Burm.f.",
  "Geranium pyrenaicum f. albiflorum Schur", "Geranium pyrenaicum Burm.f.",
  "Geranium rotundifolium", "Geranium rotundifolium L.",
  "Geranium sanguineum", "Geranium sanguineum L.",
  "Geranium sibiricum", "Geranium sibiricum L.",
  "Geranium silvaticum", "Geranium sylvaticum L.",
  "Geranium silvaticum var. eglandulosum Cel.", "Geranium sylvaticum L.",
  "Geranium silvestre", "Geranium sylvaticum L.",
  "Geum rivale", "Geum rivale L.", 
  "Geum rivale f. luxurians Tratt.", "Geum rivale Bigelow", 
  "Gladiolus imbricatus", "Gladiolus imbricatus L.",
  "Glaucium corniculatum (L.) Cts.", "Glaucium corniculatum (L.) Curtis",
  "Glaucium flavum", "Glaucium flavum Crantz",
  "Glaucium corniculatum", "Glaucium corniculatum (L.) Rudolph",
  "Glyceria aquatica f. vivipara", "Glyceria maxima (Hartm.) Holmb.",
  "Glyceria nemoralis", "Glyceria nemoralis (R.Uechtr.) R.Uechtr. & Koern.",
  "Glyceria plicata Fries", "Glyceria notata Chevall.", 
  "Glycine hispida (Mönch) Maxim.", "Glycine max subsp. max", 
  "Gnaphalium luteo-album", "Helichrysum luteoalbum (L.) Rchb.",
  "Gnaphalium luteoalbum", "Helichrysum luteoalbum (L.) Rchb.",
  "Gratiola officinalis", "Gratiola officinalis L.", 
  "Guizotia abyssinica", "Guizotia abyssinica (L.fil.) Cass.",
  "Gymnadenia conopea", "Gymnadenia conopsea (L.) R.Br.",
  "Gymnadenia conopea var. densiflora", "Gymnadenia densiflora (Wahlenb.) A.Dietr.",
  "Gymnadenia conopea var. ornithis Beck", "Gymnadenia conopsea (L.) R.Br.",
  "Gypsophila elegans", "Gypsophila elegans M.Bieb.",
  "Gypsophila fastigiata", "Gypsophila fastigiata L.",
  "Gypsophila viscosa Murr.", "Gypsophila viscosa Murray",
  "Haynaldia villosa", "Dasypyrum villosum (L.) Borbás",
  "Haynaldia villosa (L.) Schur.", "Dasypyrum villosum (L.) Borbás",
  "Helenium autumnale L.", "Helenium autumnale L.",
  "Heleocharis ovata", "Eleocharis ovata (Roth) Roem. & Schult.",
  "Helianthemum chamaecistus", "Helianthemum nummularium subsp. obscurum (Pers. ex Wahlenb.) Holub",
  "Helianthus tuberosus", "Helianthus tuberosus L.", 
  "Helichrysum arenarium", "Helichrysum arenarium (L.) Moench",
  "Helleborus viridis", "Helleborus viridis L.",
  "Heracleum Sphondylium", "Heracleum sphondylium L.",
  "Hesperis matronalis", "Hesperis matronalis L.",
  "Hibiscus Tríonum", "Hibiscus trionum L.",
  "Hibiscus trionum", "Hibiscus trionum L.",
  "Heracleum sphondylium", "Heracleum sphondylium L.", 
  "Hieracium ambiguum Ehrh.", "Pilosella caespitosa subsp. caespitosa",
  "Hieracium aurantiacum", "Pilosella aurantiaca subsp. aurantiaca",
  "Hieracium auriculoides Lang. ssp. asperrimum Schur", "Pilosella auriculoides (Láng) Arv.-Touv.",
  "Hieracium bracchiatum Beck", "Pilosella acutifolia subsp. acutifolia",
  "Hieracium brachiatum Bertol.", "Pilosella acutifolia subsp. acutifolia",
  "Hieracium cernuiforme N. P.", "Hieracium cernuiforme N.P., 1885", 
  "Hieracium chaunanthes (N. P.) Zahn", "Pilosella rubra (Peter) Soják",
  "Hieracium cymoso-praealtum", "Pilosella piloselloides subsp. praealta (Gochnat) S.Bräut. & Greuter",
  "Hieracium cymosum", "Hieracium cymosum Willd., 1803", 
  "Hieracium cymosum ssp. pulveratum", "Pilosella cymosa subsp. cymosa (L.) F.W.Schultz & Sch.Bip.",
  "Hieracium echioides", "Pilosella echioides subsp. echioides (Lumn.) F.W.Schultz & Sch.Bip.",
  "Hieracium fallacinum F. Schultz", "Pilosella fallacina (F.W.Schultz) F.W.Schultz",
  "Hieracium floribundum", "Pilosella floribunda (Wimm. & Grab.) Fr.",
  "Hieracium iseranum Uechtritz", "Pilosella iserana (Uechtr.) Soják",
  "Hieracium laschii (Gebr. Schultz) Zahn", "Pilosella cana (Peter) Gottschl.",
  "Hieracium levicaule Jord.", "Hieracium levicaule Jord.",
  "Hieracium levigatum", "Hieracium laevigatum Willd.",
  "Hieracium liptoviense Borb.", "Hieracium liptoviense Borbás",
  "Hieracium liptoviense ssp. Schalowii Zahn", "Hieracium liptoviense Borbás", 
  "Hieracium Obornyanum N. P. ssp. Kruberi Zahn", "Pilosella polymastix (Peter) Holub",
  "Hieracium onosmoides Fr.", "Hieracium onosmoides Fr.",
  "Hieracium piloselloides", "Pilosella piloselloides subsp. piloselloides (Villars) Soják",
  "Hieracium praecox Schultz-Bip.", "Hieracium glaucinum subsp. glaucinum Jord.",
  "Hieracium pratense", "Pilosella caespitosa subsp. caespitosa",
  "Hieracium prussicum", "Pilosella prussica (Nägeli & Peter) Soják",
  "Hieracium prussicum N. P.", "Pilosella prussica (Nägeli & Peter) Soják",
  "Hieracium saxifragum Fr.", "Hieracium saxifragum Fr.",
  "Hieracium schultesii F. Schultz", "Pilosella schultesii (Sch.Bip.) F.W.Schultz & Sch.Bip.",
  "Hieracium stoloniflorum-collinum", "",
  "Hieracium tauschii", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium tauschii ssp. acrosciadium N. P.", "Pilosella densiflora (Tausch) Soják",
  "Hieracium tauschii Zahn", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium Tauschii", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium tephrosoma (N. P.) Zahn", "Hieracium tephrosoma (Nägeli & Peter) Zahn",
  "Hieracium Wiesbaurianum Uechtr.", "Hieracium hypochoeroides subsp. wiesbaurianum (R.Uechtr.) Greuter",
  "Hieracium Zizianum Tausch", "Pilosella ziziana subsp. ziziana",
  "Hierochloa odorata", "Anthoxanthum nitens (Weber) Y.Schouten & Veldkamp", 
  "Holoschoenus vulgaris", "Scirpoides holoschoenus (L.) Soják",
  "Holosteum umbellatum", "Holosteum umbellatum L.",
  "Holosteum umbellatum f. heuffeli", "Holosteum umbellatum L.",
  "Homogyne alpina", "Homogyne alpina (L.) Cass.",
  "Hordeum europaeum", "Hordelymus europaeus (L.) Jess. ex Harz", 
  "Hordeum maritimum With.", "Hordeum marinum Huds.",
  "Humulus Lupulus", "Humulus lupulus L.",
  "Hydrocharis Morsus ranae", "Hydrocharis morsus-ranae L.",
  "Hydrocotyle vulgaris", "Hydrocotyle vulgaris L.", 
  "Hypericum hirsutum", "Hypericum hirsutum L.",
  "Hypochoeris glabra", "Hypochoeris glabra L.", 
  "Hypochoeris maculata", "Trommsdorffia maculata subsp. maculata", 
  "Hyssopus officinalis", "Hyssopus officinalis L.", 
  "Hyssopus officinalis f. albus Alefeld", "Hyssopus officinalis L.", 
  "Iberis Lagascana DC.", "Iberis carnosa subsp. lagascana (DC.) Mateo & Figuerola",
  "Illecebrum verticillatum", "Illecebrum verticillatum L.",
  "Impatiens parviflora", "Impatiens parviflora DC.",
  "Impatiens Roylei", "Impatiens glandulifera Royle",
  "Imperatoria ostruthium", "Imperatoria ostruthium L.", 
  "Inula britannica", "Pentanema britannicum (L.) D.Gut.Larr., Santos-Vicente, Anderb., E.Rico & M.M.Mart.Ort.",
  "Inula helenium", "Inula helenium L.",
  "Inula salicina", "Pentanema salicinum subsp. salicinum",
  "Inula vulgaris", "Inula vulgaris Williams", 
  "Iris sibirica", "Iris sibirica L.",
  "Isatis tinctoria", "Isatis tinctoria L.",
  "Isoetes lacustris", "Isoetes lacustris L.", 
  "Isopyrum thalictroides", "Isopyrum thalictroides L.", 
  "Iva xanthiifolia (Fresen) Nutt.", "Cyclachaena xanthiifolia (Nutt.) Fresen.",
  "Jasione montana", "Jasione montana L.",
  "Juncus alpinus Vill.", "Juncus alpinoarticulatus subsp. alpinoarticulatus Chaix", 
  "Juncus filiformis", "Juncus filiformis L.",
  "Juncus filiformis f. pusillus Fries", "Juncus filiformis L.",
  "Juncus glaucus", "Juncus inflexus subsp. inflexus",
  "Juncus supinus", "Juncus supinus Bicheno, 1819", 
  "Juncus supinus var. confervaceus (St. Lager) Buchenau", "Juncus bulbosus subsp. bulbosus",
  "Juncus tenageja", "Juncus tenageia Ehrh. ex L.fil.", 
  "Juncus Tanageia", "Juncus tenageia Ehrh. ex L.fil.", 
  "Juncus tenuis", "Juncus tenuis Willd.",
  "Juniperus communis", "Juniperus communis L.",
  "Kochia scoparia", "Bassia scoparia (L.) A.J.Scott",
  "Kochia Scoparia f. trichophila Schinz et Thell.", "Bassia scoparia (L.) A.J.Scott",
  "Koeleria hispida (Savi) D. C.", "Rostraria hispida (Savi) Dogan", 
  "Koeleria phleoides", "Rostraria cristata (L.) Tzvelev",
  "Koeleria phleoides (Vili.) Pers.", "Rostraria cristata (L.) Tzvelev",
  "Lactuca scariola", "Lactuca serriola L.",
  "Lactuca Scariola f. augustana", "Lactuca serriola f. integrifolia (J.Becker) Hegi",
  "Lactuca saligna", "Lactuca saligna L.", 
  "Lactuca virosa", "Lactuca virosa L.",
  "Lagoseris Nemausensis (Gouan) Koch", "Crepis sancta subsp. sancta",
  "Lagurus ovatus", "Lagurus ovatus L.",
  "Lamium galeobdolon", "Lamium galeobdolon (L.) L.", 
  "Lampsana communis f. minor Zimm.", "Lapsana communis L.",
  "Lappula Myosotis", "Lappula squarrosa (Retz.) Dumort.",
  "Lappula patula (Lehm)", "Lappula patula (Lehm.) Gürke",
  "Laserpicium prutenicum", "Silphiodaucus prutenicus subsp. prutenicus",
  "Laserpicium prutenicum f. glabrum", "Silphiodaucus prutenicus subsp. prutenicus",
  "Lathraea squamaria", "Lathraea squamaria L.",
  "Lathyrus aphaca", "Lathyrus aphaca L.",
  "Lathyrus Aphaca", "Lathyrus aphaca L.",
  "Lathyrus niger", "Lathyrus niger (L.) Bernh.",
  "Lathyrus niger f. heterophyllus", "Lathyrus niger subsp. niger",
  "Lathyrus nissolia", "Lathyrus nissolia L.",
  "Lathyrus Nissolia", "Lathyrus nissolia L.",
  "Lathyrus montanus", "Lathyrus linifolius (Reichard) Bässler",
  "Lathyrus odoratus", "Lathyrus odoratus L.",
  "Lathyrus odoratus L.", "Lathyrus odoratus L.",
  "Lathyrus paluster", "Lathyrus palustris L.",
  "Lathyrus silvester", "Lathyrus sylvestris L.",
  "Lathyrus silvester f. ensifolius", "Lathyrus sylvestris L.",
  "Lathyrus silvestris", "Lathyrus sylvestris L.",
  "Lathyrus sylvestris", "Lathyrus sylvestris L.", 
  "Lathyrus tuberosus", "Lathyrus tuberosus L.",
  "Lavatera thuringiaca", "Malva thuringiaca subsp. thuringiaca",
  "Lavatera trimestris", "Malva trimestris (L.) Salisb.",
  "Ledum palustre", "Rhododendron tomentosum subsp. tomentosum",
  "Leersia oryzoides", "Leersia oryzoides (L.) Sw.",
  "Leersia Oryzoides", "Leersia oryzoides (L.) Sw.",
  "Lemna gibba", "Lemna gibba L.",
  "Lemna polyrrhiza", "Spirodela polyrhiza (L.) Schleid.",
  "Lens esculenta", "Vicia lens (L.) Coss. & Germ.",
  "Leontodon taraxacum", "Taraxacum officinale Weber ex Wiggins", 
  "Lepidium densiflorum", "Lepidium densiflorum Schrad.",
  "Lepidium draba", "Lepidium draba L.",
  "Lepidium Draba", "Lepidium draba L.",
  "Lepidium heterophyllum", "Lepidium heterophyllum Benth.",
  "Lepidium heterophyllum (D. C.) Bentham", "Lepidium heterophyllum Benth.",
  "Lepidium latifolium L.", "Lepidium latifolium L.",
  "Lepidium ruderale", "Lepidium ruderale L.",
  "Lepidium sativum", "Lepidium sativum L.",
  "Lepidium virginicum", "Lepidium virginicum L.",
  "Lepidium Virginicum", "Lepidium virginicum L.",
  "Lepturus incurvatus Trin.", "Parapholis incurva (L.) C.E.Hubb.",
  "Lepturus pannonicus Knuth.", "Pholiurus pannonicus (Host) Trin.",
  "Leucoium vernum", "Leucojum vernum L.",
  "Leucojum vernum", "Leucojum vernum L.",
  "Levisticum officinale", "Levisticum officinale W.D.J.Koch",
  "Ligustrum vulgare", "Ligustrum vulgare L.", 
  "Lilium martagon", "Lilium martagon L.",
  "Lilium Martagon", "Lilium martagon L.",
  "Limnanthemum nymphaeoides", "Nymphoides peltata (S.G.Gmel.) Kuntze",
  "Limnanthemum Nymphaeoides", "Nymphoides peltata (S.G.Gmel.) Kuntze",
  "Limosella aquatica", "Limosella aquatica L.", 
  "Linaria arvensis", "Linaria arvensis (L.) Desf.",
  "Linaria bipartita", "Linaria bipartita (Vent.) Willd.",
  "Linaria cymbalaria", "Cymbalaria muralis subsp. muralis G.Gaertner, B.Meyer & Scherbius",
  "Linaria Cymbalaria", "Cymbalaria muralis subsp. muralis G.Gaertner, B.Meyer & Scherbius",
  "Linaria Elatine", "Kickxia elatine subsp. elatine",
  "Linaria genistifolia", "Linaria genistifolia (L.) Mill.",
  "Linaria minor", "Chaenorhinum minus subsp. minus (L.) Lange",
  "Linaria pilosa (Jacq.) DC.", "Cymbalaria pilosa (Jacq.) L.H.Bailey",
  "Linaria vulgaris", "Linaria vulgaris Mill.",
  "Lindernia pyxidaria", "Lindernia pyxidaria Pursh", 
  "Linum usitatissimum", "Linum usitatissimum L.", 
  "Linum usitatissimum f. leucanthum Maly", "Linum usitatissimum L.", 
  "Lobelia erinus", "Lobelia erinus L.", 
  "Lobularia maritima", "Lobularia maritima (L.) Desv.",
  "Lolium multiflorum f. ramosum", "Lolium multiflorum Lam.",
  "Lolium perenne f. compositum", "Lolium perenne L.",
  "Lolium perenne f. cristatum", "Lolium perenne L.",
  "Lolium remotum", "Lolium remotum Schrank", 
  "Lolium rigidum", "Lolium rigidum Gaudin",
  "Lolium rigidum Gaud.", "Lolium rigidum Gaudin",
  "Lolium subulatum Vis.", "Lolium rigidum Gaudin",
  "Lolium temulentum", "Lolium temulentum L.",
  "Lolium temulentum f. arvense", "Lolium temulentum L.",
  "Lolium temulentum var. arvense", "Lolium temulentum L.",
  "Lonicera caprifolium", "Lonicera caprifolium L.",
  "Lonicera morrowii", "Lonicera morrowii Gray", 
  "Lonicera periclymenum", "Lonicera periclymenum L.", 
  "Lonicera Periclymenum", "Lonicera periclymenum L.", 
  "Lonicera tatarica", "Lonicera tatarica L.",
  "Lonicera xylosteum", "Lonicera xylosteum L.", 
  "Lonicera Xylosteum", "Lonicera xylosteum L.", 
  "Lotus siliquosus", "Lathyrus inconspicuus var. inconspicuus", 
  "Lotus tenuifolius", "Lotus tenuis Waldst. & Kit. ex Willd.",
  "Lunaria annua", "Lunaria annua L.",
  "Lunaria rediviva", "Lunaria rediviva L.",
  "Lupinus albus L.", "Lupinus albus L.",
  "Lupinus angustifolius", "Lupinus angustifolius L.",
  "Luzula nemorosa", "Luzula luzuloides (Lam.) Dandy & Wilmott",
  "Luzula silvatica", "Luzula sylvatica (Huds.) Gaudin",
  "Lychnis chalcedonica", "Silene chalcedonica (L.) E.H.L.Krause",
  "Lychnnis Chalcedonica L.", "Silene chalcedonica (L.) E.H.L.Krause",
  "Lychnis coronaria", "Silene coronaria (L.) Clairv.",
  "Lycium halimifolium", "Lycium barbarum L.", 
  "Lycopodium alpinum", "Diphasiastrum alpinum (L.) Holub", 
  "Lycopodium annotinum", "Lycopodium annotinum L.", 
  "Lycopodium annotinum f. integrifolium", "Lycopodium annotinum L.", 
  "Lycopodium chamaecyparissus", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium clavatum", "Lycopodium clavatum L.", 
  "Lycopodium clavatum L. var. tristachyum Nutt. (als Alt)", "Lycopodium clavatum L.", 
  "Lycopodium complanatum", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum L. ssp. anceps (Wallr.)", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum L. ssp. chamaecyparissus ABr.", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium complanatum L. var. L. Chamaecyparissus A, Braun.", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium complanatum anceps Wallr.", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum f. brachystachys", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium inundatum", "Lycopodiella inundata (L.) Holub", 
  "Lycopodium selago", "Huperzia selago (L.) Bernh. ex Schrank & Mart", 
  "Lysimachia thyrsiflora", "Lysimachia thyrsiflora L.", 
  "Lysimachia Nummularia", "Lysimachia nummularia L.",
  "Macleya cordata", "Macleaya cordata (Willd.) R.Br.",
  "Macleya cordata R. Br.", "Macleaya cordata (Willd.) R.Br.",
  "Malcolmia maritima", "Malcolmia maritima (L.) W.T.Aiton",
  "Malope trifida", "Malope trifida Cav.",
  "Malope trifida Cav.", "Malope trifida Cav.",
  "Malva crispa", "Malva verticillata L.",
  "Malva moschata", "Malva moschata L.",
  "Malva parviflora", "Malva parviflora L.",
  "Malva pusilla With.", "Malva pusilla Sm.",
  "Malva verticillata", "Malva verticillata L.",
  "Malva verticillata L.", "Malva verticillata L.",
  "Malva verticillata var. crispa", "Malva verticillata L.",
  "Malva verticillata var. crispa L.", "Malva verticillata L.",
  "Marrubium vulgare", "Marrubium vulgare L.",
  "Matricaria chamomilla", "Matricaria chamomilla L.", 
  "Matricaria chamomilla f. eradiata", "Matricaria chamomilla L.", 
  "Matricaria Chamomilla f. eradiata Rupr.", "Matricaria chamomilla L.", 
  "Matricaria discoidea", "Matricaria discoidea DC.",
  "Matricaria inodora", "Tripleurospermum inodorum (L.) Sch.-Bip", 
  "Matthiola bicornis", "Matthiola longipetala subsp. bicornis (Sm.) P.W.Ball",
  "Medicago aculeata Gaertn.", "Medicago polymorpha L.",
  "Medicago falcata f. glandulosa", "Medicago falcata subsp. glandulosa (W.D.J.Koch) Kozuharov",
  "Medicago falcata x sativa", "Medicago sativa subsp. x varia ",
  "Medicago hispida", "Medicago polymorpha L.",
  "Medicago hispida var. apiculata (Willd.) Burn.", "Medicago polymorpha L.",
  "Medicago hispida var. confinis (Koch) Burn.", "Medicago polymorpha L.",
  "Medicago hispida var. denticulata (Willd.) Burn.", "Medicago polymorpha L.",
  "Medicago rigidula var. minor (Sav.) Thell.", "Medicago rigidula (L.) All.",
  "Medicago rigidula (L.) Desr.", "Medicago rigidula (L.) All.",
  "Medicago sativa L. ssp. microcarpa Urban", "Medicago sativa subsp. sativa L.",
  "Medicago scutellata All.", "Medicago scutellata (L.) Mill.",
  "Melampyrum cristatum", "Melampyrum cristatum L.", 
  "Melampyrum cristatum f. pallidum", "Melampyrum cristatum L.", 
  "Melampyrum silvaticum f. dentatum", "Melampyrum sylvaticum L.",
  "Melandryum album x rubrum", "Melandryum album X rubrum",
  "Melandryum album X rubrum", "Melandryum album X rubrum",
  "Melandryum noctiflorum", "Silene noctiflora L.", 
  "Melandryum rubrum", "Silene dioica subsp. dioica", 
  "Melica ciliata", "Melica ciliata L.",
  "Melica uniflora", "Melica uniflora Retz.", 
  "Melilotus albus", "Melilotus albus Medik.", 
  "Melilotus altissimus", "Melilotus altissimus Thuill.",
  "Melilotus indicus", "Melilotus indicus (L.) All.",
  "Melilotus officinalis", "Melilotus officinalis (L.) Lam.",
  "Melilotus Siculus (Turra) Jackson", "Melilotus siculus (Turra) Steud.",
  "Melilotus sulcatus", "Melilotus sulcatus Desf.",
  "Melilotus sulcatus Desf.", "Melilotus sulcatus Desf.",
  "Melittis melissophyllum", "Melittis melissophyllum L.",
  "Mentha arvensis x longifolia", "Mentha arvensis X longifolia",
  "Mentha piperita", "Mentha ×piperita L.",
  "Mentha Pulegium var. hirsuta (Perard) Briquet", "Mentha pulegium L.",
  "Mentha verticillata f. subspicata", "Mentha aquatica L.",
  "Mentha villosa", "Mentha ×villosa Huds.",
  "Mentha viridis", "Mentha spicata subsp. spicata",
  "Menyanthes trifoliata", "Menyanthes trifoliata L.", 
  "Mercurialis annua", "Mercurialis annua L.",
  "Mercurialis perennis", "Mercurialis perennis L.",
  "Merremia sibirica (L.) Hall. f.", "Merremia sibirica (L.) Hallier fil.",
  "Mesembrianthemum cordifolium", "Mesembryanthemum cordifolium L.fil.",
  "Meum athamanticum", "Meum athamanticum Jacq.",
  "Mimulus guttatus", "Erythranthe guttata (DC.) G.L.Nesom",
  "Mimulus moschatus", "Erythranthe moschata (Douglas ex Lindl.) G.L.Nesom",
  "Mirabilis Jalapa L.", "Mirabilis jalapa L.", 
  "Montia intermedia", "Montia fontana subsp. amporitana Sennen",
  "Montia intermedia Decker.", "Montia fontana subsp. amporitana Sennen",
  "Montia rivularis", "Montia fontana subsp. fontana Linnaeus",
  "Mulgedium alpinum", "Cicerbita alpina (L.) Wallr.",
  "Mulgedium macrophyllum", "Lactuca macrophylla subsp. macrophylla (Willd.) A.Gray", 
  "Muscari comosum", "Leopoldia comosa (L.) Parl.",
  "Muscari racemosum", "Muscari racemosum Mill.",
  "Myosotis caespitosa", "Myosotis caespitosa DC., 1846", 
  "Myosotis palustris", "Myosotis scorpioides L.", 
  "Myosotis silvatica f. lactea", "Myosotis sylvatica Ehrh. ex Hoffm.", 
  "Myosotis sparsiflora", "Myosotis sparsiflora Pohl",
  "Myriophyllum spicatum", "Myriophyllum spicatum L.", 
  "Myriophyllum verticillatum", "Myriophyllum verticillatum L.", 
  "Myrrhis odorata", "Myrrhis odorata (L.) Scop.", 
  "Najas marina", "Najas marina L.",
  "Narcissus poeticus", "Narcissus poeticus L.",
  "Narcissus Pseudo—Narcissus", "Narcissus pseudonarcissus L.",
  "Narcissus pseudonarcissus", "Narcissus pseudonarcissus L.",
  "Nasturtium Armoracia", "Armoracia rusticana P.Gaertn., B.Mey. & Scherb.",
  "Nasturtium armoracia", "Armoracia rusticana P.Gaertn., B.Mey. & Scherb.",
  "Nasturtium austriacum", "Rorippa austriaca (Crantz) Besser",
  "Nasturtium palustre", "Rorippa palustris (L.) Besser",
  "Nasturtium officinale", "Nasturtium officinale R.Br.", 
  "Neottia nidus avis", "Neottia nidus-avis (L.) Rich.", 
  "Neottia Nidus avis", "Neottia nidus-avis (L.) Rich.", 
  "Nepeta Cataria", "Nepeta cataria L.",
  "Nepeta Mussini Henckel v. Donnersm.", "Nepeta racemosa subsp. racemosa",
  "Nicandra physaloides", "Physochlaina physaloides (L.) G.Don", 
  "Nicotiana Sanderae Sand.", "Nicotiana ×sanderae W.Watson",
  "Nicotiana latissima", "Nicotiana tabacum L.",
  "Nicotiana rustica", "Nicotiana rustica L.", 
  "Nigella Damascena", "Nigella damascena L.",
  "Nitella flexilis", "Nitella flexilis (L.) C.Agardh",
  "Nonnea rosea (M. B.) Lk.", "Nonea rosea (M.Bieb.) Link", 
  "Nymphaea alba", "Nymphaea alba L.",
  "Nymphaea candida", "Nymphaea candida J.Presl & C.Presl",
  "Oenanthe aquatica", "Oenanthe aquatica (L.) Poir.",
  "Oenanthe fistulosa", "Oenanthe fistulosa L.",
  "Oenothera fruticosa L.", "Oenothera fruticosa L.",
  "Oenothera muricata", "Oenothera biennis L.", 
  "Omphalodes scorpioides", "Memoremea scorpioides (Haenke) A.Otero, Jim.Mejías, Valcárcel & P.Vargas",
  "Omphalodes verna", "Omphalodes verna Moench",
  "Onobrychis viciaefolia", "Onobrychis viciifolia Scop.",
  "Ononis hircina var. spinescens", "Ononis arvensis L.",
  "Ononis spinosa", "Ononis spinosa L.",
  "Onopordon acanthium", "Onopordum acanthium L.",
  "Onopordum acanthium", "Onopordum acanthium L.",
  "Onopordum Acanthium", "Onopordum acanthium L.",
  "Ophioglossum vulgatum", "Ophioglossum vulgatum L.",
  "Ophioglossum vulgatum L.", "Ophioglossum vulgatum L.",
  "Orchis globosa", "Traunsteinera globosa (L.) Rchb.",
  "Orchis incarnata", "Dactylorhiza incarnata (L.) Soó",
  "Orchis latifolia", "Dactylorhiza incarnata subsp. incarnata",
  "Orchis mascula", "Orchis mascula (L.) L.",
  "Orchis militaris", "Orchis militaris L.",
  "Orchis morio", "Anacamptis morio (L.) R.M.Bateman, Pridgeon & M.W.Chase",
  "Orchis sambucina", "Dactylorhiza sambucina (L.) Soó",
  "Orchis ustulata", "Neotinea ustulata (L.) R.M.Bateman, Pridgeon & M.W.Chase",
  "Origanum vulgare", "Origanum vulgare L.",
  "Ornithogalum Boucheanum", "Ornithogalum boucheanum (Kunth) Asch.", 
  "Ornithogalum nutans", "Ornithogalum nutans L.",
  "Ornithogalum tenuifolium", "Ornithogalum gussonei Ten.",
  "Ornithogalum umbellatum", "Ornithogalum umbellatum L.",
  "Ornithopus compressus L.", "Ornithopus compressus L.",
  "Ornithopus perpusillus", "Ornithopus perpusillus L.",
  "Orobanche caryophyllea", "Orobanche caryophyllacea Sm.", 
  "Orobanche lutea", "Orobanche lutea Baumg.",
  "Orobanche pallidiflora", "Orobanche reticulata subsp. pallidiflora (Wimm. & Grab.) Hayek", 
  "Osmunda regalis", "Osmunda regalis L.", 
  "Osmunda regalis L.", "Osmunda regalis L.", 
  "Oxalis acetosella", "Oxalis acetosella L.",
  "Oxalis tetraphylla", "Oxalis tetraphylla Cav.",
  "Panicum colonum", "Echinochloa colonum (L.) Link",
  "Panicum crus galli var. edule (Hitchcook) Thell.", "Echinochloa frumentacea Link",
  "Panicum dichotomiflorum Michx.", "Panicum dichotomiflorum Michx.",
  "Panicum lineare", "Panicum lineare Burm.f., 1768",
  "Panicum sanguinale f. Aegyptiacum (Retz) Richter", "Digitaria sanguinalis (L.) Scop.",
  "Panicum sanguinale f. atrichum Aschers, u. Gr.", "Digitaria sanguinalis (L.) Scop.",
  "Panicum sanguinale f. esculenta Gaud.", "Digitaria sanguinalis (L.) Scop.",
  "Papaver dubium", "Papaver dubium L.",
  "Papaver hybridum L.", "Roemeria hispida Stace", 
  "Papaver somniferum", "Papaver somniferum L.",
  "Papaver somniferum f. laciniatum", "Papaver somniferum L.",
  "Parietaria officinalis", "Parietaria officinalis L.",
  "Pastinaca sativa", "Pastinaca sativa L.", 
  "Pedicularis palustris", "Pedicularis palustris L.", 
  "Pedicularis silvatica", "Pedicularis sylvatica L.",
  "Pellia epiphyla", "Pellia epiphylla (L.) Corda", 
  "Petasites albus", "Petasites albus (L.) Gaertn.",
  "Petasites officinalis", "Petasites hybridus subsp. hybridus ", 
  "Petroselinum sativum", "Petroselinum crispum (Mill.) Fuss",
  "Peucedanum cervaria", "Cervaria rivini Gaertn.", 
  "Peucedanum Cervaria", "Cervaria rivini Gaertn.", 
  "Peucedanum palustre", "Thysselinum palustre (L.) Hoffm.", 
  "Phacelia congesta Hook.", "Phacelia congesta (Douglas ex Lehm.) Hook.",
  "Phacelia tanacetifolia", "Phacelia tanacetifolia Benth.", 
  "Phalaris arundinacea f. picta", "Phalaris arundinacea var. picta Muhl. ex W.P.C.Barton, 1815",
  "Phalaris brachystachys Link", "Phalaris brachystachys Link",
  "Phalaris canariensis", "Phalaris canariensis L.",
  "Phalaris coerulescens Desf.", "Phalaris coerulescens Desf.",
  "Phalaris minor", "Phalaris minor Retz.",
  "Phalaris minor Retz", "Phalaris minor Retz.",
  "Phalaris paradoxa", "Phalaris paradoxa L.",
  "Phalaris paradoxa L.", "Phalaris paradoxa L.",
  "Phalaris truncata Guss.", "Phalaris truncata Guss.",
  "Pharbitis purpurea", "Ipomoea purpurea (L.) Roth",
  "Phegopteris dryopteris (L.) Fee", "Gymnocarpium dryopteris (L.) Newman",
  "Phegopteris polypodioides Fée.", "Phegopteris connectilis (Michx.) Watt",
  "Phegopteris robertiana", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phegopteris robertiana (Hoffm.) A. Br.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phegopteris robertianum A. Br.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phleum alpinum f. bracteatum", "Phleum alpinum L.",
  "Phleum Boehmeri", "Phleum phleoides (L.) H.Karst.",
  "Phleum Boehmeri f. blepharodes", "Phleum phleoides (L.) H.Karst.",
  "Phleum pratense", "Phleum pratense L.",
  "Phleum pratense f. lobatum", "Phleum pratense L.",
  "Phleum subulatum (Savi) Aschers. et Gr.", "Phleum subulatum (Savi) Asch. & Graebn.",
  "Phragmites communis f. picta Hammerschmid", "Phragmites australis (Cav.) Trin. ex Steud.", 
  "Physalis Alkekengi", "Alkekengi officinarum Moench",
  "Physalis alkekengi", "Alkekengi officinarum Moench",
  "Physocarpus opulifolius", "Physocarpus opulifolius (L.) Maxim.",
  "Phyteuma orbiculare", "Phyteuma orbiculare L.", 
  "Phyteuma spicatum", "Phyteuma spicatum L.",
  "Phytolacca decandra", "Phytolacca americana L.",
  "Picris echioides", "Helminthotheca echioides (L) Holub",
  "Picris hieracioides", "Picris hieracioides L.",
  "Pilularia globulifera", "Pilularia globulifera L.",
  "Pimpinella magna", "Pimpinella major subsp. major",
  "Pimpinella Saxifraga f. dissecta", "Pimpinella saxifraga L.",
  "Pinguicula vulgaris", "Pinguicula vulgaris L.",
  "Pinus Pumilio", "Pinus mugo subsp. mugo",
  "Pinus uliginosa", "Pinus mugo subsp. rotundata (Link) Janch. & H.Neumayer",
  "Pirola chlorantha", "Pyrola chlorantha Sw.",
  "Pirola media", "Pyrola media Sw.",
  "Pirola uniflora", "Moneses uniflora (L.) A.Gray",
  "Pirus malus", "Malus domestica (Suckow) Borkh.",
  "Plantago arenaria", "Plantago arenaria Waldst. & Kit.", 
  "Plantago intermedia", "Plantago uliginosa subsp. uliginosa",
  "Plantago intermedia Gilibert", "Plantago uliginosa subsp. uliginosa", 
  "Plantago lagopus L.", "Plantago lagopus L.",
  "Plantago lanceolata", "Plantago lanceolata L.",
  "Plantago laneeolata f. polystachya", "Plantago lanceolata L.",
  "Plantago major", "Plantago major L.",
  "Poa bulbosa", "Poa bulbosa L.", 
  "Poa chaixii var. remota", "Poa remota Forselles", 
  "Poa Chaixi var. remota", "Poa remota Forselles", 
  "Poa nemoralis var. montana", "Poa nemoralis L.",
  "Polemonium coeruleum", "Polemonium caeruleum L.", 
  "Polygala amara", "Polygala amara L.", 
  "Polygonatum officinale", "Polygonatum officinale All.",
  "Polygonum arenarium W. K.", "Polygonum arenarium Waldst. & Kit.",
  "Polygonum aviculare var. monspeliense", "Polygonum aviculare subsp. aviculare",
  "Polygonum cuspidatum", "Reynoutria japonica Houtt.",
  "Polygonum mite", "Persicaria mitis (Schrank) Assenov",
  "Polygonum orientale", "Persicaria orientalis (L.) Spach",
  "Polygonum patulum", "Polygonum patulum M.Bieb.",
  "Polygonum patulum M. B.", "Polygonum patulum M.Bieb.",
  "Polygonum polystachyum", "Polygonum polystachyum Wall., 1829",
  "Polygonum sachalinense", "Reynoutria sachalinensis (F.Schmidt) Nakai",
  "Polyporus lucidus","Ganoderma lucidum (Curtis) P.Karst.",
  "Polypogon monspeliensis", "Polypogon monspeliensis (L.) Desf.",
  "Polypodium Robertianum Hoffm.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Polypodium dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Polypodium phegopteris", "Phegopteris connectilis (Michx.) Watt",
  "Polypodium vulgare", "Polypodium vulgare L.", 
  "Polypodium vulgare L.", "Polypodium vulgare L.",
  "Populus alba", "Populus alba L.",
  "Portulaca grandiflora Hook.", "Portulaca grandiflora Hook.",
  "Portulaca oleracea", "Portulaca oleracea L.",
  "Potamogeton acutifolius", "Potamogeton acutifolius Link ex Roem. & Schult.",
  "Potamogeton alpinus", "Potamogeton alpinus Balb.",
  "Potamogeton crispus", "Potamogeton crispus L.", 
  "Potamogeton densus L.", "Groenlandia densa (L.) Fourr.", 
  "Potamogeton natans", "Potamogeton natans L.",
  "Potamogeton obtusifolius", "Potamogeton obtusifolius Mert. & W.D.J.Koch",
  "Potamogeton pectinatus", "Stuckenia pectinata (L.) Börner",
  "Potamogeton polygonifolius", "Potamogeton polygonifolius Pourr.",
  "Potamogeton praelongus", "Potamogeton praelongus Wulfen",
  "Potamogeton pusillus", "Potamogeton pusillus L.",
  "Potamogeton rufescens", "Potamogeton alpinus subsp. alpinus Balbis",
  "Potentilla alba", "Potentilla alba L.", 
  "Potentilla arenaria", "Potentilla incana Borkh.", 
  "Potentilla aurea", "Potentilla aurea L.",
  "Potentilla canescens", "Potentilla inclinata Vill.",
  "Potentilla fragariastrum", "Potentilla sterilis (L.) Garcke",
  "Potentilla norvegica", "Potentilla norvegica L.",
  "Potentilla opaca", "Potentilla heptaphylla subsp. heptaphylla",
  "Potentilla opaca X Potentilla verna", "",
  "Potentilla palustris", "Comarum palustre L.",
  "Potentilla recta", "Potentilla recta L.",
  "Potentilla silesiaca", "Potentilla silesiaca Uechtr.", 
  "Potentilla supina", "Potentilla supina L.",
  "Potentilla verna", "Potentilla verna L.",
  "Potentilla verna f. parviflora f. nov.", "Potentilla verna L.",
  "Potentilla wiemanniana", "Potentilla wiemanniana Spreng. ex Günther & Schummel",
  "Preissia commutata", "Marchantia quadrata Scop.", 
  "Primula elatior f. colorata Pax", "Primula elatior subsp. elatior",
  "Primula officinalis", "Primula officinalis Wulfen, 1778", 
  "Prunella laciniata", "Prunella laciniata (L.) L.",
  "Prunella laciniata X vulgaris", "Prunella laciniata × vulgaris",
  "Prunus Cerasus", "Prunus cerasus L.",
  "Prunus domestica", "Prunus domestica L.",
  "Prunus italica", "Prunus domestica subsp. insititia (L.) Bonnier & Layens",
  "Prunus serotina", "Prunus serotina Ehrh.",
  "Prunus spinosa L.", "Prunus spinosa L.",
  "Pteris aquilina", "Pteridium aquilinum (L.) Kuhn",
  "Pulicaria vulgaris", "Pulicaria vulgaris Gaertn.", 
  "Pulmonaria angustifolia", "Pulmonaria angustifolia L.",
  "Pulmonaria officinalis f. albiflora", "Pulmonaria officinalis L.",
  "Pulmonaria officinalis f. maculosa", "Pulmonaria officinalis subsp. officinalis",
  "Quercus robur", "Quercus robur L.",
  "Quercus robur X Quercus sessiliflora", "Quercus ×rosacea Bechst.",
  "Quercus robur var. longipetiolati Schröter", "Quercus robur L.",
  "Ranunculus auricomus var. fallax", "Ranunculus fallax (Wimm. & Grab.) Schur",
  "Ranunculus auricomus f. fallax", "Ranunculus fallax (Wimm. & Grab.) Schur",
  "Ranunculus bulbosus X Ranunculus polyanthemos", "",
  "Ranunculus cassubicus", "Ranunculus cassubicus L.",
  "Ranunculus flaccidus", "Ranunculus trichophyllus subsp. trichophyllus Chaix ex Villars", 
  "Ranunculus lanuginosus", "Ranunculus lanuginosus L.",
  "Ranunculus lingua", "Ranunculus lingua L.",
  "Ranunculus polyanthemus", "Ranunculus polyanthemos L.", 
  "Ranunculus sceleratus", "Ranunculus sceleratus L.",
  "Ranunculus sceleratus f. natans Gluck", "Ranunculus sceleratus subsp. sceleratus L., 1753",
  "Ranunculus Steveni", "Ranunculus japonicus Thunb.",
  "Ranunculus trichophyllus", "Ranunculus trichophyllus Chaix", 
  "Raphanus raphanistrum var. purpurascens Dum.", "Raphanus raphanistrum L.",
  "Rapistrum rugosum", "Rapistrum rugosum (L.) All.",
  "Reseda lutea", "Reseda lutea L.",
  "Reseda lutea var. crispa J. Müller", "Reseda lutea subsp. lutea",
  "Reseda luteola", "Reseda luteola L.",
  "Reseda odorata", "Reseda odorata L.",
  "Rhamnus cathartica", "Rhamnus cathartica L.",
  "Rhamnus Frangula f. quercifolia nov. f.", "Frangula alnus subsp. alnus",
  "Rhus Toxicodendron", "Toxicodendron radicans subsp. radicans (Linnaeus) Kuntze",
  "Rhynchospora alba", "Rhynchospora alba (L.) Vahl",
  "Rhynchospora fusca", "Rhynchospora fusca (L.) W.T.Aiton",
  "Ribes alpinum", "Ribes alpinum L.",
  "Ribes aureum", "Ribes aureum Pursh",
  "Ribes grossularia", "Ribes uva-crispa var. sativum DC.",
  "Ribes nigrum", "Ribes nigrum L.",
  "Riccia", "Riccia sp.",
  "Riccia fluitans", "Riccia fluitans L.",
  "Robinia pseudacacia", "Robinia pseudoacacia L.",
  "Roripa amphibia", "Rorippa amphibia (L.) Besser",
  "Roripa austriaca", "Rorippa austriaca (Crantz) Besser", 
  "Roripa austriaca X silvestre", "",
  "Roripa islandica", "Rorippa islandica (Oeder) Borbás",
  "Roripa prostrata (Bergeret) Schinz et Thell.", "Rorippa anceps (Wahlenb.) Rchb.",
  "Rosa agrestis", "Rosa agrestis Savi", 
  "Rosa canina X gallica", "Rosa canina x gallica",
  "Rosa cinnamomea", "Rosa cinnamomea Borrer ex Hook.",
  "Rosa coriifolia", "Rosa caesia Sm.",
  "Rosa elliptica", "Rosa inodora Fr.",
  "Rosa eutomentosa", "Rosa tomentosa Sm.",
  "Rosa gallica", "Rosa gallica L.", 
  "Rosa gallica x dumetorum", "", 
  "Rosa glauca", "Rosa glauca Pourr.",
  "Rosa hirtifolia (H. Br.) Schalow", "Rosa corymbifera Borkh.",
  "Rosa hispidula (Ripart) E. Schal.", "Rosa corymbifera Borkh.",
  "Rosa humilis", "Rosa gallica L.",
  "Rosa incana (Kit.) Schalow", "Rosa incana Kit. ex Tratt.",
  "Rosa inodora (Fries) Schalow", "Rosa inodora Fr.",
  "Rosa Jundzillii", "Rosa marginata Wallr.",
  "Rosa obtusifolia (Desv.) Schalow", "Rosa obtusifolia Desv.",
  "Rosa omissa", "Rosa sherardii Davies",
  "Rosa pendulina", "Rosa pendulina L.",
  "Rosa pendulina var. levis (Ser.) R. Keil.", "Rosa pendulina L.",
  "Rosa pendulina var. setosa (Gremii) R. Keil.", "Rosa pendulina L.",
  "Rosa pimpinellifolia", "Rosa pimpinellifolia Jacq.",
  "Rosa pomifera", "Rosa villosa L.",
  "Rosa rubiginosa", "Rosa rubiginosa L.",
  "Rosa rubrifolia", "Rosa rubrifolia R.Br.",
  "Rosa rugosa", "Rosa rugosa Thunb.",
  "Rosa scabriuscula", "Rosa sherardii Davies",
  "Rosa silesiaca", "Rosa agrestis Savi", 
  "Rosa silesiaca Nimptsch", "Rosa agrestis Savi", 
  "Rosa silesiaca f. inopinata mh. f. nov.", "Rosa agrestis Savi", 
  "Rosa subcanina", "Rosa subcanina (Christ) Dalla Torre & Sarnth.",
  "Rosa subcanina Hayeck", "Rosa dumalis Bechst.",
  "Rubus caesius", "Rubus caesius L.",
  "Rubus odoratus", "Rubus odoratus L.",
  "Rubus salisburgensis", "Rubus salisburgensis Focke",
  "Rubus saxatilis", "Rubus saxatilis L.",
  "Rudbeckia hirta", "Rudbeckia hirta L.",
  "Rudbeckia laciniata", "Rudbeckia laciniata L.", 
  "Rudbekia laciniata", "Rudbeckia laciniata L.", 
  "Rumex acetosella f. ramosissima", "Rumex acetosella L.",
  "Rumex acetoselia f. ramosissima mh. f. nov.", "Rumex acetosella L.",
  "Rumex alpinus", "Rumex alpinus L.",
  "Rumex aquaticus", "Rumex aquaticus L.",
  "Rumex aquaticus x obtusifolius", "",
  "Rumex bacephalophorus", "Rumex bucephalophorus L.",
  "Rumex bucephalophorus L.", "Rumex bucephalophorus L.",
  "Rumex Hydrolapathum", "Rumex hydrolapathum (Scop.) Huds.",
  "Rumex maritimus", "Rumex maritimus L.",
  "Rumex maximus", "Rumex hydrolapathum (Scop.) Huds.",
  "Rumex pulcher L.", "Rumex pulcher L.",
  "Rumex salicifolius Weinm.", "Rumex salicifolius Weinm.",
  "Sagina apetala", "Sagina apetala Ard.",
  "Sagina Linnaei", "Sagina saginoides (L.) Karst.",
  "Sagina nodosa", "Sagina nodosa (L.) Fenzl", 
  "Salix acutifolia", "Salix acutifolia Willd.",
  "Salix aurita", "Salix aurita L.", 
  "Salix aurita-cinerea", "", 
  "Salix aurita-livida", "", 
  "Salix aurita-purpurea", "Salix aurita × purpurea", 
  "Salix cinerea-purpurea", "Salix cinerea × purpurea",
  "Salix cinerea-viminalis", "Salix ×holosericea Willd.", 
  "Salix daphnoides", "Salix daphnoides Vill.",
  "Salix dasyclados", "Salix ×dasyclados Wimm.", 
  "Salix fragilis-pentandra", "Salix fragilis x pentandra",
  "Salix hastata-silesiaca", "", 
  "Salix nigricans", "Salix myrsinifolia Salisb.",
  "Salix nigricans-repens", "", 
  "Salix pentandra", "Salix pentandra L.",
  "Salix pruinosa Wendl.", "Salix acutifolia Willd.",
  "Salix purpurea-repens", "Salix purpurea x repens",
  "Salix repens", "Salix repens L.",
  "Salix repens var. rosmarinifolia", "Salix rosmarinifolia L.",
  "Salix silesiaca-Lapponum", "", 
  "Salix silesiaca-caprea", "", 
  "Salix viminalis-aurita f. glabrata", "", 
  "Salsola kali", "Kali turgidum (Dumort.) Gutermann",
  "Salsola Kali", "Kali turgidum (Dumort.) Gutermann",
  "Salvia glutinosa", "Salvia glutinosa L.",
  "Salvia nemorosa", "Salvia nemorosa L.",
  "Salvia pratensis", "Salvia pratensis L.", 
  "Salvia pratensis f. rostrata", "Salvia pratensis subsp. pratensis",
  "Salvia verticillata", "Salvia verticillata L.",
  "Salvia viridis var. horminum", "Salvia viridis L.",
  "Salvia viridis var. Horminum", "Salvia viridis L.",
  "Salvinia natans", "Salvinia natans (L.) All.",
  "Sambucus ebulus", "Sambucus ebulus L.",
  "Sambucus Ebulus", "Sambucus ebulus L.",
  "Sambucus nigra var. laciniata L.", "Sambucus nigra var. laciniata L.",
  "Sambucus racemosa", "Sambucus racemosa L.", 
  "Sambucus racemosa f. laciniata", "Sambucus racemosa var. laciniata A.Gray, 1884",
  "Sambucus racemosa var. laciniata", "Sambucus racemosa var. laciniata A.Gray, 1884",
  "Sanguisorba minor", "Poterium sanguisorba subsp. sanguisorba L.",
  "Sanicula europaea", "Sanicula europaea L.", 
  "Santolina Chamaecyparissus L.", "Santolina chamaecyparissus L.",
  "Saponaria ocymoides L.", "Saponaria ocymoides L.",
  "Saponaria officinalis", "Saponaria officinalis L.",
  "Sarothamnus scoparius", "Cytisus scoparius (L.) Link",
  "Satureja acinos", "Clinopodium acinos (L.) Kuntze",
  "Satureja hortensis", "Satureja hortensis L.",
  "Saxifraga granulata f. stenoloba f. nov.", "Saxifraga granulata L.",
  "Saxifraga tridactylites", "Saxifraga tridactylites L.",
  "Scabiosa canescens", "Scabiosa canescens Waldst. & Kit.", 
  "Scabiosa Columbaria", "Scabiosa columbaria L.",
  "Scandix pecten Veneris", "Scandix pecten-veneris L.",
  "Scheuchzeria palustris", "Scheuchzeria palustris L.",
  "Scilla bifolia", "Scilla bifolia L.",
  "Scirpus acicularis", "Scirpus acicularis Willd. ex Kunth",
  "Scirpus holoschoenus", "Scirpoides holoschoenus (L.) Soják",
  "Scirpus lacustris", "Schoenoplectus lacustris (L.) Palla",
  "Scirpus maritimus", "Bolboschoenus maritimus (L.) Palla", 
  "Scirpus mucronatus", "Schoenoplectiella mucronata (L.) J.Jung & H.K.Choi",
  "Scirpus ovatus", "Eleocharis ovata (Roth) Roem. & Schult.",
  "Scirpus pauciflorus", "Eleocharis quinqueflora (Hartmann) O.Schwarz", 
  "Scirpus radicans", "Scirpus radicans Schkuhr",
  "Scirpus radicans X silvaticus", "",
  "Scirpus tabernaemontani", "Schoenoplectus tabernaemontani (C.C.Gmel.) Palla",
  "Scirpus Tabernaemontani", "Schoenoplectus tabernaemontani (C.C.Gmel.) Palla",
  "Scleranthus annuus X perennis", "Scleranthus annuus × perennis", 
  "Scleropoa rigida", "Catapodium rigidum (L.) C.E.Hubb.",
  "Scleropoa rigida Griseb.", "Catapodium rigidum (L.) C.E.Hubb.",
  "Scolymus hispanicus L.", "Scolymus hispanicus L.",
  "Scorzonera humilis", "Scorzonera humilis L.",
  "Scorzonera purpurea", "Scorzonera purpurea L.",
  "Scrofularia alata", "Scrophularia alata A.Gray", 
  "Scutellaria hastifolia", "Scutellaria hastifolia L.",
  "Secale cereale", "Secale cereale L.", 
  "Sedum album", "Sedum album L.",
  "Sedum reflexum", "Petrosedum rupestre subsp. rupestre", 
  "Sedum spurium", "Sedum spurium Sibth. ex Nyman, 1879",
  "Sedum villosum", "Sedum villosum L.",
  "Selaginella apoda", "Selaginella apoda (L.) Spring",
  "Selaginella selaginoides", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.",
  "Selaginella spiculosa", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.", 
  "Selaginella spinulosa", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.",            
  "Selaginella spinulosa A. Br.", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.", 
  "Sempervivum soboliferum", "Sempervivum globiferum subsp. globiferum",
  "Senecio barbaraeifolius", "Jacobaea erratica (Bertol.) Fourr.",
  "Senecio crispatus", "Tephroseris crispa (Jacq.) Schur",
  "Senecio fluviatilis", "Senecio sarracenicus L.",
  "Senecio fuchsi", "Senecio ovatus subsp. ovatus (G.Gaertn., B.Mey. & Scherb.) Hoppe",
  "Senecio Jacobaea var. erucoides", "Jacobaea vulgaris Gaertn.", 
  "Senecio Jacobaea var. erucoides D. C.", "Jacobaea vulgaris Gaertn.", 
  "Senecio nemorensis", "Senecio nemorensis L.",
  "Senecio vernalis", "Senecio vernalis Waldst. & Kit.", 
  "Serratula tinctoria var. pinnata Kit.", "Serratula tinctoria L.",
  "Seseli coloratum", "Seseli annuum subsp. annuum", 
  "Setaria ambigua Guss.", "Setaria verticillata (L.) P.Beauv.",
  "Setaria italica", "Setaria italica (L.) P.Beauv.",
  "Setaria Italica var. maxima Alef", "Setaria italica (L.) P.Beauv.",
  "Setaria viridis f. fallax Bruhin", "Setaria viridis (L.) P.Beauv.",
  "Sideritis montana", "Sideritis montana L.",
  "Silene armeria", "Atocion armeria (L.) Fourr.",
  "Silene coeli rosa", "Eudianthe coeli-rosa (L.) Endl.", 
  "Silene coeli rosa (L.) A. Br.", "Eudianthe coeli-rosa (L.) Endl.", 
  "Silene conica", "Silene conica L.",
  "Silene dichotoma", "Silene dichotoma Ehrh.",
  "Silene gallica", "Silene gallica L.",
  "Silene gallica var. anglica L.", "Silene gallica L.",
  "Silene nutans f. glabra", "Silene nutans subsp. nutans",
  "Silene otites", "Silene otites (L.) Wibel", 
  "Silene Otites", "Silene otites (L.) Wibel", 
  "Silene pendula", "Silene pendula L.",
  "Silybum marianum", "Silybum marianum (L.) Gaertn.",
  "Silybum Marianum", "Silybum marianum (L.) Gaertn.",
  "Sinapis alba", "Sinapis alba L.",
  "Sinapis alba f. glabrata", "Sinapis alba subsp. dissecta (Lag.) Simonk.",
  "Sisymbrium orientale", "Sisymbrium orientale L.",
  "Sisymbrium sinapistrum", "Sisymbrium altissimum L.",
  "Sisymbrium Sinapistrum", "Sisymbrium altissimum L.", 
  "Sisymbrium Sophia", "Descurainia sophia (L.) Webb ex Prantl",
  "Sisymbrium Wolgense", "Sisymbrium volgense M.Bieb. ex E.Fourn.",
  "Sisymbrium Wolgense M. Bieb.", "Sisymbrium volgense M.Bieb. ex E.Fourn.",
  "Sisyrinchium angustufolium", "Sisyrinchium angustifolium Mill.",
  "Solanum Lycopersicum", "Solanum lycopersicum L.",
  "Solanum rostratum", "Solanum angustifolium Houst. ex Mill.",
  "Solanum sarachoides Sendtner", "Solanum sarrachoides Sendtn.",
  "Solanum sisymbrifolium Lam.", "Solanum sisymbriifolium Lam.",
  "Solanum sodomaeum L.", "Solanum anguivi Lam.",
  "Solanum villosum", "Solanum villosum Mill.",
  "Solanum villosum var. alatum", "Solanum alatum Moench",
  "Solidago canadensis", "Solidago canadensis L.",
  "Solidago gigantea Aiton", "Solidago gigantea Aiton",
  "Solidago serotina", "Solidago serotina Retz., 1781",
  "Sonchus arvensis f. uliginosus", "Sonchus arvensis subsp. uliginosus (M.Bieb.) Nyman",
  "Sorbaria sorbifolia", "Sorbaria sorbifolia (L.) A.Braun",
  "Sparganium diversifolium", "Sparganium diversifolium Asch.",
  "Sparganium minimum", "Sparganium minimum Hill, 1756",
  "Sparganium natans", "Sparganium natans L.",
  "Sparganium ramosum", "Sparganium erectum L.",
  "Sparganium simplex", "Sparganium emersum Rehmann",
  "Specularia Speculum", "Legousia speculum-veneris (L.) Chaix",
  "Specularia speculum", "Legousia speculum-veneris (L.) Chaix",
  "Spinacia oleracea", "Spinacia oleracea L.",
  "Spiraea chamaedryfolia", "Spiraea chamaedryfolia L.",
  "Spiraea chamaedrifolia", "Spiraea chamaedryfolia L.",
  "Spiraea obovata W. u. K.", "Spiraea hypericifolia subsp. obovata (Waldst. & Kit. ex Willd.) H.Huber",
  "Spiraea salicifolia", "Spiraea salicifolia L.",
  "Spiranthes spiralis", "Spiranthes spiralis (L.) Chevall.",
  "Stachys annua", "Stachys annua (L.) L.",
  "Stachys alpina f. ochroleucus Correns", "Stachys alpina L.",
  "Stachys arvensis", "Stachys arvensis (L.) L.",
  "Stachys grandiflora", "Betonica macrantha K.Koch",
  "Stachys recta", "Stachys recta L.", 
  "Stachys rectus", "Stachys recta L.", 
  "Stellaria friesiana", "Stellaria longifolia (Regel) Muhl. ex Willd.",
  "Stellaria media f. neglecta", "Stellaria neglecta (Lej.) Weihe", 
  "Stellaria nemorum", "Stellaria nemorum L.",
  "Stellaria pallida", "Stellaria apetala Bernardino",
  "Stenactis annua Nees", "Erigeron annuus (L.) Pers.",
  "Stratiotes aloides", "Stratiotes aloides L.", 
  "Stratiotes Aloides", "Stratiotes aloides L.", 
  "Streptopus amplexifolius", "treptopus amplexifolius (L.) DC.",
  "Struthiopteris germanica", "Matteuccia struthiopteris subsp. struthiopteris",
  "Sturmia Loeselii", "Liparis loeselii (L.) Rich.",
  "Suaeda maritima Dum.", "Suaeda maritima (L.) Dumort.",
  "Succisa pratensis f. incisa", "Succisa pratensis Moench",
  "Sweertia perennis var. flore sulphureo", "Swertia perennis L.", 
  "Symphytum asperum X officinale", "Symphytum ×uplandicum Nyman", 
  "Symphytum officinale f. bohemicum", "Symphytum bohemicum F.W.Schmidt",
  "Symphytum tuberosum", "Symphytum tuberosum L.", 
  "Symphoricarpus racemosus", "Symphoricarpos albus (L.) K.Koch",
  "Symphoricarpus racemosus Michx.", "Symphoricarpos albus (L.) K.Koch",
  "Taxus baccata", "Cephalotaxus harringtonii var. harringtonii",
  "Teesdalea nudicaulis", "Teesdalia nudicaulis (L.) W.T.Aiton",
  "Tetragonia expansa Murr.", "Tetragonia tetragonoides (Pall.) Kuntze",
  "Teucrium Botrys", "Teucrium botrys L.",
  "Teucrium scordium", "Teucrium scordium L.",
  "Teucrium Scordium", "Teucrium scordium L.",
  "Teucrium Scorodonia", "Teucrium scorodonia L.",
  "Thalictrum aquilegifolium", "Thalictrum aquilegiifolium L.",
  "Thalictrum flavum", "Thalictrum flavum L.", 
  "Thalictrum minus var. silvaticum", "Thalictrum minus subsp. minus L.",
  "Thalictrum simplex", "Thalictrum simplex L.", 
  "Thesium alpinum", "Thesium alpinum L.",
  "Thesium ebracteatum", "Thesium ebracteatum Hayne",
  "Thesium intermedium", "Thesium linophyllon L.", 
  "Thesium pratense", "Thesium pyrenaicum Pourr.",
  "Thladiantha dubia", "Thladiantha dubia Bunge",
  "Thladiantha dubia Bunge", "Thladiantha dubia Bunge",
  "Thlaspi alpestre", "Thlaspi alpestre Luce",
  "Thlaspi arvense", "Thlaspi arvense L.",
  "Thymus alpestris Tausch", "Thymus alpestris (Celak.) Tausch ex A.Kern.",
  "Thymus parviflorus Opiz", "Thymus pulegioides subsp. montanus (Trevir.) Ronniger", 
  "Thymus pulegioides L. var. Chamaedrys (Fries) Ronn.", "Thymus pulegioides L.", 
  "Thymus pulegioides L. var. gracilicaulis Ronn.", "Thymus pulegioides L.",
  "Thymus pulegioides L. var. ovatus (Mill.) Ronn.", "Thymus pulegioides L.",
  "Thymus pulegioides X serpyllum", "",
  "Thymus serpyllum L. em. Fries var. rigidus (Wimmer et Gr.) Ronn.", "Thymus serpyllum var. rigidus Wimmer & Grab.",
  "Thymus sudeticus Opiz", "Thymus pulcherrimus Schur",
  "Thysselinum", "",
  "Tilia alba Ait.", "Tilia tomentosa Moench",
  "Torilis arvensis (Huds.) Link ssp. heterophylla (Guss.) Thell.", "Torilis africana Spreng.",
  "Torilis arvensis ssp. heterophylla", "Torilis africana Spreng.",  
  "Torilis nodosa", "Torilis nodosa (L.) Gaertn.",
  "Torilis nodosa (L.) Gaertn.", "Torilis nodosa (L.) Gaertn.",
  "Trapa natans", "Trapa natans L.",
  "Tragopogon glaber (L.) Benth. et. Hook.", "Geropogon hybridus (L.) Sch.Bip.",
  "Tragopogon major", "Tragopogon dubius subsp. dubius",
  "Tragopogon orientalis", "Tragopogon orientalis L.",
  "Tragopogon pratensis", "Tragopogon pratensis L.",
  "Tragopogon pratensis f. tortilis G. F. W. Meyer", "Tragopogon pratensis L.",
  "Trientalis europaea", "Lysimachia europaea (L.) U.Manns & Anderb.",
  "Trientalis europaeus", "Lysimachia europaea (L.) U.Manns & Anderb.",
  "Trifolium alpestre", "Trifolium alpestre L.",
  "Trifolium echinatum Bieb. ssp. constantinopolitanum (Ser.) Gibelli et Belli", "", 
  "Trifolium fragiferum", "Trifolium fragiferum L.",
  "Trifolium glomeratum L. var. minus Rouy", "", 
  "Trifolium hybridum", "Trifolium hybridum L.",
  "Trifolium lappaceum L.", "Trifolium lappaceum L.", 
  "Trifolium ochroleucum", "Trifolium ochroleucon subsp. ochroleucon",
  "Trifolium resupinatum", "Trifolium resupinatum L.",
  "Trifolium rubens", "Trifolium rubens L.",
  "Trifolium spadiceum", "Trifolium spadiceum L.",
  "Triglochin maritima", "Triglochin maritima L.",
  "Triglochin palustris", "Triglochin palustris L.", 
  "Triticum durum", "Triticum turgidum subsp. durum (Desf.) Husn.",
  "Triticum durum Desf.", "Triticum turgidum subsp. durum (Desf.) Husn.",
  "Trollius europaeus", "Trollius europaeus L.",
  "Tropaeolum majus", "Tropaeolum majus L.",
  "Tulipa silvestris", "Tulipa sylvestris L.",
  "Turritis glabra", "Turritis glabra L.",
  "Typha angustifolia", "Typha angustifolia L.",
  "Typha latifolia", "Typha latifolia L.",
  "Ulex europaeus", "Ulex europaeus L.",
  "Ulmaria filipendula", "Filipendula vulgaris Moench",
  "Ulmaria Filipendula", "Filipendula vulgaris Moench",
  "Ulmus campestris var. suberosa", "Ulmus minor subsp. minor",
  "Ulmus montana", "Ulmus glabra Huds.",
  "Ulmus pedunculata", "Ulmus laevis Pall.",
  "Urtica dioeca f. angustifolia", "Urtica angustifolia Fisch. ex Hornem.",
  "Urtica dioeca f. subinermis", "Urtica subinermis (R.Uechtr.) Thomé ex Hand & Buttler",
  "Utricularia intermedia", "Utricularia intermedia Hayne",
  "Utricularia minor", "Utricularia minor L.",
  "Utricularia neglecta", "Utricularia ×neglecta Lehm.",
  "Utricularia vulgaris", "Utricularia vulgaris L.",
  "Vaccaria parviflora", "Gypsophila vaccaria (L.) Sm.",
  "Vaccinium myrtillus X Vaccinium vitis-idaea", "Vaccinium ×intermedium Ruthe",
  "Vaccinium oxycoccus", "Vaccinium oxycoccos L.",
  "Vaccinium Oxycoccus", "Vaccinium oxycoccos L.",
  "Vaccinium uliginosum", "Vaccinium uliginosum L.",
  "Valeriana dioeca", "Valeriana dioica L.",
  "Valeriana exaltata", "Valeriana officinalis L.",
  "Valeriana officinalis f. exaltata", "Valeriana officinalis L.",
  "Valeriana polygama", "Valeriana elongata Jacq.",
  "Valeriana sambucifolia", "Valeriana sambucifolia J.C.Mikan ex Pohl",
  "Valerianella carinata", "Valeriana carinata (Loisel.) Christenh. & Byng",
  "Valerianella coronata D. C.", "Valerianella coronata (L.) DC.",
  "Valerianella eriocarpa", "Valerianella eriocarpa Desv.",
  "Valerianella eriocarpa Desv.", "Valerianella eriocarpa Desv.",
  "Valerianella rimosa", "Valerianella rimosa Bastard",
  "Veratrum album", "Veratrum album L.",
  "Veratrum album var. lobelianum", "Veratrum lobelianum Bernh.",
  "Verbascum blattaria", "Verbascum blattaria L.", 
  "Verbascum Lychnitis", "Verbascum lychnitis L.",
  "Verbascum phlomoides", "Verbascum phlomoides L.",
  "Verbascum phoeniceum", "Verbascum phoeniceum L.",
  "Verbascum Thapsus", "Verbascum thapsus L.",
  "Verbascum thapsiforme x thapsus", "",
  "Verbena venosa Gill. et Hook.", "Verbena rigida Spreng.",
  "Veronica anagallis", "Veronica anagallis L.",
  "Veronica longifolia", "Veronica longifolia L.",
  "Veronica scutellata", "Veronica scutellata L.",
  "Veronica spicata", "Veronica spicata L.",
  "Veronica teucrium", "Veronica teucrium L.",
  "Vicia cassubica", "Vicia cassubica L.",
  "Vicia cracca var. alpestris Čel.", "",
  "Vicia dumetorum", "Vicia dumetorum L.",
  "Vicia Ervilia (L.) Willd.", "Vicia ervilia (L.) Willd.", 
  "Vicia Faba", "Vicia faba L.",
  "Vicia grandiflora", "Vicia grandiflora Scop.",
  "Vicia lathyroides", "Vicia lathyroides L.",
  "Vicia lutea L. f. caerulea Arcang.", "Vicia lutea L.", 
  "Vicia melanops Sibth. et Sm.", "Vicia melanops Sm.",
  "Vicia pannonica", "Vicia pannonica Crantz",
  "Vicia Panononica", "Vicia pannonica Crantz",
  "Vicia pannonica f. purpurascens", "Vicia pannonica Crantz",
  "Vicia Panononica f. purpurascens", "Vicia pannonica Crantz",
  "Vicia pannonica var. typica", "Vicia pannonica Crantz",
  "Vicia pisiformis", "Vicia pisiformis L.", 
  "Vicia sepium f. ochroleuca", "Vicia sepium L.",
  "Vicia silvatica", "Vicia sylvatica L.",
  "Vicia tenuifolia", "Vicia tenuifolia Roth",
  "Vicia villosa", "Vicia villosa Roth",
  "Vicia villosa ssp. varia", "Vicia villosa Roth",
  "Vinca minor", "Vinca minor L.", 
  "Vincetoxicum officinale", "Vincetoxicum hirundinaria Medik.",
  "Viola arvensis", "Viola arvensis Murray",
  "Viola canina X Viola persicifolia", "", 
  "Viola canina X Viola riviniana", "Viola canina x riviniana",
  "Viola canina X Riviniana", "Viola canina x riviniana",
  "Viola elatior", "Viola elatior Fr.", 
  "Viola elatior Fries", "Viola elatior Fr.", 
  "Viola elatior f . humilis Uechtritz", "",
  "Viola elatior x pumila", "Viola elatior x pumila",
  "Viola epipsila", "Viola epipsila Ledeb.", 
  "Viola hirta", "Viola hirta L.", 
  "Viola montana L.", "Viola ruppii All.",
  "Viola montana x riviniana", "Viola riviniana x ruppii", 
  "Viola mirabilis", "Viola mirabilis L.", 
  "Viola palustris", "Viola palustris L.", 
  "Viola persicifolia", "Viola stagnina Kit.",
  "Viola persicifolia Roth", "Viola stagnina Kit.",
  "Viola persicifolia x canina", "",
  "Viola Riviniana X rupestris", "Viola riviniana x rupestris",
  "Viola rupestris Schmidt var. glaberrima Murb.", "Viola rupestris subsp. glaberrima (Murb.) Vl.V.Nikitin",
  "Viola rupestris var. glaberrima", "Viola rupestris subsp. glaberrima (Murb.) Vl.V.Nikitin",
  "Viola silvestris", "Viola reichenbachiana Jord. ex Boreau",
  "Viola tricolor", "Viola tricolor L.",
  "Viola tricolor f. saxatilis", "Viola tricolor subsp. alpestris (Ging.) Ces.",
  "Viscum album", "Viscum album L.",
  "Viscum album var. laxum", "Viscum laxum Boiss. & Reut.",
  "Vulpia ciliata", "Festuca ciliata Pers.",
  "Vulpia ciliata (Danth.) Link", "Festuca ciliata Pers.",
  "Xanthium italicum", "Xanthium orientale var. italicum (Moretti) M.Hassl.",
  "Xanthium spinosum", "Xanthium spinosum L.",
  "Xanthium strumarium", "Xanthium strumarium L.",
  "Xeranthemum annuum", "Xeranthemum annuum L.",
  "Zannichellia palustris", "Zannichellia palustris L.",
  "Zea mays", "Zea mays L.",
  "Zygophyllum Fabago L.", "Zygophyllum fabago L."
)

an <- matrix(unlist(an), nrow=length(an)/2, byrow=TRUE) |>
  as.data.frame()
names(an) <- c("species", "accepted_name")

# an <- an |>  
#   unique() |>
#   dplyr::arrange(species)
#   
# message(
#   paste0("\"", an[, 1], "\", \"", an[,2], "\", \n")
# )

m <- jahres |>
  subset(select = "species") |>
  dplyr::left_join(an, by = "species") |>
  unique() |>
#  subset(is.na(accepted_name) | accepted_name == "") |>
  subset(is.na(accepted_name)) |>
  dplyr::arrange(species) 
# |>
#  as.matrix()

print(m)

