an <- c(
  "Abutilon avicennae", "Abutilon theophrasti Medik.",
  "Acer campestre", "Acer campestre L.", 
  "Acer tataricum", "Acer tataricum L.",
  "Adonis aestivalis", "Adonis aestivalis L.",
  "Agrimonia odorata", "Agrimonia repens L.",
  "Agrostemma githago f. latisecta f. nov.", "Agrostemma githago L.",
  "Ailanthus glandulosa Desf.", "Ailanthus altissima (Mill.) Swingle", 
  "Aira caryophyllea", "Aira caryophyllea L.", 
  "Allium senescens", "Allium senescens L.",
  "Allium sibiricum", "Allium schoenoprasum L.",
  "Allium ursinum", "Allium ursinum L.",
  "Allium victorialis", "Allium victorialis L.",
  "Alyssum argenteum", "Odontarrhena argentea (All.) Ledeb.",
  "Amarantus albus", "Amaranthus albus L.",
  "Amarantus angustifolius Lam.", "Amaranthus graecizans L.",
  "Amarantus angustifolius var. graecizans (L.) Thell.", "Amaranthus graecizans L.",
  "Amarantus cruentus var.paniculatus","Amaranthus cruentus L.",
  "Amarantus hypochondriacus var. chlorostachys", "Amaranthus hypochondriacus L.",
  "Andropogon halepensis f . muticus Hackel", "Sorghum halepense (L.) Pers.",
  "Androsace septentrionalis", "Androsace septentrionalis L.",  
  "Anemone pratensis", "Pulsatilla pratensis subsp. pratensis ", 
  "Antennaria margaritacea", "Antennaria margaritacea R.Br., 1817",
  "Anthemis tinctoria", "Cota tinctoria subsp. tinctoria", 
  "Anthericum ramosum", "Anthericum ramosum L.",
  "Anthoxanthum aristatum", "Anthoxanthum aristatum Boiss.",
  "Anthriscus nitida", "Anthriscus nitidus (Wahlenb.) Hazsl.",
  "Antirrhinum orontium", "Misopates orontium subsp. orontium (Linnaeus) Rafinesque",
  "Arabis hirsuta", "Arabis hirsuta (L.) Scop.",
  "Archangelica officinalis", "Angelica archangelica subsp. archangelica", 
  "Arnica montana", "Arnica montana L.",
  "Aristolochia clematitis", "Aristolochia clematitis L.",
  "Armeria vulgaris", "Armeria maritima subsp. elongata (Hoffm.) Bonnier",
  "Arrhenatherum elatius f. biaristatum", "Arrhenatherum elatius (L.) P.Beauv. ex J.Presl & C.Presl",
  "Artemisia annua", "Artemisia annua L.", 
  "Artemisia campestris", "Artemisia campestris L.", 
  "Artemisia pontica", "Artemisia pontica L.",
  "Asperugo procumbens", "Asperugo procumbens L.",
  "Asperula aparine", "Galium aparine L.", 
  "Asperula odorata", "Galium odoratum (L.) Scop.", 
  "Aspidium dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Aspidium Dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Aspidium filix mas var. deorsolobatum", "",
  "Aspidium lonchitis (L.) Sw.", "Polystichum lonchitis (L.) Roth", 
  "Aspidium montanum (Vogler) Aschs.", "Oreopteris limbosperma (All.) Holub", 
  "Aspidium phegopteris", "Phegopteris connectilis (Michx.) Watt", 
  "Aspidium Phegopteris", "Phegopteris connectilis (Michx.) Watt", 
  "Aspidium robertianum", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Aspidium Robertianum", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Aspidium spinulosum", "Dryopteris carthusiana (Vill.) H.P.Fuchs", 
  "Aspidium tanacetifolium", "Dryopteris dilatata subsp. dilatata", 
  "Aspidium thelypteris", "Thelypteris palustris subsp. palustris", 
  "Aspidium Thelypteris", "Thelypteris palustris subsp. palustris", 
  "Aspidium thelypteris (L.) Sw.", "Thelypteris palustris subsp. palustris", 
  "Asplenium fllix femina", "Athyrium filix-femina (L.) Roth", 
  "Asplenium germanicum Weis.", "Asplenium ruta-muraria subsp. ruta-muraria", 
  "Asplenium ruta-muraria", "Asplenium ruta-muraria L.", 
  "Asplenium Ruta muraria", "Asplenium ruta-muraria L.", 
  "Asplenium septentrionale", "Asplenium septentrionale (L.) Hoffm.", 
  "Asplenium trichomanes L.", "Asplenium trichomanes L.", 
  "Asplenium viride", "Asplenium viride Huds.", 
  "Asplenium viride Huds.", "Asplenium viride Huds.", 
  "Asplenium viride ssp. adulterinum", "Asplenium adulterinum Milde", 
  "Aster novi-belgii", "Symphyotrichum novi-belgii (L.) G.L.Nesom", 
  "Aster salignus", "Aster salignus L.", 
  "Astragalus arenarius", "Astragalus arenarius L.", 
  "Astragalus cicer", "Astragalus cicer L.",
  "Astrantia major", "Astrantia major L.",
  "Atrichum tenellum", "Atrichum tenellum Bruch & W.P.Schimper, 1844", 
  "Atriplex hortense", "Atriplex hortensis L.",
  "Atriplex hortense f. ruberrimum", "Atriplex hortensis L.",
  "Atriplex nitens", "Atriplex sagittata Borkh.",
  "Avena sativa f . aristata Krause", "Avena sativa L.",
  "Barbaraea stricta", "Barbarea stricta Andrz. ex Besser",
  "Berberis vulgaris", "Berberis vulgaris L.",
  "Berteroa incana", "Berteroa incana (L.) DC.",
  "Berula", "Berula erecta (Huds.)",
  "Beta maritima L.", "Beta maritima L.", 
  "Betula pubescens x verrucosa", "", 
  "Bidens connatus", "Bidens connata Muhl. ex Willd.", 
  "Bidens melanocarpus", "Bidens frondosa L.", 
  "Blechnum spicant", "Struthiopteris spicant (L.) Weiss", 
  "Blechnum spicant (L.) Wth.", "Struthiopteris spicant (L.) Weiss", 
  "Borrago officinalis", "Borago officinalis L.", 
  "Botrychium lunaria", "Botrychium lunaria (L.) Sw.", 
  "Botrychium lunaria f. cristatum", "Botrychium lunaria (L.) Sw.",
  "Botrychium lunaria f. incisum", "Botrychium lunaria (L.) Sw.",
  "Botrychium lunaria var. subincisum Rüp.", "Botrychium lunaria (L.) Sw.",
  "Botrychium matricariae", "Sceptridium multifidum (S.G.Gmel.) Nishida ex Tagawa", 
  "Botrychium matricariaefolium", "Botrychium matricariifolium (Döll) A.Braun ex Koch", 
  "Botrychium matricarifolium", "Botrychium matricariifolium (Döll) A.Braun ex Koch", 
  "Botrychium rutaefolium A. Br.", "Sceptridium multifidum (S.G.Gmel.) Nishida ex Tagawa", 
  "Botrychium simplex Hitchcock", "Botrychium simplex E.Hitchc.", 
  "Botrychium ternatum Sw.", "Sceptridium ternatum (Thunb.) Lyon", 
  "Brassica juncea", "Brassica juncea (L.) Czern.",
  "Bromus asper", "Bromus ramosus Huds.", 
  "Bromus erectus", "Bromus erectus Huds.",
  "Bromus inermis", "Bromus inermis Leyss.",
  "Bromus racemosus", "Bromus racemosus L.",
  "Bromus sterilis", "Bromus sterilis L.",
  "Buphthalmum speciosum", "Telekia speciosa (Schreb.) Baumg.", 
  "Bupleurum tenuissimum", "Bupleurum tenuissimum L.", 
  "Butomus umbellatus", "Butomus umbellatus L.", 
  "Calendula officinalis", "Calendula officinalis L.", 
  "Calla palustris", "Calla palustris L.",
  "Camelina sativa", "Camelina sativa (L.) Crantz", 
  "Campanula patula", "Campanula patula L.", 
  "Campanula Rapunculus", "Campanula rapunculus L.", 
  "Campanula rotundifolia", "Campanula rotundifolia L.", 
  "Campanula trachelium var. calycibus complanatis", "Campanula trachelium L.", 
  "Cardamine amara", "Cardamine amara L.", 
  "Cardamine chelidonia L.", "Cardamine chelidonia L.", 
  "Carduus crispus", "Carduus crispus L.", 
  "Carex acuta x stricta", "", 
  "Carex brizoides", "Carex brizoides L.", 
  "Carex buekii", "Carex buekii Wimm.", 
  "Carex buxbaumi", "Carex buxbaumii Wahlenb.",
  "Carex buxbaumii", "Carex buxbaumii Wahlenb.", 
  "Carex caespitosa L. nach Fries.", "Carex cespitosa L.", 
  "Carex cyperoides", "Carex bohemica Schreb.",
  "Carex davalliana", "Carex davalliana Sm.", 
  "Carex davalliana Smith", "Carex davalliana Sm.", 
  "Carex disticha", "Carex disticha Huds.",
  "Carex evoluta Hartmann", "Carex ×evoluta Hartm.", 
  "Carex goodenoughi f. tornata", "Carex nigra subsp. nigra",
  "Carex goodenoughii x stricta", "",
  "Carex ligerica", "Carex colchica J.Gay",
  "Carex longifolia Host.", "Carex umbrosa subsp. umbrosa", 
  "Carex paradoxa", "Carex appropinquata Schumach.", 
  "Carex paradoxa var. gracilis Aschers, et Gr.", "Carex appropinquata Schumach.", 
  "Carex pendula", "Carex pendula Huds.",
  "Carex pilosa", "Carex pilosa Scop.", 
  "Carex pseudocyperus", "Carex pseudocyperus L.", 
  "Carex pulicaris", "Carex pulicaris L.", 
  "Carex riparia", "Carex riparia Curtis", 
  "Carex teretiuscula", "Carex teretiuscula Willd. ex Kunth, 1837",
  "Carex tomentosa", "Carex tomentosa L.",
  "Carlina acaulis", "Carlina acaulis L.", 
  "Carlina acaulis f. caulescens", "Carlina acaulis subsp. caulescens (Lam.) Schübl. & G.Martens", 
  "Centaurea phrygia", "Centaurea phrygia L.", 
  "Ceratophyllum demersum", "Ceratophyllum demersum L.",
  "Cerastium anomalum", "", 
  "Cerinthe minor", "Cerinthe minor L.", 
  "Chenopodium ficifolium", "Chenopodium ficifolium Sm.",
  "Chenopodium hircinum", "Chenopodium hircinum Schrad.",
  "Chenopodium opulifolium", "Chenopodium opulifolium Schrad.",
  "Chenopodium vulvaria", "Chenopodium vulvaria L.",
  "Chrysosplenium oppositifolium", "Chrysosplenium oppositifolium L.",
  "Cichorium intybus", "Cichorium intybus L.", 
  "Cicuta virosa", "Cicuta virosa L.", 
  "Circaea alpina", "Circaea alpina L.",
  "Circaea intermedia", "Circaea ×intermedia Ehrh.", 
  "Cirsium acaule", "Cirsium acaule (L.) All., 1780", 
  "Cirsium acaule-oleraceum", "Cirsium acaule × oleraceum", 
  "Cirsium arvense", "Cirsium arvense (L.) Scop.", 
  "Cirsium canum", "Cirsium canum (L.) All.", 
  "Cirsium canum-acaule", "", 
  "Cirsium heterophyllum", "Cirsium heterophyllum (L.) Hill", 
  "Cirsium lanceolatum-oleraceum", "", 
  "Cirsium rivulare", "Cirsium rivulare (Jacq.) All.", 
  "Coeloglossum viride", "Dactylorhiza viridis (L.) R.M.Bateman, Pridgeon & M.W.Chase",
  "Colchicum autumnale", "Colchicum autumnale L.", 
  "Conium maculatum", "Conium maculatum L.", 
  "Convallaria majalis", "Convallaria majalis L.", 
  "Convolvulus dahuricus", "Calystegia pulchra Brumm. & Heywood",
  "Cosmos bipinnatus", "Cosmos bipinnatus Cav.", 
  "Cotoneaster integerrimus", "Cotoneaster integerrimus Medik.",
  "Crepis biennis", "Crepis biennis L.", 
  "Crocus vernus", "Crocus vernus (L.) Hill",
  "Crocus vernus Wulf.", "Crocus vernus (L.) Hill",
  "Cucumis melo L.", "Cucumis melo L.",
  "Cucubalus baccifer", "Silene baccifera (L.) Roth",
  "Cucurbita maxima Duch.", "Cucurbita maxima Duchesne", 
  "Cystopteris fragilis (L.) Beruh.", "Cystopteris fragilis (L.) Bernh.", 
  "Cystopteris sudetica", "Cystopteris sudetica A.Braun & Milde",
  "Cytisus elongatus", "",
  "Cytisus nigricans", "Cytisus nigricans L.",
  "Dahlia variabilis", "Dahlia variabilis Hort.", 
  "Daphne mezereum", "Daphne mezereum L.",
  "Datura stramonium", "Datura stramonium L.", 
  "Delphinium ajacis", "Delphinium ajacis L.",
  "Dentaria bulbifera", "Cardamine bulbifera (L.) Crantz",
  "Dentaria enneaphyllos", "Cardamine enneaphyllos (L.) Crantz",
  "Dianthus barbatus", "Dianthus barbatus L.",
  "Dianthus carthusianorum", "Dianthus carthusianorum L.", 
  "Dianthus superbus", "Dianthus superbus L.",
  "Digitalis purpurea", "Digitalis purpurea L.", 
  "Diplotaxis muralis", "Diplotaxis muralis (L.) DC.",
  "Dipsacus silvester", "Dipsacus fullonum L.", 
  "Drosera rotundifolia", "Drosera rotundifolia L.", 
  "Echinops sphaerocephalus", "Echinops sphaerocephalus L.", 
  "Elatine alsinastrum L.", "Elatine alsinastrum L.", 
  "Elatine hexandra", "Elatine hexandra (Lapierre) DC.",
  "Elatine hydropiper", "Elatine hydropiper L.",
  "Epilobium adnatum", "Epilobium tetragonum L.",
  "Epilobium hirsutum x montanum", "Epilobium hirsutum × montanum ",
  "Epilobium lamyi", "Epilobium lamyi F.W.Schultz", 
  "Epilobium obscurum", "Epilobium obscurum Schreb.", 
  "Epilobium palustre f. glandulosum", "Epilobium palustre L.",
  "Epilobium parviflorum", "Epilobium parviflorum Schreb.", 
  "Epilobium parviflorum x roseum", "Epilobium parviflorum x roseum", 
  "Equisetum Telmateia Ehrh", "Equisetum telmateia Ehrh.", 
  "Equisetum arvense", "Equisetum arvense L.", 
  "Equisetum arvense L. var. boreale (Rup.) f. normalis", "Equisetum arvense L.", 
  "Equisetum arvense L. var. campestre (C.F. Schultz)", "Equisetum arvense L.", 
  "Equisetum arvense L. var. nemorosum A. Br.", "Equisetum arvense L.", 
  "Equisetum arvense f. campestre", "Equisetum arvense L.", 
  "Equisetum arvense f. irriguum", "Equisetum arvense L.", 
  "Equisetum arvense var. serotinum G. F. W. Mey.", "Equisetum arvense L.", 
  "Equisetum arvense x limosum", "", 
  "Equisetum hiemale", "Equisetum hyemale L.", 
  "Equisetum limosum", "Equisetum fluviatile L.", 
  "Equisetum limosum L. (erw.) var. attenuatum Milde", "Equisetum fluviatile L.", 
  "Equisetum limosum L. var. uliginosum (Mhbg.)", "Equisetum fluviatile L.", 
  "Equisetum limosum L. var. verticillatum Döll f. ramosissima Baenitz.", "Equisetum fluviatile L.", 
  "Equisetum limosum a. linnaeanum Döll.", "Equisetum fluviatile L.", 
  "Equisetum limosum v. uliginosum", "Equisetum fluviatile L.", 
  "Equisetum limosum var. uliginosum", "Equisetum fluviatile L.", 
  "Equisetum limosum var. uliginosum Mühlbg.", "Equisetum fluviatile L.", 
  "Equisetum litorale", "Equisetum ×litorale Kühlew. ex Rupr.", 
  "Equisetum litorale Kühl.", "Equisetum ×litorale Kühlew. ex Rupr.", 
  "Equisetum maximum", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum Lmk. var. serotinum A. Br.", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum f. serotinum", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum v. breve Milde", "Equisetum telmateia Ehrh.", 
  "Equisetum maximum v. gracile", "Equisetum telmateia Ehrh.", 
  "Equisetum palustre", "Equisetum palustre L.", 
  "Equisetum palustre L. var. arcuatum Milde", "Equisetum palustre L.", 
  "Equisetum palustre f. arcuatum", "Equisetum palustre L.", 
  "Equisetum palustre f. polystachium", "Equisetum palustre L.", 
  "Equisetum pratense", "Equisetum pratense Ehrh.", 
  "Equisetum ramosissimum", "Equisetum ramosissimum Desf.", 
  "Equisetum silvaticum", "Equisetum sylvaticum L.", 
  "Equisetum telmateja Ehrh.", "Equisetum telmateia Ehrh.", 
  "Equisetum variegatum", "Equisetum variegatum Schleich.", 
  "Erica tetralix", "Erica tetralix L.", 
  "Eriophorum gracile Koch.", "Eriophorum gracile W.D.J.Koch", 
  "Eriophorum vaginatum", "Eriophorum vaginatum L.",
  "Eruca sativa", "Eruca sativa Hill",
  "Eupatorium cannabinum", "Eupatorium cannabinum L.", 
  "Euphorbia dulcis", "Euphorbia dulcis L.", 
  "Euphorbia lathyris", "Euphorbia lathyris L.",
  "Euphorbia platyphylla", "Euphorbia platyphyllos L.",
  "Falcaria vulgaris", "Falcaria vulgaris Bernh.", 
  "Festuca elatior var.pseudololiacea", "Lolium arundinaceum subsp. arundinaceum",
  "Festuca myurus", "Festuca myuros L.",
  "Ficus carica", "Ficus carica L.",
  "Flieracium tauschii Zahn", "", 
  "Fragaria collina x vesca", "",
  "Gagea arvensis", "Gagea arvensis Kar. & Kir. ex Ledeb.", 
  "Gagea minima", "Gagea minima (L.) Ker Gawl.",
  "Gagea pratensis", "Gagea pratensis (Pers.) Dumort.", 
  "Galega officinalis", "Galega officinalis L.",
  "Galinsoga parviflora", "Galinsoga parviflora Cav.", 
  "Galinsoga quadriradiata", "Galinsoga quadriradiata Ruiz & Pav.", 
  "Galium boreale", "Galium boreale L.", 
  "Galium tricorne", "Galium tricorne With., 1796", 
  "Geaster fornicatus Fries.", "Geastrum fornicatum (Huds.) Hook.", 
  "Genista pilosa", "Genista pilosa L.",
  "Gentiana verna", "Gentiana verna L.", 
  "Geranium columbinum", "Geranium columbinum L.",
  "Geranium molle", "Geranium molle L.",
  "Geranium phaeum", "Geranium phaeum L.",
  "Geranium pyrenaicum", "Geranium pyrenaicum Burm.f.",
  "Geranium pyrenaicum f. albiflorum", "Geranium pyrenaicum Burm.f.",
  "Geranium sanguineum", "Geranium sanguineum L.",
  "Geranium sibiricum", "Geranium sibiricum L.",
  "Geranium silvaticum", "Geranium sylvaticum L.",
  "Geranium silvaticum var. eglandulosum Cel.", "Geranium sylvaticum L.",
  "Geum rivale", "Geum rivale L.", 
  "Gladiolus imbricatus", "Gladiolus imbricatus L.",
  "Glaucium flavum", "Glaucium flavum Crantz",
  "Glyceria nemoralis", "Glyceria nemoralis (R.Uechtr.) R.Uechtr. & Koern.",
  "Glyceria plicata Fries", "Glyceria notata Chevall.", 
  "Glycine hispida (Mönch) Maxim.", "Glycine max subsp. max", 
  "Gnaphalium luteo-album", "Helichrysum luteoalbum (L.) Rchb.",
  "Gratiola officinalis", "Gratiola officinalis L.", 
  "Guizotia abyssinica", "Guizotia abyssinica (L.fil.) Cass.", 
  "Gymnadenia conopea var. densiflora", "Gymnadenia densiflora (Wahlenb.) A.Dietr.",
  "Gymnadenia conopea var. ornithis Beck", "Gymnadenia conopsea (L.) R.Br.",
  "Gypsophila elegans", "Gypsophila elegans M.Bieb.",
  "Gypsophila fastigiata", "Gypsophila fastigiata L.",
  "Gypsophila viscosa Murr.", "Gypsophila viscosa Murray",
  "Helenium autumnale L.", "Helenium autumnale L.",
  "Helianthus tuberosus", "Helianthus tuberosus L.", 
  "Helichrysum arenarium", "Helichrysum arenarium (L.) Moench", 
  "Helleborus viridis", "Helleborus viridis L.",
  "Hesperis matronalis", "Hesperis matronalis L.",
  "Hibiscus Tríonum", "Hibiscus trionum L.",
  "Heracleum sphondylium", "Heracleum sphondylium L.", 
  "Hieracium ambiguum Ehrh.", "Pilosella caespitosa subsp. caespitosa",
  "Hieracium aurantiacum", "Pilosella aurantiaca subsp. aurantiaca",
  "Hieracium bracchiatum Beck", "Pilosella acutifolia subsp. acutifolia",
  "Hieracium brachiatum Bertol.", "Pilosella acutifolia subsp. acutifolia",
  "Hieracium cernuiforme N. P.", "Hieracium cernuiforme N.P., 1885", 
  "Hieracium chaunanthes (N. P.) Zahn", "Pilosella rubra (Peter) Soják",
  "Hieracium cymoso-praealtum", "Pilosella piloselloides subsp. praealta (Gochnat) S.Bräut. & Greuter",
  "Hieracium cymosum", "Hieracium cymosum Willd., 1803", 
  "Hieracium cymosum ssp. pulveratum", "Pilosella cymosa subsp. cymosa (L.) F.W.Schultz & Sch.Bip.",
  "Hieracium echioides", "Pilosella echioides subsp. echioides (Lumn.) F.W.Schultz & Sch.Bip.",
  "Hieracium fallacinum F. Schultz", "Pilosella fallacina (F.W.Schultz) F.W.Schultz",
  "Hieracium floribundum", "Pilosella floribunda (Wimm. & Grab.) Fr.",
  "Hieracium iseranum Uechtritz", "Pilosella iserana (Uechtr.) Soják",
  "Hieracium laschii (Gebr. Schultz) Zahn", "Pilosella cana (Peter) Gottschl.",
  "Hieracium levicaule Jord.", "Hieracium levicaule Jord.",
  "Hieracium levigatum", "Hieracium laevigatum Willd.",
  "Hieracium liptoviense Borb.", "Hieracium liptoviense Borbás",
  "Hieracium liptoviense ssp. Schalowii Zahn", "", 
  "Hieracium onosmoides Fr.", "Hieracium onosmoides Fr.",
  "Hieracium piloselloides", "Pilosella piloselloides subsp. piloselloides (Villars) Soják",
  "Hieracium praecox Schultz-Bip.", "Hieracium glaucinum subsp. glaucinum Jord.",
  "Hieracium pratense", "Pilosella caespitosa subsp. caespitosa",
  "Hieracium prussicum", "Pilosella prussica (Nägeli & Peter) Soják",
  "Hieracium prussicum N. P.", "Pilosella prussica (Nägeli & Peter) Soják",
  "Hieracium saxifragum Fr.", "Hieracium saxifragum Fr.",
  "Hieracium schultesii F. Schultz", "Pilosella schultesii (Sch.Bip.) F.W.Schultz & Sch.Bip.",
  "Hieracium stoloniflorum-collinum", "",
  "Hieracium tauschii", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium tauschii ssp. acrosciadium N. P.", "Pilosella densiflora (Tausch) Soják",
  "Hieracium tauschii Zahn", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium Tauschii", "Pilosella densiflora (Tausch) Soják", 
  "Hieracium tephrosoma (N. P.) Zahn", "Hieracium tephrosoma (Nägeli & Peter) Zahn",
  "Hieracium Wiesbaurianum Uechtr.", "Hieracium hypochoeroides subsp. wiesbaurianum (R.Uechtr.) Greuter",
  "Hieracium Zizianum Tausch", "Pilosella ziziana subsp. ziziana",
  "Hierochloa odorata", "Anthoxanthum nitens (Weber) Y.Schouten & Veldkamp", 
  "Holoschoenus vulgaris", "Scirpoides holoschoenus (L.) Soják",
  "Holosteum umbellatum", "Holosteum umbellatum L.",
  "Holosteum umbellatum f. heuffeli", "Holosteum umbellatum L.",
  "Hordeum europaeum", "Hordelymus europaeus (L.) Jess. ex Harz", 
  "Hydrocotyle vulgaris", "Hydrocotyle vulgaris L.", 
  "Hypericum hirsutum", "Hypericum hirsutum L.",
  "Hypochoeris glabra", "Hypochoeris glabra L.", 
  "Hypochoeris maculata", "Trommsdorffia maculata subsp. maculata", 
  "Hyssopus officinalis", "Hyssopus officinalis L.", 
  "Hyssopus officinalis f. albus Alefeld", "Hyssopus officinalis L.", 
  "Iberis Lagascana DC.", "Iberis carnosa subsp. lagascana (DC.) Mateo & Figuerola",
  "Illecebrum verticillatum", "Illecebrum verticillatum L.",
  "Impatiens parviflora", "Impatiens parviflora DC.",
  "Impatiens Roylei", "Impatiens glandulifera Royle",
  "Imperatoria ostruthium", "Imperatoria ostruthium L.", 
  "Inula salicina", "Inula salicina Pall.", 
  "Inula vulgaris", "Inula vulgaris Williams", 
  "Iris sibirica", "Iris sibirica L.",
  "Isoetes lacustris", "Isoetes lacustris L.", 
  "Isopyrum thalictroides", "Isopyrum thalictroides L.", 
  "Juncus alpinus Vill.", "Juncus alpinoarticulatus subsp. alpinoarticulatus Chaix", 
  "Juncus filiformis", "Juncus filiformis L.",
  "Juncus filiformis f. pusillus Fries", "Juncus filiformis L.",
  "Juncus supinus", "Juncus supinus Bicheno, 1819", 
  "Juncus tenageja", "Juncus tenageia Ehrh. ex L.fil.", 
  "Juncus Tanageia", "Juncus tenageia Ehrh. ex L.fil.", 
  "Juncus tenuis", "Juncus tenuis Willd.",
  "Kochia scoparia", "Bassia scoparia (L.) A.J.Scott",
  "Koeleria hispida (Savi) D. C.", "Rostraria hispida (Savi) Dogan", 
  "Lactuca scariola", "Lactuca serriola L.",
  "Lactuca virosa", "Lactuca virosa L.",
  "Laserpicium prutenicum", "Silphiodaucus prutenicus subsp. prutenicus",
  "Lamium galeobdolon", "Lamium galeobdolon (L.) L.", 
  "Lathyrus niger", "Lathyrus niger (L.) Bernh.",
  "Lathyrus Nissolia", "Lathyrus nissolia L.",
  "Lathyrus montanus", "Lathyrus linifolius (Reichard) Bässler",
  "Lathyrus odoratus", "Lathyrus odoratus L.",
  "Lathyrus silvester", "Lathyrus sylvestris L.",
  "Lathyrus sylvestris", "Lathyrus sylvestris L.", 
  "Lavatera thuringiaca", "Malva thuringiaca subsp. thuringiaca",
  "Lavatera trimestris", "Malva trimestris (L.) Salisb.",
  "Ledum palustre", "Rhododendron tomentosum subsp. tomentosum",
  "Leersia oryzoides", "Leersia oryzoides (L.) Sw.",
  "Lens esculenta", "Vicia lens (L.) Coss. & Germ.",
  "Leontodon taraxacum", "Taraxacum officinale Weber ex Wiggins", 
  "Lepidium densiflorum", "Lepidium densiflorum Schrad.",
  "Lepidium draba", "Lepidium draba L.",
  "Lepidium Draba", "Lepidium draba L.",
  "Lepidium ruderale", "Lepidium ruderale L.",
  "Lepidium sativum", "Lepidium sativum L.",
  "Lepidium virginicum", "Lepidium virginicum L.",
  "Lepidium Virginicum", "Lepidium virginicum L.",
  "Leucoium vernum", "Leucojum vernum L.",
  "Ligustrum vulgare", "Ligustrum vulgare L.", 
  "Lilium martagon", "Lilium martagon L.",
  "Limnanthemum nymphaeoides", "Nymphoides peltata (S.G.Gmel.) Kuntze",
  "Limnanthemum Nymphaeoides", "Nymphoides peltata (S.G.Gmel.) Kuntze",
  "Limosella aquatica", "Limosella aquatica L.", 
  "Linaria arvensis", "Linaria arvensis (L.) Desf.",
  "Linaria bipartita", "Linaria bipartita (Vent.) Willd.",
  "Linaria cymbalaria", "Cymbalaria muralis subsp. muralis G.Gaertner, B.Meyer & Scherbius",
  "Linaria Cymbalaria", "Cymbalaria muralis subsp. muralis G.Gaertner, B.Meyer & Scherbius",
  "Linaria genistifolia", "Linaria genistifolia (L.) Mill.",
  "Linaria pilosa (Jacq.) DC.", "Cymbalaria pilosa (Jacq.) L.H.Bailey",
  "Lindernia pyxidaria", "Lindernia pyxidaria Pursh", 
  "Linum usitatissimum", "Linum usitatissimum L.", 
  "Lobelia erinus", "Lobelia erinus L.", 
  "Lolium perenne f. compositum", "Lolium perenne L.",
  "Lolium remotum", "Lolium remotum Schrank", 
  "Lolium temulentum", "Lolium temulentum L.",
  "Lolium temulentum f. arvense", "Lolium temulentum L.",
  "Lolium temulentum var. arvense", "Lolium temulentum L.",
  "Lonicera caprifolium", "Lonicera caprifolium L.",
  "Lonicera morrowii", "Lonicera morrowii Gray", 
  "Lonicera periclymenum", "Lonicera periclymenum L.", 
  "Lonicera xylosteum", "Lonicera xylosteum L.", 
  "Lotus siliquosus", "Lathyrus inconspicuus var. inconspicuus", 
  "Lotus tenuifolius", "Lotus tenuis Waldst. & Kit. ex Willd.",
  "Lunaria annua", "Lunaria annua L.",
  "Lunaria rediviva", "Lunaria rediviva L.",
  "Lupinus angustifolius", "Lupinus angustifolius L.",
  "Luzula nemorosa", "Luzula luzuloides (Lam.) Dandy & Wilmott",
  "Lychnis chalcedonica", "Silene chalcedonica (L.) E.H.L.Krause",
  "Lychnnis Chalcedonica L.", "Silene chalcedonica (L.) E.H.L.Krause",
  "Lychnis coronaria", "Silene coronaria (L.) Clairv.",
  "Lycium halimifolium", "Lycium barbarum L.", 
  "Lycopodium alpinum", "Diphasiastrum alpinum (L.) Holub", 
  "Lycopodium annotinum", "Lycopodium annotinum L.", 
  "Lycopodium annotinum f. integrifolium", "Lycopodium annotinum L.", 
  "Lycopodium chamaecyparissus", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium clavatum", "Lycopodium clavatum L.", 
  "Lycopodium clavatum L. var. tristachyum Nutt. (als Alt)", "Lycopodium clavatum L.", 
  "Lycopodium complanatum", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum L. ssp. anceps (Wallr.)", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum L. ssp. chamaecyparissus ABr.", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium complanatum L. var. L. Chamaecyparissus A, Braun.", "Diphasiastrum tristachyum (Pursh) Holub", 
  "Lycopodium complanatum anceps Wallr.", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium complanatum f. brachystachys", "Diphasiastrum complanatum (L.) Holub", 
  "Lycopodium inundatum", "Lycopodiella inundata (L.) Holub", 
  "Lycopodium selago", "Huperzia selago (L.) Bernh. ex Schrank & Mart", 
  "Lysimachia thyrsiflora", "Lysimachia thyrsiflora L.", 
  "Macleya cordata", "Macleaya cordata (Willd.) R.Br.",
  "Malcolmia maritima", "Malcolmia maritima (L.) W.T.Aiton",
  "Malva moschata", "Malva moschata L.",
  "Malva parviflora", "Malva parviflora L.",
  "Malva verticillata", "Malva verticillata L.",
  "Malva verticillata L.", "Malva verticillata L.",
  "Malva verticillata var. crispa", "Malva verticillata L.",
  "Malva verticillata var. crispa L.", "Malva verticillata L.",
  "Marrubium vulgare", "Marrubium vulgare L.",
  "Matricaria chamomilla", "Matricaria chamomilla L.", 
  "Matricaria inodora", "Tripleurospermum inodorum (L.) Sch.-Bip", 
  "Medicago falcata x sativa", "",
  "Melampyrum cristatum", "Melampyrum cristatum L.", 
  "Melandryum album x rubrum", "",
  "Melandryum album X rubrum", "",
  "Melandryum noctiflorum", "Silene noctiflora L.", 
  "Melandryum rubrum", "Silene dioica subsp. dioica", 
  "Melica ciliata", "Melica ciliata L.",
  "Melica uniflora", "Melica uniflora Retz.", 
  "Melilotus albus", "Melilotus albus Medik.", 
  "Melilotus altissimus", "Melilotus altissimus Thuill.",
  "Melilotus indicus", "Melilotus indicus (L.) All.",
  "Melittis melissophyllum", "Melittis melissophyllum L.", 
  "Menyanthes trifoliata", "Menyanthes trifoliata L.", 
  "Mercurialis annua", "Mercurialis annua L.",
  "Mercurialis perennis", "Mercurialis perennis L.",
  "Meum athamanticum", "Meum athamanticum Jacq.",
  "Mirabilis Jalapa L.", "Mirabilis jalapa L.", 
  "Montia intermedia", "Montia fontana subsp. amporitana Sennen",
  "Montia rivularis", "Montia fontana subsp. fontana Linnaeus",
  "Mulgedium alpinum", "Cicerbita alpina (L.) Wallr.",
  "Mulgedium macrophyllum", "Lactuca macrophylla subsp. macrophylla (Willd.) A.Gray", 
  "Muscari comosum", "Leopoldia comosa (L.) Parl.",
  "Muscari racemosum", "Muscari racemosum Mill.",
  "Myosotis caespitosa", "Myosotis caespitosa DC., 1846", 
  "Myosotis palustris", "Myosotis scorpioides L.", 
  "Myosotis silvatica f. lactea", "Myosotis sylvatica Ehrh. ex Hoffm.", 
  "Myosotis sparsiflora", "Myosotis sparsiflora Pohl",
  "Myriophyllum spicatum", "Myriophyllum spicatum L.", 
  "Myriophyllum verticillatum", "Myriophyllum verticillatum L.", 
  "Myrrhis odorata", "Myrrhis odorata (L.) Scop.", 
  "Narcissus poeticus", "Narcissus poeticus L.",
  "Narcissus Pseudo—Narcissus", "Narcissus pseudonarcissus L.",
  "Narcissus pseudonarcissus", "Narcissus pseudonarcissus L.",
  "Nasturtium officinale", "Nasturtium officinale R.Br.", 
  "Neottia nidus avis", "Neottia nidus-avis (L.) Rich.", 
  "Nepeta Mussini Henckel v. Donnersm.", "Nepeta racemosa subsp. racemosa",
  "Nicandra physaloides", "Physochlaina physaloides (L.) G.Don", 
  "Nicotiana latissima", "Nicotiana tabacum L.",
  "Nicotiana rustica", "Nicotiana rustica L.", 
  "Nigella Damascena", "Nigella damascena L.",
  "Nitella flexilis", "Nitella flexilis (L.) C.Agardh",
  "Nonnea rosea (M. B.) Lk.", "Nonea rosea (M.Bieb.) Link", 
  "Nymphaea candida", "Nymphaea candida J.Presl & C.Presl",
  "Oenanthe aquatica", "Oenanthe aquatica (L.) Poir.",
  "Oenothera fruticosa L.", "Oenothera fruticosa L.",
  "Oenothera muricata", "Oenothera biennis L.", 
  "Omphalodes scorpioides", "Memoremea scorpioides (Haenke) A.Otero, Jim.Mejías, Valcárcel & P.Vargas",
  "Onobrychis viciaefolia", "Onobrychis viciifolia Scop.",
  "Ononis spinosa", "Ononis spinosa L.",
  "Onopordon acanthium", "Onopordum acanthium L.", 
  "Onopordum acanthium", "Onopordum acanthium L.",  
  "Ophioglossum vulgatum", "Ophioglossum vulgatum L.",
  "Ophioglossum vulgatum L.", "Ophioglossum vulgatum L.",
  "Orchis globosa", "Traunsteinera globosa (L.) Rchb.",
  "Orchis incarnata", "Dactylorhiza incarnata (L.) Soó",
  "Orchis mascula", "Orchis mascula (L.) L.",
  "Orchis militaris", "Orchis militaris L.",
  "Orchis sambucina", "Dactylorhiza sambucina (L.) Soó",
  "Ornithogalum Boucheanum", "Ornithogalum boucheanum (Kunth) Asch.", 
  "Ornithogalum nutans", "Ornithogalum nutans L.",
  "Ornithogalum tenuifolium", "Ornithogalum gussonei Ten.",
  "Ornithogalum umbellatum", "Ornithogalum umbellatum L.",
  "Ornithopus perpusillus", "Ornithopus perpusillus L.",
  "Orobanche caryophyllea", "Orobanche caryophyllacea Sm.", 
  "Orobanche lutea", "Orobanche lutea Baumg.",
  "Orobanche pallidiflora", "Orobanche reticulata subsp. pallidiflora (Wimm. & Grab.) Hayek", 
  "Osmunda regalis", "Osmunda regalis L.", 
  "Osmunda regalis L.", "Osmunda regalis L.", 
  "Oxalis tetraphylla", "Oxalis tetraphylla Cav.",
  "Panicum lineare", "Cynodon dactylon (L.) Pers.",
  "Papaver dubium", "Papaver dubium L.",
  "Papaver hybridum L.", "Roemeria hispida Stace", 
  "Papaver somniferum", "Papaver somniferum L.",
  "Papaver somniferum f. laciniatum", "Papaver somniferum L.",
  "Pastinaca sativa", "Pastinaca sativa L.", 
  "Pedicularis palustris", "Pedicularis palustris L.", 
  "Petasites officinalis", "Petasites hybridus subsp. hybridus ", 
  "Petroselinum sativum", "Petroselinum crispum (Mill.) Fuss",
  "Peucedanum cervaria", "Cervaria rivini Gaertn.", 
  "Peucedanum palustre", "Thysselinum palustre (L.) Hoffm.", 
  "Phacelia congesta Hook.", "Phacelia congesta (Douglas ex Lehm.) Hook.",
  "Phacelia tanacetifolia", "Phacelia tanacetifolia Benth.", 
  "Phalaris arundinacea f. picta", "Phalaris arundinacea var. picta Muhl. ex W.P.C.Barton, 1815",
  "Phalaris canariensis", "Phalaris canariensis L.",
  "Phalaris paradoxa", "Phalaris paradoxa L.",
  "Phegopteris dryopteris (L.) Fee", "Gymnocarpium dryopteris (L.) Newman",
  "Phegopteris polypodioides Fée.", "Phegopteris connectilis (Michx.) Watt",
  "Phegopteris robertiana", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phegopteris robertiana (Hoffm.) A. Br.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phegopteris robertianum A. Br.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Phleum pratense", "Phleum pratense L.",
  "Phleum subulatum (Savi) Aschers. et Gr.", "Phleum subulatum (Savi) Asch. & Graebn.",
  "Physalis Alkekengi", "Alkekengi officinarum Moench",
  "Physalis alkekengi", "Alkekengi officinarum Moench",
  "Physocarpus opulifolius", "Physocarpus opulifolius (L.) Maxim.",
  "Phyteuma orbiculare", "Phyteuma orbiculare L.", 
  "Phytolacca decandra", "Phytolacca americana L.",
  "Picris echioides", "Helminthotheca echioides (L) Holub",
  "Pilularia globulifera", "Pilularia globulifera L.",
  "Pinguicula vulgaris", "Pinguicula vulgaris L.",
  "Pinus uliginosa", "Pinus mugo subsp. rotundata (Link) Janch. & H.Neumayer",
  "Pirola media", "Pyrola media Sw.",
  "Pirola uniflora", "Moneses uniflora (L.) A.Gray",
  "Plantago arenaria", "Plantago arenaria Waldst. & Kit.", 
  "Plantago intermedia", "Plantago uliginosa subsp. uliginosa",
  "Plantago lanceolata", "Plantago lanceolata L.",
  "Poa bulbosa", "Poa bulbosa L.", 
  "Poa chaixii var. remota", "Poa remota Forselles", 
  "Poa nemoralis var. montana", "Poa nemoralis L.",
  "Polemonium coeruleum", "Polemonium caeruleum L.", 
  "Polygala amara", "Polygala amara L.", 
  "Polygonatum officinale", "Polygonatum officinale All.",
  "Polygonum cuspidatum", "Reynoutria japonica Houtt.",
  "Polygonum mite", "Persicaria mitis (Schrank) Assenov",
  "Polyporus lucidus","Ganoderma lucidum (Curtis) P.Karst.",
  "Polypogon monspeliensis", "Polypogon monspeliensis (L.) Desf.",
  "Polypodium Robertianum Hoffm.", "Gymnocarpium robertianum (Hoffm.) Newman",
  "Polypodium dryopteris", "Gymnocarpium dryopteris (L.) Newman",
  "Polypodium phegopteris", "Phegopteris connectilis (Michx.) Watt",
  "Polypodium vulgare", "Polypodium vulgare L.", 
  "Polypodium vulgare L.", "Polypodium vulgare L.",
  "Populus alba", "Populus alba L.",
  "Potamogeton densus L.", "Groenlandia densa (L.) Fourr.", 
  "Potamogeton obtusifolius", "Potamogeton obtusifolius Mert. & W.D.J.Koch",
  "Potamogeton pectinatus", "Stuckenia pectinata (L.) Börner",
  "Potamogeton praelongus", "Potamogeton praelongus Wulfen",
  "Potamogeton pusillus", "Potamogeton pusillus L.",
  "Potamogeton rufescens", "Potamogeton alpinus subsp. alpinus Balbis",
  "Potentilla alba", "Potentilla alba L.", 
  "Potentilla arenaria", "Potentilla incana Borkh.", 
  "Potentilla canescens", "Potentilla inclinata Vill.",
  "Potentilla fragariastrum", "Potentilla sterilis (L.) Garcke",
  "Potentilla norvegica", "Potentilla norvegica L.",
  "Potentilla opaca", "Potentilla heptaphylla subsp. heptaphylla",
  "Potentilla palustris", "Comarum palustre L.",
  "Potentilla recta", "Potentilla recta L.",
  "Potentilla supina", "Potentilla supina L.",
  "Potentilla verna", "Potentilla verna L.",
  "Potentilla verna f. parviflora f. nov.", "Potentilla verna L.",
  "Potentilla wiemanniana", "Potentilla wiemanniana Spreng. ex Günther & Schummel",
  "Primula elatior f. colorata Pax", "Primula elatior subsp. elatior",
  "Primula officinalis", "Primula officinalis Wulfen, 1778", 
  "Prunus Cerasus", "Prunus cerasus L.",
  "Prunus domestica", "Prunus domestica L.",
  "Prunus italica", "Prunus domestica subsp. insititia (L.) Bonnier & Layens",
  "Prunus serotina", "Prunus serotina Ehrh.",
  "Pteris aquilina", "Pteridium aquilinum (L.) Kuhn",
  "Pulicaria vulgaris", "Pulicaria vulgaris Gaertn.", 
  "Pulmonaria angustifolia", "Pulmonaria angustifolia L.",
  "Quercus robur X Quercus sessiliflora", "Quercus ×rosacea Bechst.",
  "Quercus robur var. longipetiolati Schröter", "Quercus robur L.",
  "Ranunculus auricomus var. fallax", "Ranunculus fallax (Wimm. & Grab.) Schur",
  "Ranunculus auricomus f. fallax", "Ranunculus fallax (Wimm. & Grab.) Schur",
  "Ranunculus bulbosus X Ranunculus polyanthemos", "",
  "Ranunculus cassubicus", "Ranunculus cassubicus L.",
  "Ranunculus flaccidus", "Ranunculus trichophyllus subsp. trichophyllus Chaix ex Villars", 
  "Ranunculus lanuginosus", "Ranunculus lanuginosus L.",
  "Ranunculus lingua", "Ranunculus lingua L.",
  "Ranunculus polyanthemus", "Ranunculus polyanthemos L.", 
  "Ranunculus sceleratus", "Ranunculus sceleratus L.",
  "Ranunculus sceleratus f. natans Gluck", "Ranunculus sceleratus subsp. sceleratus L., 1753",
  "Raphanus raphanistrum var. purpurascens Dum.", "Raphanus raphanistrum L.",
  "Rapistrum rugosum", "Rapistrum rugosum (L.) All.",
  "Reseda lutea", "Reseda lutea L.",
  "Reseda lutea var. crispa J. Müller", "Reseda lutea subsp. lutea",
  "Reseda luteola", "Reseda luteola L.",
  "Reseda odorata", "Reseda odorata L.",
  "Rhus Toxicodendron", "Toxicodendron radicans subsp. radicans (Linnaeus) Kuntze",
  "Rhynchospora alba", "Rhynchospora alba (L.) Vahl",
  "Rhynchospora fusca", "Rhynchospora fusca (L.) W.T.Aiton",
  "Ribes alpinum", "Ribes alpinum L.",
  "Ribes aureum", "Ribes aureum Pursh",
  "Ribes grossularia", "Ribes uva-crispa var. sativum DC.",
  "Ribes nigrum", "Ribes nigrum L.",
  "Robinia pseudacacia", "Robinia pseudoacacia L.",
  "Roripa amphibia", "Rorippa amphibia (L.) Besser",
  "Roripa austriaca", "Rorippa austriaca (Crantz) Besser", 
  "Roripa austriaca X silvestre", "",
  "Roripa islandica", "Rorippa islandica (Oeder) Borbás",
  "Roripa prostrata (Bergeret) Schinz et Thell.", "Rorippa anceps (Wahlenb.) Rchb.",
  "Rosa agrestis", "Rosa agrestis Savi", 
  "Rosa cinnamomea", "Rosa cinnamomea Borrer ex Hook.",
  "Rosa coriifolia", "Rosa caesia Sm.",
  "Rosa elliptica", "Rosa inodora Fr.",
  "Rosa eutomentosa", "Rosa tomentosa Sm.",
  "Rosa gallica", "Rosa gallica L.", 
  "Rosa gallica x dumetorum", "", 
  "Rosa glauca", "Rosa glauca Pourr.",
  "Rosa hirtifolia (H. Br.) Schalow", "Rosa corymbifera Borkh.",
  "Rosa humilis", "Rosa gallica L.",
  "Rosa incana (Kit.) Schalow", "Rosa incana Kit. ex Tratt.",
  "Rosa inodora (Fries) Schalow", "Rosa inodora Fr.",
  "Rosa Jundzillii", "Rosa marginata Wallr.",
  "Rosa obtusifolia (Desv.) Schalow", "Rosa obtusifolia Desv.",
  "Rosa omissa", "Rosa sherardii Davies",
  "Rosa pimpinellifolia", "Rosa pimpinellifolia Jacq.",
  "Rosa pomifera", "Rosa villosa L.",
  "Rosa rubiginosa", "Rosa rubiginosa L.",
  "Rosa rugosa", "Rosa rugosa Thunb.",
  "Rosa scabriuscula", "Rosa sherardii Davies",
  "Rosa silesiaca", "Rosa agrestis Savi", 
  "Rosa silesiaca Nimptsch", "Rosa agrestis Savi", 
  "Rosa silesiaca f. inopinata mh. f. nov.", "Rosa agrestis Savi", 
  "Rosa subcanina", "Rosa subcanina (Christ) Dalla Torre & Sarnth.",
  "Rubus salisburgensis", "Rubus salisburgensis Focke",
  "Rubus saxatilis", "Rubus saxatilis L.",
  "Rudbeckia hirta", "Rudbeckia hirta L.",
  "Rudbeckia laciniata", "Rudbeckia laciniata L.", 
  "Rudbekia laciniata", "Rudbeckia laciniata L.", 
  "Rumex acetosella f. ramosissima", "Rumex acetosella L.",
  "Rumex acetoselia f. ramosissima mh. f. nov.", "Rumex acetosella L.",
  "Rumex alpinus", "Rumex alpinus L.",
  "Rumex aquaticus", "Rumex aquaticus L.",
  "Rumex aquaticus x obtusifolius", "",
  "Rumex Hydrolapathum", "Rumex hydrolapathum (Scop.) Huds.",
  "Rumex maritimus", "Rumex maritimus L.",
  "Rumex maximus", "Rumex hydrolapathum (Scop.) Huds.",
  "Rumex pulcher L.", "Rumex pulcher L.",
  "Rumex salicifolius Weinm.", "Rumex salicifolius Weinm.",
  "Sagina apetala", "Sagina apetala Ard.",
  "Sagina Linnaei", "Sagina saginoides (L.) Karst.",
  "Sagina nodosa", "Sagina nodosa (L.) Fenzl", 
  "Salix acutifolia", "Salix acutifolia Willd.",
  "Salix aurita", "Salix aurita L.", 
  "Salix aurita-cinerea", "", 
  "Salix aurita-livida", "", 
  "Salix aurita-purpurea", "Salix aurita × purpurea", 
  "Salix cinerea-purpurea", "Salix cinerea × purpurea",
  "Salix cinerea-viminalis", "Salix ×holosericea Willd.", 
  "Salix daphnoides", "Salix daphnoides Vill.",
  "Salix dasyclados", "Salix ×dasyclados Wimm.", 
  "Salix fragilis-pentandra", "Salix fragilis x pentandra",
  "Salix hastata-silesiaca", "", 
  "Salix nigricans", "Salix myrsinifolia Salisb.",
  "Salix nigricans-repens", "", 
  "Salix pentandra", "Salix pentandra L.",
  "Salix pruinosa Wendl.", "Salix acutifolia Willd.",
  "Salix purpurea-repens", "Salix purpurea x repens",
  "Salix repens", "Salix repens L.",
  "Salix repens var. rosmarinifolia", "Salix rosmarinifolia L.",
  "Salix silesiaca-Lapponum", "", 
  "Salix silesiaca-caprea", "", 
  "Salix viminalis-aurita f. glabrata", "", 
  "Salsola kali", "Kali turgidum (Dumort.) Gutermann",
  "Salsola Kali", "Kali turgidum (Dumort.) Gutermann",
  "Salvia glutinosa", "Salvia glutinosa L.",
  "Salvia nemorosa", "Salvia nemorosa L.",
  "Salvia pratensis", "Salvia pratensis L.", 
  "Salvia pratensis f. rostrata", "Salvia pratensis subsp. pratensis",
  "Salvia verticillata", "Salvia verticillata L.",
  "Salvia viridis var. horminum", "Salvia viridis L.",
  "Salvinia natans", "Salvinia natans (L.) All.",
  "Sambucus ebulus", "Sambucus ebulus L.",
  "Sambucus Ebulus", "Sambucus ebulus L.",
  "Sambucus racemosa", "Sambucus racemosa L.", 
  "Sambucus racemosa f. laciniata", "Sambucus racemosa var. laciniata A.Gray, 1884",
  "Sanguisorba minor", "Poterium sanguisorba subsp. sanguisorba L.",
  "Sanicula europaea", "Sanicula europaea L.", 
  "Santolina Chamaecyparissus L.", "Santolina chamaecyparissus L.",
  "Saponaria ocymoides L.", "Saponaria ocymoides L.",
  "Saponaria officinalis", "Saponaria officinalis L.",
  "Sarothamnus scoparius", "Cytisus scoparius (L.) Link",
  "Satureja acinos", "Clinopodium acinos (L.) Kuntze",
  "Satureja hortensis", "Satureja hortensis L.",
  "Saxifraga granulata f. stenoloba f. nov.", "Saxifraga granulata L.",
  "Saxifraga tridactylites", "Saxifraga tridactylites L.",
  "Scabiosa canescens", "Scabiosa canescens Waldst. & Kit.", 
  "Scandix pecten Veneris", "Scandix pecten-veneris L.",
  "Scheuchzeria palustris", "Scheuchzeria palustris L.",
  "Scilla bifolia", "Scilla bifolia L.",
  "Scirpus holoschoenus", "Scirpoides holoschoenus (L.) Soják",
  "Scirpus lacustris", "Schoenoplectus lacustris (L.) Palla",
  "Scirpus maritimus", "Bolboschoenus maritimus (L.) Palla", 
  "Scirpus ovatus", "Eleocharis ovata (Roth) Roem. & Schult.",
  "Scirpus pauciflorus", "Eleocharis quinqueflora (Hartmann) O.Schwarz", 
  "Scirpus radicans", "Scirpus radicans Schkuhr",
  "Scirpus tabernaemontani", "Schoenoplectus tabernaemontani (C.C.Gmel.) Palla",
  "Scirpus Tabernaemontani", "Schoenoplectus tabernaemontani (C.C.Gmel.) Palla",
  "Scirpus mucronatus", "Schoenoplectiella mucronata (L.) J.Jung & H.K.Choi",
  "Scleranthus annuus X perennis", "Scleranthus annuus × perennis", 
  "Scleropoa rigida", "Catapodium rigidum (L.) C.E.Hubb.",
  "Scolymus hispanicus L.", "Scolymus hispanicus L.",
  "Scorzonera humilis", "Scorzonera humilis L.",
  "Scorzonera purpurea", "Scorzonera purpurea L.",
  "Scrofularia alata", "Scrophularia alata A.Gray", 
  "Scutellaria hastifolia", "Scutellaria hastifolia L.",
  "Secale cereale", "Secale cereale L.", 
  "Sedum album", "Sedum album L.",
  "Sedum reflexum", "Petrosedum rupestre subsp. rupestre", 
  "Sedum spurium", "Sedum spurium Sibth. ex Nyman, 1879",
  "Sedum villosum", "Sedum villosum L.",
  "Selaginella apoda", "Selaginella apoda (L.) Spring",
  "Selaginella selaginoides", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.",
  "Selaginella spiculosa", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.", 
  "Selaginella spinulosa", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.",            
  "Selaginella spinulosa A. Br.", "Selaginella selaginoides (L.) Schrank & C.F.P.Mart.", 
  "Sempervivum soboliferum", "Sempervivum globiferum subsp. globiferum",
  "Senecio barbaraeifolius", "Jacobaea erratica (Bertol.) Fourr.",
  "Senecio crispatus", "Tephroseris crispa (Jacq.) Schur",
  "Senecio fluviatilis", "Senecio sarracenicus L.",
  "Senecio fuchsi", "Senecio ovatus subsp. ovatus (G.Gaertn., B.Mey. & Scherb.) Hoppe",
  "Senecio Jacobaea var. erucoides", "Jacobaea vulgaris Gaertn.", 
  "Senecio nemorensis", "Senecio nemorensis L.",
  "Senecio vernalis", "Senecio vernalis Waldst. & Kit.", 
  "Serratula tinctoria var. pinnata Kit.", "Serratula tinctoria L.",
  "Seseli coloratum", "Seseli annuum subsp. annuum", 
  "Setaria italica", "Setaria italica (L.) P.Beauv.",
  "Setaria Italica var. maxima Alef", "Setaria italica (L.) P.Beauv.",
  "Setaria viridis f. fallax Bruhin", "Setaria viridis (L.) P.Beauv.",
  "Silene armeria", "Atocion armeria (L.) Fourr.",
  "Silene coeli rosa", "Eudianthe coeli-rosa (L.) Endl.", 
  "Silene coeli rosa (L.) A. Br.", "Eudianthe coeli-rosa (L.) Endl.", 
  "Silene dichotoma", "Silene dichotoma Ehrh.",
  "Silene gallica", "Silene gallica L.",
  "Silene nutans f. glabra", "Silene nutans subsp. nutans",
  "Silene otites", "Silene otites (L.) Wibel", 
  "Silene Otites", "Silene otites (L.) Wibel", 
  "Silene pendula", "Silene pendula L.",
  "Silybum marianum", "Silybum marianum (L.) Gaertn.",
  "Sinapis alba", "Sinapis alba L.",
  "Sinapis alba f. glabrata", "Sinapis alba subsp. dissecta (Lag.) Simonk.",
  "Sisymbrium orientale", "Sisymbrium orientale L.",
  "Sisymbrium sinapistrum", "Sisymbrium altissimum L.",
  "Sisymbrium Sinapistrum", "Sisymbrium altissimum L.", 
  "Sisymbrium Sophia", "Descurainia sophia (L.) Webb ex Prantl",
  "Sisymbrium Wolgense", "Sisymbrium volgense M.Bieb. ex E.Fourn.",
  "Sisymbrium Wolgense M. Bieb.", "Sisymbrium volgense M.Bieb. ex E.Fourn.",
  "Sisyrinchium angustufolium", "Sisyrinchium angustifolium Mill.",
  "Solanum rostratum", "Solanum angustifolium Houst. ex Mill.",
  "Solanum sarachoides Sendtner", "Solanum sarrachoides Sendtn.",
  "Solanum sisymbrifolium Lam.", "Solanum sisymbriifolium Lam.",
  "Solanum sodomaeum L.", "Solanum anguivi Lam.",
  "Solanum villosum", "Solanum villosum Mill.",
  "Solanum villosum var. alatum", "Solanum alatum Moench",
  "Solidago canadensis", "Solidago canadensis L.",
  "Solidago serotina", "Solidago serotina Retz., 1781",
  "Sorbaria sorbifolia", "Sorbaria sorbifolia (L.) A.Braun",
  "Sparganium diversifolium", "Sparganium diversifolium Asch.",
  "Sparganium minimum", "Sparganium minimum Hill, 1756",
  "Sparganium natans", "Sparganium natans L.",
  "Sparganium ramosum", "Sparganium erectum L.",
  "Sparganium simplex", "Sparganium emersum Rehmann",
  "Specularia Speculum", "Legousia speculum-veneris (L.) Chaix",
  "Specularia speculum", "Legousia speculum-veneris (L.) Chaix",
  "Spinacia oleracea", "Spinacia oleracea L.",
  "Spiraea chamaedryfolia", "Spiraea chamaedryfolia L.",
  "Spiraea chamaedrifolia", "Spiraea chamaedryfolia L.",
  "Spiraea obovata W. u. K.", "Spiraea hypericifolia subsp. obovata (Waldst. & Kit. ex Willd.) H.Huber",
  "Spiraea salicifolia", "Spiraea salicifolia L.",
  "Stachys annua", "Stachys annua (L.) L.",
  "Stachys alpina f. ochroleucus Correns", "Stachys alpina L.",
  "Stachys arvensis", "Stachys arvensis (L.) L.",
  "Stachys grandiflora", "Betonica macrantha K.Koch",
  "Stachys recta", "Stachys recta L.", 
  "Stachys rectus", "Stachys recta L.", 
  "Stellaria friesiana", "Stellaria longifolia (Regel) Muhl. ex Willd.",
  "Stellaria media f. neglecta", "Stellaria neglecta (Lej.) Weihe", 
  "Stellaria nemorum", "Stellaria nemorum L.",
  "Stenactis annua Nees", "Erigeron annuus (L.) Pers.",
  "Stratiotes aloides", "Stratiotes aloides L.", 
  "Stratiotes Aloides", "Stratiotes aloides L.", 
  "Struthiopteris germanica", "Matteuccia struthiopteris subsp. struthiopteris",
  "Sturmia Loeselii", "Liparis loeselii (L.) Rich.",
  "Suaeda maritima Dum.", "Suaeda maritima (L.) Dumort.",
  "Succisa pratensis f. incisa", "Succisa pratensis Moench",
  "Sweertia perennis var. flore sulphureo", "Swertia perennis L.", 
  "Symphytum asperum X officinale", "Symphytum ×uplandicum Nyman", 
  "Symphytum officinale f. bohemicum", "Symphytum bohemicum F.W.Schmidt",
  "Symphytum tuberosum", "Symphytum tuberosum L.", 
  "Symphoricarpus racemosus", "Symphoricarpos albus (L.) K.Koch",
  "Symphoricarpus racemosus Michx.", "Symphoricarpos albus (L.) K.Koch",
  "Taxus baccata", "Cephalotaxus harringtonii var. harringtonii",
  "Teesdalea nudicaulis", "Teesdalia nudicaulis (L.) W.T.Aiton",
  "Teucrium scordium", "Teucrium scordium L.",
  "Teucrium Scordium", "Teucrium scordium L.",
  "Teucrium Scorodonia", "Teucrium scorodonia L.",
  "Thalictrum aquilegifolium", "Thalictrum aquilegiifolium L.",
  "Thalictrum flavum", "Thalictrum flavum L.", 
  "Thalictrum simplex", "Thalictrum simplex L.", 
  "Thesium alpinum", "Thesium alpinum L.",
  "Thesium ebracteatum", "Thesium ebracteatum Hayne",
  "Thesium intermedium", "Thesium linophyllon L.", 
  "Thesium pratense", "Thesium pyrenaicum Pourr.",
  "Thladiantha dubia", "Thladiantha dubia Bunge",
  "Thladiantha dubia Bunge", "Thladiantha dubia Bunge",
  "Thlaspi alpestre", "Thlaspi alpestre Luce",
  "Thlaspi arvense", "Thlaspi arvense L.",
  "Thymus alpestris Tausch", "Thymus alpestris (Celak.) Tausch ex A.Kern.",
  "Thymus parviflorus Opiz", "Thymus pulegioides subsp. montanus (Trevir.) Ronniger", 
  "Thymus pulegioides L. var. Chamaedrys (Fries) Ronn.", "Thymus pulegioides L.", 
  "Thymus pulegioides L. var. gracilicaulis Ronn.", "Thymus pulegioides L.",
  "Thymus pulegioides L. var. ovatus (Mill.) Ronn.", "Thymus pulegioides L.",
  "Thymus pulegioides X serpyllum", "",
  "Thymus serpyllum L. em. Fries var. rigidus (Wimmer et Gr.) Ronn.", "Thymus serpyllum var. rigidus Wimmer & Grab.",
  "Thymus sudeticus Opiz", "Thymus pulcherrimus Schur",
  "Tilia alba Ait.", "Tilia tomentosa Moench",
  "Torilis arvensis (Huds.) Link ssp. heterophylla (Guss.) Thell.", "Torilis africana Spreng.",
  "Torilis arvensis ssp. heterophylla", "Torilis africana Spreng.",  
  "Torilis nodosa", "Torilis nodosa (L.) Gaertn.",
  "Torilis nodosa (L.) Gaertn.", "Torilis nodosa (L.) Gaertn.",
  "Trapa natans", "Trapa natans L.",
  "Tragopogon glaber (L.) Benth. et. Hook.", "Geropogon hybridus (L.) Sch.Bip.",
  "Tragopogon orientalis", "Tragopogon orientalis L.",
  "Tragopogon pratensis", "Tragopogon pratensis L.",
  "Tragopogon pratensis f. tortilis G. F. W. Meyer", "Tragopogon pratensis L.",
  "Trientalis europaea", "Lysimachia europaea (L.) U.Manns & Anderb.",
  "Trientalis europaeus", "Lysimachia europaea (L.) U.Manns & Anderb.",
  "Trifolium alpestre", "Trifolium alpestre L.",
  "Trifolium echinatum Bieb. ssp. constantinopolitanum (Ser.) Gibelli et Belli", "", 
  "Trifolium glomeratum L. var. minus Rouy", "", 
  "Trifolium hybridum", "Trifolium hybridum L.",
  "Trifolium lappaceum L.", "Trifolium lappaceum L.", 
  "Trifolium ochroleucum", "Trifolium ochroleucon subsp. ochroleucon",
  "Trifolium resupinatum", "Trifolium resupinatum L.",
  "Trifolium spadiceum", "Trifolium spadiceum L.",
  "Triglochin maritima", "Triglochin maritima L.",
  "Triglochin palustris", "Triglochin palustris L.", 
  "Triticum durum", "Triticum turgidum subsp. durum (Desf.) Husn.",
  "Triticum durum Desf.", "Triticum turgidum subsp. durum (Desf.) Husn.",
  "Trollius europaeus", "Trollius europaeus L.",
  "Tropaeolum majus", "Tropaeolum majus L.",
  "Tulipa silvestris", "Tulipa sylvestris L.",
  "Turritis glabra", "Turritis glabra L.",
  "Typha angustifolia", "Typha angustifolia L.",
  "Typha latifolia", "Typha latifolia L.",
  "Ulex europaeus", "Ulex europaeus L.",
  "Ulmaria filipendula", "Filipendula vulgaris Moench",
  "Ulmus campestris var. suberosa", "Ulmus minor subsp. minor",
  "Ulmus montana", "Ulmus glabra Huds.",
  "Ulmus pedunculata", "Ulmus laevis Pall.",
  "Utricularia intermedia", "Utricularia intermedia Hayne",
  "Utricularia minor", "Utricularia minor L.",
  "Utricularia neglecta", "Utricularia ×neglecta Lehm.",
  "Utricularia vulgaris", "Utricularia vulgaris L.",
  "Vaccaria parviflora", "Gypsophila vaccaria (L.) Sm.",
  "Vaccinium oxycoccus", "Vaccinium oxycoccos L.",
  "Vaccinium Oxycoccus", "Vaccinium oxycoccos L.",
  "Vaccinium uliginosum", " Vaccinium uliginosum L.",
  "Valeriana dioeca", "Valeriana dioica L.",
  "Valeriana exaltata", "Valeriana officinalis L.",
  "Valeriana officinalis f. exaltata", "Valeriana officinalis L.",
  "Valeriana polygama", "Valeriana elongata Jacq.",
  "Valeriana sambucifolia", "Valeriana sambucifolia J.C.Mikan ex Pohl",
  "Valerianella carinata", "Valeriana carinata (Loisel.) Christenh. & Byng",
  "Valerianella rimosa", "Valerianella rimosa Bastard",
  "Veratrum album", "Veratrum album L.",
  "Verbascum blattaria", "Verbascum blattaria L.", 
  "Verbascum Lychnitis", "Verbascum lychnitis L.",
  "Verbascum phlomoides", "Verbascum phlomoides L.",
  "Verbascum Thapsus", "Verbascum thapsus L.",
  "Verbascum thapsiforme x thapsus", "",
  "Veronica anagallis", "Veronica anagallis L.",
  "Veronica longifolia", "Veronica longifolia L.",
  "Veronica scutellata", "Veronica scutellata L.",
  "Veronica spicata", "Veronica spicata L.",
  "Veronica teucrium", "Veronica teucrium L.",
  "Vicia cassubica", "Vicia cassubica L.",
  "Vicia cracca var. alpestris Čel.", "",
  "Vicia dumetorum", "Vicia dumetorum L.",
  "Vicia Ervilia (L.) Willd.", "Vicia ervilia (L.) Willd.", 
  "Vicia grandiflora", "Vicia grandiflora Scop.",
  "Vicia lathyroides", "Vicia lathyroides L.",
  "Vicia lutea L. f. caerulea Arcang.", "", 
  "Vicia pannonica", "Vicia pannonica Crantz",
  "Vicia pannonica f. purpurascens", "Vicia pannonica Crantz",
  "Vicia pannonica var. typica", "Vicia pannonica Crantz",
  "Vicia silvatica", "Vicia sylvatica L.",
  "Vicia tenuifolia", "Vicia tenuifolia Roth",
  "Vicia villosa", "Vicia villosa Roth",
  "Vicia villosa ssp. varia", "Vicia villosa Roth",
  "Vinca minor", "Vinca minor L.", 
  "Vincetoxicum officinale", "Vincetoxicum hirundinaria Medik.",
  "Viola canina X Viola persicifolia", "", 
  "Viola canina X Viola riviniana", "",
  "Viola elatior", "Viola elatior Fr.", 
  "Viola elatior Fries", "Viola elatior Fr.", 
  "Viola elatior f . humilis Uechtritz", "",
  "Viola elatior x pumila", "",
  "Viola epipsila", "Viola epipsila Ledeb.", 
  "Viola hirta", "Viola hirta L.", 
  "Viola montana x riviniana", "", 
  "Viola mirabilis", "Viola mirabilis L.", 
  "Viola palustris", "Viola palustris L.", 
  "Viola persicifolia", "Viola persicifolia Schreb.",
  "Viola persicifolia x  canina", "",
  "Viola rupestris var. glaberrima", "Viola rupestris subsp. glaberrima (Murb.) Vl.V.Nikitin",
  "Viola tricolor f. saxatilis", "Viola tricolor subsp. alpestris (Ging.) Ces.",
  "Viola silvestris", "Viola reichenbachiana Jord. ex Boreau",
  "Viscum album", "Viscum album L.",
  "Viscum album var. laxum", "Viscum laxum Boiss. & Reut.",
  "Vulpia ciliata", "Festuca ciliata Pers.",
  "Vulpia ciliata (Danth.) Link", "Festuca ciliata Pers.",
  "Xanthium spinosum", "Xanthium spinosum L.",
  "Xanthium strumarium", "Xanthium strumarium L.",
  "Xeranthemum annuum", "Xeranthemum annuum L.",
  "Zannichellia palustris", "Zannichellia palustris L.",
  "Zea mays", "Zea mays L."
)

an <- matrix(unlist(an), nrow=length(an)/2, byrow=TRUE) |>
  as.data.frame()
names(an) <- c("species", "accepted_name")

# an <- an |>  
#   unique() |>
#   dplyr::arrange(species)
#   
# message(
#   paste0("\"", an[, 1], "\", \"", an[,2], "\", \n")
# )

m <- jahres |>
  subset(select = "species") |>
  dplyr::left_join(an, by = "species") |>
  unique() |>
#  subset(is.na(accepted_name) | accepted_name == "") |>
  subset(is.na(accepted_name)) |>
  dplyr::arrange(species) 
# |>
#  as.matrix()

print(m)

